### ISSUE TITLE
Exception in BuiltinSSLAdapter "The handshake operation timed out"

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1036]
Originally reported by: **Anonymous**

---

Using BuiltinSSLAdapter CherryPy crashes with SSLError ("_ssl.c:484: The handshake operation timed out") after some successful request when browsing with Chromium. Does not occur with Internet Explorer.

CherryPy 3.2.0rc1[[BR]]
Microsoft Windows [Version 6.1.7600]/32-Bit[[BR]]
Chromium 10.0.605.0 (68468)[[BR]]
Python 2.7.1[[BR]]
OpenSSL 1.0.0c 2 Dec 2010[[BR]]

Workaround:[[BR]]
File: site-packages/cherrypy/wsgiserver/ssl_builtin.py[[BR]]
Method: BuiltinSSLAdapter.wrap()[[BR]]
append to the except-block before the raise statement:

```
#!python
elif not e.errno and str(e).split(None, 1)[1] == "The handshake operation timed out":
#    print __name__ + ".BuiltinSSLAdapter." + BuiltinSSLAdapter.wrap.__name__ + "() " + str(type(e)) + " " + str(e)
    return None, {}
```

Reported by daniel@redneck-engineering.com

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1036

**Comment by Safihre** [comment]
This is fixed by #1499.
