### ISSUE TITLE
WSPB plugin tests hangs on Mac

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1060]
Originally reported by: **Anonymous**

----------------------------------------

I'm using Mac OS X 10.6.7, using the Python 2.6.1 that comes with the OS.

When I issue `nosetest -s tests`, a number of tests in `test_states:PluginTests` and `test_states:SignalHandlingTests` hangs on the Mac. It seems that subprocesses spawned using `os.P_WAIT` can't listen on network sockets on the Mac. When `self.getPage()` is called subsequently, the HTTPConnection.getresponse() call gets stuck in openUrl().

These tests work perfectly under Linux however. Not sure how to fix them, it would be nice if they pass under the Mac too as the included tests offer some example codes to test custom plugins and tools.

Reported by wyuenho@gmail.com

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1060

**Comment by jaraco** [comment]
Although maybe valid at one time, I'm running the tests on Mac now without this issue, so I'm assuming it's been fixed.
