### ISSUE TITLE
SO_REUSEADDR should not be used on windows

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1088]
Originally reported by: **Anonymous**

---

The standard idiom of creating a socket with SO_REUSEADDR before binding, should not be done on windows.  The meaning of this socket option is quite different on windows.  On windows, the default behaviour is as though SO_REUSEADDR had been specified on unix.
If this flag is specified, it is possible to bind to a port that is actually _in use_.
See for example this discussion from twisted:  http://twistedmatrix.com/trac/ticket/1151

And this documentaton on the flag and its windows specific colleagues:
http://msdn.microsoft.com/en-us/library/ms740621(v=vs.85).aspx

Reported by kristjan@ccpgames.com

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1088

**Comment by kyrias** [comment]
Quickly looking over this, this would need to be changed in the flup WSGI servers rather than cherrypy, since the socket code itself is in those modules rather than in cherrypy.

**Comment by webknjaz** [comment]
@kyrias, flup is a third-party we don't control. It is an optional dependency.
CherryPy 🍒 itself is used to implement its own WSGI, which has been factored out into a separate Cheroot distribution. Current issue is about that separate repository now.
Please consider sending PR there :)

**Comment by kyrias** [comment]
Ah, completely missed that, seems I was looking in the wrong place, sorry 'bout that!
