### ISSUE TITLE
Failed installing to alternate directory (distutils, pip)

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1090]
Originally reported by: **guest (Bitbucket: [guest](http://bitbucket.org/guest), GitHub: [guest](http://github.com/guest))**

---

SUMMARY:
Couldn't install CherryPy to alternate directory using PIP. It fails at 'intall_data'.

FIX:
I comment line 110 in setup.py: fix_data_files(data_files)

DESCRIPTION OF PROBLEM:
Note: This was using Jython but guess it would be the same with CPython.

Alternate directory: /opt/nhery/lib/jython2.5.2/site-packages
Default directory (don't have permissions): /opt/fddata/jython2.5.2/Lib/site-packages

I have a /opt/fddata/jython2.5.2/Lib/distutils/distutils.cfg that looks like:
[install]
install_lib = /opt/nhery/lib/jython2.5.2/site-packages

Works fine until install_data
Output of 'pip install cherrypy':

......
byte-compiling /opt/nhery/lib/jython2.5.2/site-packages/cherrypy/tutorial/bonus-sqlobject.py to bonus-sqlobject$py.class

byte-compiling /opt/nhery/lib/jython2.5.2/site-packages/cherrypy/tutorial/tut02_expose_methods.py to tut02_expose_methods$py.class

running install_data

creating /opt/fddata/jython2.5.2/Lib/site-packages/cherrypy

error: could not create '/opt/fddata/jython2.5.2/Lib/site-packages/cherrypy': Permission denied

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1090

**Comment by jaraco** [comment]
I'm assuming this is fixed by #1539.
