### ISSUE TITLE
Binary builds only include one wsgiserver.

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1110]
Originally reported by: **hunsen (Bitbucket: [hunsen](http://bitbucket.org/hunsen), GitHub: [hunsen](http://github.com/hunsen))**

----------------------------------------

As the title says, only wsgiserver2.py found in the lib directory after installing cherrypy using CherryPy-3.2.2.win32.exe. It would import wsgiserver3 module while you are running python3, so it would throw importError.
btw, found it is included in CherryPy-3.2.2.zip package.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1110

**Comment by jaraco** [comment]
Fixed in 9501729f52d8
