### ISSUE TITLE
Connection: Keep-Alive requires Kamel-Kasing

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1115]
Originally reported by: **Chris McDonough (Bitbucket: [chrism](http://bitbucket.org/chrism), GitHub: [chrism](http://github.com/chrism))**

---

I'm not even sure this is a bug, because I can't divine it from any spec, but line 724 of wsgiserver2.py looks like this:

```
if self.inheaders.get("Connection", "") != "Keep-Alive":
    self.close_connection = True
```

If an HTTP/1.0 client sends a Connection header with the value "keep-alive" (lowercase), this if will be True, and the connection will be closed.  Maybe if self.inheaders.get('Connection', '').lower() == 'keep-alive' would be better here, even if the spec doesn't allow for it?

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1115

**Comment by DeviaVir** [comment]
I'm taking a stab at this one.

**Comment by DeviaVir** [comment]
Looks like this issue is outdated, the only mention of `Keep-Alive` is applied in tests, i.e. in:
`test_conn.py` and `test_mime.py`. And there the tests set them.

Nominating this to be closed instead. @webknjaz

**Comment by webknjaz** [comment]
@DeviaVir thanks
