### ISSUE TITLE
ssl_adapters is not in __all__

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1121]
Originally reported by: **mmarkk (Bitbucket: [mmarkk](http://bitbucket.org/mmarkk), GitHub: [mmarkk](http://github.com/mmarkk))**

----------------------------------------

ssl_adapters in the wsgiserver/wsgiserver2.py is not exported in "underscore underscore all underscore underscore", so users can not register custom ssl adapters

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1121

**Comment by jaraco** [comment]
Also, wsgiserver3 is the same way. However, it's not the case that "users can not register custom ssl adapters" due to that.
