### ISSUE TITLE
ssl_pyopenssl

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1128]
Originally reported by: **Anonymous**

----------------------------------------

File "/usr/local/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/wsgiserver/ssl_pyopenssl.py", line 75, in _safe_call
    if is_reader and errnum in wsgiserver.socket_errors_to_ignore:
AttributeError: 'module' object has no attribute 'socket_errors_to_ignore'

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1128

**Comment by jaraco** [comment]
I suspect this issue is resolved now that the wsgiserver modules have been unified.
