### ISSUE TITLE
documentation bugs + enhancements

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1157]
Originally reported by: **Anonymous**

----------------------------------------

http://docs.cherrypy.org/stable/progguide/REST.html
there is \*\* which has to be ** in the code examples (multiple times)

http://docs.cherrypy.org/stable/progguide/files/downloading.html                                                                                           the BehindApache link is broken(404): http://www.cherrypy.org/wiki/BehindApache                                                                                                             

i think the article/example about downloading files should be modified, or a warning that this is not secure

there are pages which aren't updated since 2005

http://docs.cherrypy.org/stable/refman/_cperror.html#anticipated-http-responses
you could mention, that there is also a 'error_page.default' config posibility...
also descripe some example how to replace default http content type for http errors there
( i think my solution is not nice:
def default_error_page(**kwargs):
       cherrypy.response.headers['Content-type'] = MIMETYPE_PLAIN
       return cherrypy._cperror._HTTPErrorTemplate % kwargs
cherrypy.config.update({'error_page.default': default_error_page})
)

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1157

**Comment by jaraco** [comment]
I tried applying the patch in the repo, and even against the Mercurial hash referenced in the diff, the patch fails to apply:

```
$ hg update -C b0c482
3 files updated, 0 files merged, 0 files removed, 0 files unresolved
$ hg patch doc.patch -d "2012-09-23" --user spaceone doc.patch -m "Applying patch; fixes #1157."
applying doc.patch
applying doc.patch
patching file sphinx/source/concepts/dispatching.rst
Hunk #1 FAILED at 379
1 out of 1 hunks FAILED -- saving rejects to file sphinx/source/concepts/dispatching.rst.rej
patching file sphinx/source/progguide/REST.rst
Hunk #1 FAILED at 207
Hunk #2 FAILED at 220
2 out of 2 hunks FAILED -- saving rejects to file sphinx/source/progguide/REST.rst.rej
patching file sphinx/source/progguide/files/downloading.rst
Hunk #1 FAILED at 6
Hunk #2 FAILED at 41
2 out of 2 hunks FAILED -- saving rejects to file sphinx/source/progguide/files/downloading.rst.rej
transaction abort!
rollback completed
abort: patch failed to apply
```

I welcome others to revisit the issue and develop solutions.
