### ISSUE TITLE
Password protected private key files are not supported by cherrypy.wsgiserver.SSLAdapter

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1165]
Originally reported by: **Anonymous**

---

class cherrypy.wsgiserver.SSLAdapter(certificate, private_key, certificate_chain=None)

does not support password protected private key file.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1165

**Comment by webknjaz** [comment]
Duplicate of #1583
