### ISSUE TITLE
[Python-3.3.0] test_3_Redirect in nosetests -s -v test_session.py takes forever

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1180]
Originally reported by: **Benny Ng (Bitbucket: [tpng](http://bitbucket.org/tpng), GitHub: @tpng)**

---

Running nosetests -s -v test_session.py, the case test_3_Redirect seems to never return.

I have tested this on both the release version of cherrypy-3.2.2 and the latest source, on both version the test never completes on Python-3.3.0.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1180

**Comment by ghost** [comment]
_Original comment by_ **lakin.wecker (Bitbucket: [lakin.wecker](http://bitbucket.org/lakin.wecker), GitHub: @lakinwecker?)**:

---

Thanks for the information about your environment. I don't personally have the same environment as you to test with, but I'll leave this open until I can get to it.

**Comment by webknjaz** [comment]
Ref #1557 #1534

**Comment by webknjaz** [comment]
The reason is probably #1747

**Comment by webknjaz** [comment]
Closing as irrelevant. We don't support Python 3.3 anymore and it's probably stable now.
