### ISSUE TITLE
max_request_header_size not used anywhere

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1182]
Originally reported by: **Anshul Goyal (Bitbucket: [goyal](http://bitbucket.org/goyal), GitHub: @goyal)**

---

I am trying to send a HTTP request with header size greater than 512KB to ensure that I will receive HTTP-413. As per my readings, cherrypy will return 413 when the received header size is greater than the value defined in max_request_header_size or when the request body size exceeds the value defined in max_request_body_size.

After reading the code and trying the following, I see that the default header size is set to 500Kb.

```
#!python
import cherrypy
print cherrypy.server.max_request_header_size

result: 512000
```

However, I didn't see anywhere in the code where this variable (max_request_header_size) is actually used. After browsing the code, I realize that it only verifies max_request_body_size against the 'content-length' header property.

https://bitbucket.org/cherrypy/cherrypy/src/55be1e7c6dd37ffbf326fdf83ea94cf0565cbdc7/cherrypy/wsgiserver/wsgiserver2.py?at=default#cl-710

It appears to be a bug in cherrypy. Can you please confirm?

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1182

**Comment by webknjaz** [comment]
It's used on the Cheroot side: https://github.com/cherrypy/cheroot/blob/764461633ef6d6c1d8cece0617a264f66b279942/cheroot/server.py#L699
