### ISSUE TITLE
cherrypy 3.2.3 (zip, tar.gz and win32.exe) not accessible from cherrypy.org

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1203]
Originally reported by: **Nabil BEN YOUSSEF (Bitbucket: [nabilbenyoussef](http://bitbucket.org/nabilbenyoussef), GitHub: Unknown)**

----------------------------------------

Hi !

Can you :
- upload the version 3.2.3 (zip, tar.gz and win32.exe) here : http://download.cherrypy.org/cherrypy/3.2.3/ ?
- update the download link in the homepage ?

Thanks a lot

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1203

**Comment by webknjaz** [comment]
This subdomain is no longer supported, closing.
