### ISSUE TITLE
HeaderMap (CaseInsensitiveDict) __init__ missing

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1231]
Originally reported by: **space one (Bitbucket: [spaceone](http://bitbucket.org/spaceone), GitHub: [spaceone](http://github.com/spaceone))**

---

missing **`__init__`**:

```python
def __init__(self, *args, **kwargs):
    d = dict(*args, **kwargs)
    for key, value in iteritems(d):
        dict.__setitem__(self, str(key).title(), value)
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1231

**Comment by rozuur** [comment]
Have added above missing init accordingly.
