### ISSUE TITLE
Consolidate the CherryPy downloads on PyPi

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1232]
Originally reported by: **Joel  Rivera  (Bitbucket: [cyraxjoe](http://bitbucket.org/cyraxjoe), GitHub: [cyraxjoe](http://github.com/cyraxjoe))**

----------------------------------------

Currently the packages for cherrypy are hosted in  [pypi](https://pypi.python.org/pypi/CherryPy/3.2.3), http://download.cherrypy.org/ and [bitbucket](https://bitbucket.org/cherrypy/cherrypy/downloads).

It will be clearer for the documentation and facilitate the releases to just host the package on pypi.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1232

**Comment by webknjaz** [comment]
download.cherrypy.org is returning 403 currently
@jaraco I think this issue should be closed. Alternatively someone should set up redirect to pypi from URL above

**Comment by jaraco** [comment]
Happy to close.
