### ISSUE TITLE
issue when POSTing a serialized JSON

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1264]
Originally reported by: **Anonymous**

---

Hello,

I'm running CherryPy 3.3 + Python 3.3.
I have an application where I'm POSTing a serialized <form> as a JSON string:

This is my code on client side:

```
#!javascript

    AA.Form.prototype.save = function(p) {
        var _self = this;

        window.console.log(typeof(p.data));
        window.console.log(p.data);

        Yeti.AjaxRequest(p.url, {
            method: 'post',
            accept: 'json',
            data: p.data,
            onreadystatechange: function(req) {
                if (req.success()) {
                    _self.dispatcher.fire('after_save_success',
                                          req.get_response())
                } else if (req.error()) {
                    _self.dispatcher.fire('after_save_error');
                }
            }
        });
    }

```

The two window.console.log(...) output:

string
{"props":{"name":"Alien Alert Protocol","description":"Welcome to the improved ISEIA protocol: the \"Alien Alert\" protocol."},"fields":[{"required":true,"label":"Q1. Provide the name(s) of the assessor(s):","name":"field_0","id":"field_0","disabled":true,"factory":"StringField","help":"Provide a (the) name(s) for the person(s) performing the assessment."},{"required":true,"label":"Q2. Click here if you wish to add additional information.","name":"field_1","id":"field_1","disabled":true,"factory":"StringField","help":"Additional information may include your organisation, your motivation for performing this assessment; or anything else."}]}
                       ^^^^^
Please notice the ';' in the string at the end, this is where the problem occurs.

so the object is correctly serialized.

On server side I have:

```
#!python

    @cherrypy.expose()
    @cherrypy.tools.allow(methods=['POST'])
    @cherrypy.tools.json_out()
    def save(self, **kwargs):
        dir = cherrypy.request.config['file_storage_path']

        if 'key' not in kwargs:
            loop = 1
            while True:
                fn = binascii.hexlify(os.urandom(3)).decode()
                if not os.path.exists(os.path.join(dir, fn)):
                    break
                else:
                    loop += 1
                    if loop > 1000:
                        raise cherrypy.HTTPError('Cannot generate file')
        else:
            try:
                fn = int(kwargs['key'], 16) # hex -> int
            except ValueError:
                raise cherrypy.HTTPError('Invalid form id')

        cherrypy.log(str(kwargs))

        with open(os.path.join(dir, fn), 'w') as f:
            json.dump(kwargs, f, ensure_ascii=False)

        return {'key' : fn}

```

the cherrypy.log(...) output is :

[23/Aug/2013:13:41:03]  {' or anything else."}]}': '', '{"props":{"name":"Alien Alert Protocol","description":"Welcome to the improved ISEIA protocol: the \"Alien Alert\" protocol."},"fields":[{"required":true,"label":"Q1. Provide the name(s) of the assessor(s):","name":"field_0","id":"field_0","disabled":true,"factory":"StringField","help":"Provide a (the) name(s) for the person(s) performing the assessment."},{"required":true,"label":"Q2. Click here if you wish to add additional information.","name":"field_1","id":"field_1","disabled":true,"factory":"StringField","help":"Additional information may include your organisation, your motivation for performing this assessment': ''}

as you can see there is a problem with the ';' :

{' or anything else."}]}': '' which is invalid ...

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1264

**Comment by webknjaz** [comment]
This should be issue with json library, nothing we can fix.
