### ISSUE TITLE
Drop support for Python 2.3 and Python 2.4

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1270]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

----------------------------------------

While we laud the efforts of our maintainers for keeping support for Python 2.3 (while simultaneously supporting Python 3), it's time to drop support for versions prior to Python 2.5. There are pending contributions out there that are hampered if not outright prevented from improving CherryPy due to the lack of features (the 'with' statement being one of the most prominent). Supporting only Python 2.5+ still gives many years of backward compatibility while raising the bar.

Any objections?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1270

**Comment by webknjaz** [comment]
@jaraco what are the supported versions now?

Documentation still promises users support of versions 2.3-3.4, while `setup.py` defines the support of 2.6-3.5.
I've been examining imports in scope of #1480 and found out that there are still some crutches for supporting <2.6 (like this https://github.com/cherrypy/cherrypy/blob/d3c9807ba42c9b60fa077257e008caae42c3aeb0/cherrypy/lib/reprconf.py#L27-L30)

**Comment by webknjaz** [comment]
@jaraco ping

**Comment by jaraco** [comment]
Definitely dropped support for Python 2.5 and earlier in CP 4.0.0. The docs need to be updated and logic to support those older versions can be replaced with simpler native constructs. But this ticket is complete.
