### ISSUE TITLE
SSL Configuraiton

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1275]
Originally reported by: **mauch (Bitbucket: [mauch](http://bitbucket.org/mauch), GitHub: [mauch](http://github.com/mauch))**

---

Hi,

it would be very cool to configure more details for the SSL Connection.
- TLS Compression
- Cipher Suite
  ...

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1275

**Comment by WXITWangPeng** [comment]
Totally agree with you!!
I have submit a solution to add attribute "ssl_ciphers", after that, "Cipher Suite" configuration will be realized.

**Comment by webknjaz** [comment]
Ref: #1524

**Comment by webknjaz** [comment]
It looks like that PR is already incorporated in Cheroot.
