### ISSUE TITLE
Autoreloader throws "dictionary changed size during iteration" (python3)

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1280]
Originally reported by: **Anonymous**

---

Using cherrypy 3.2.4 in python3, every now and then, I get a traceback ending in:

```
File "/usr/lib/python3.3/site-packages/cherrypy/process/plugins.py", line 593,
 in sysfiles for k, m in sys.modules.items():
 RuntimeError: dictionary changed size during iteration".
```

fumanchu has already diagnosed the problem on irc.oftc.net#cherrypy:

> in Python 3, .items() now acts like .iteritems() did in Python 2; 
> that is, it is no longer "atomic". That code should be changed to 
> "for k, m in list(sys.modules.items())" to make the 
> (non-critical, transient) problem go away.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1280

**Comment by wyaadarsh** [comment]
Suddenly Cropped up in Python 3.7 on latest version cherrypy

**Comment by cyraxjoe** [comment]
@wyaadarsh This is not the same issue as the one currently present in cheroot https://github.com/cherrypy/cheroot/pull/313, the new one was caused by a refactor (intending an optimization and better use of the `selectors` module)  in the way that cheroot handles the connections.

**Comment by webknjaz** [comment]
@wyaadarsh Joel is right. Adding `cheroot != 8.4.4` to your requirements is a short-term workaround until this gets fixed.
