### ISSUE TITLE
Cherrypy logger doesn't escape special characters

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1282]
Originally reported by: **Will Dormann (Bitbucket: [wdormann](http://bitbucket.org/wdormann), GitHub: [wdormann](http://github.com/wdormann))**

---

```
#!python

>>> import cherrypy
>>> newline = 'Line1\nLine2'
>>> 
>>> cherrypy.log(newline)
08/Jan/2014:11:45:05  INFO Line1
Line2
>>> 


```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1282

**Comment by webknjaz** [comment]
Looks like this is solved with a paragraph in documentation
