### ISSUE TITLE
problems with cx_freeze on python3

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1283]
Originally reported by: **Radek Podgorny (Bitbucket: [rpodgorny](http://bitbucket.org/rpodgorny), GitHub: [rpodgorny](http://github.com/rpodgorny))**

---

when trying to run a program packaged by cx_freeze, an exception is thrown:

(sorry about the formatting - taken from stupid windows console)

```
#!python

[16/Jan/2014:12:42:18] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "c:\python33\lib\site-packages\cherrypy\process\wspbus.py", line 235, in
start
    self.publish('start')
  File "c:\python33\lib\site-packages\cherrypy\process\wspbus.py", line 215, in
publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: ImportError('cannot import name wsgiser
ver',)

the problem seems to be on line 14 in cherrypy/wsgiserver/__init__.py:

exec('from .wsgiserver3 import *')

```

when changed to plain import (without the exec), everything works as expected. i have no idea why the exec is even there but at least for cx_freeze this seems to cause problems (no problems when run directly using python).

system: windows xp 32bit
python: 3.3.3 32bit
cherrypy: 3.2.4

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1283

**Comment by webknjaz** [comment]
This is out-of-date and exec is missing from the codebase.
