### ISSUE TITLE
n must be a native str (got unicode)

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1285]
Originally reported by: **eXtink (Bitbucket: [eXtink](http://bitbucket.org/eXtink), GitHub: Unknown)**

---

When using the following code for redirecting

```
#!python

def index(self):
    raise cherrypy.HTTPRedirect("home")
index.exposed=True
```

The following error appears when accessing localhost:port

```
#!

Traceback (most recent call last):
  File "C:\Users\Bob\Programming\Hoarder\cherrypy\_cprequest.py", line 664, in respond
    inst.set_response()
  File "C:\Users\Bob\Programming\Hoarder\cherrypy\_cperror.py", line 250, in set_response
    response.body = ntob("<br />\n".join(msgs), 'utf-8')
  File "C:\Users\Bob\Programming\Hoarder\cherrypy\_cpcompat.py", line 58, in ntob
    assert_native(n)
  File "C:\Users\Bob\Programming\Hoarder\cherrypy\_cpcompat.py", line 96, in assert_native
    raise TypeError("n must be a native str (got %s)" % type(n).__name__)
TypeError: n must be a native str (got unicode)
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1285

**Comment by jaraco** [comment]
As tests are failing, I've moved those commits into the [bb-pr-85 branch](https://github.com/cherrypy/cherrypy/tree/bb-pr-85).

**Comment by binary1230** [comment]
hey @EliAndrewC, just tagging you in this since i noticed we're still employing the workaround in https://github.com/magfest/sideboard/blob/27c52f497034e7077b743c05d9029a287c01668e/setup.py#L18

**Comment by EliAndrewC** [comment]
Yeah, we're pinning an older version of CherryPy for Python 2 to get around this problem.

Eventually I'm hoping we'll just be on Python 3 everywhere and then not having to worry about this, but that's probably a few years away.  (At least MAGFest is on Python 3.)

**Comment by jaraco** [comment]
I've deleted the branch and replaced it with [this archive/1285-always-bytes tag](/cherrypy/cherrypy/releases/tag/archive%2F1285-always-bytes). I merged it with master to help facilitate getting it working if someone wishes to do so.

But since Python 2.7 is largely deprecated, unless someone wishes to revive this effort, I'm closing this as won't fix.
