### ISSUE TITLE
3.2.5 wheel does not include wsgiserver2.py but the tarball does

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1295]
Originally reported by: **cdent (Bitbucket: [cdent](http://bitbucket.org/cdent), GitHub: [cdent](http://github.com/cdent))**

----------------------------------------

When installing CherryPy with modern pip, wsgiserver2.py is missing. Upon investigation I discovered (by download both by hand) that the .whl file doesn't have it, but the .tar.gz file does.

The `ssl_pyopenssl.py` from the same directory also appears to be missing from the wheel file.

Forcing pip to --no-use-wheel gets the desired results, but clearly there's some kind of packaging error going on?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1295

**Comment by jaraco** [comment]
This is essentially a duplicate of #1110.
