### ISSUE TITLE
'AttributeError: 'module' object has no attribute 'socket_errors_to_ignore' at cherrypy\wsgiserver\ssl_pyopenssl.py", line 75, in _safe_call'

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1296]
Originally reported by: **Anonymous**

----------------------------------------

This is an old issue which allegedly was fixed once #1114/got-socket_errors_to_ignore-on-windows

However either the patch was not applied or it was altogether missing but the problem still present.
The fix is the same - add socket_errors_to_ignore to __all__ list in wsgiserver2.py
Here is the patch:
--- wsgiserver2.py.bak  2014-02-27 23:46:32.968887479 -0800
+++ wsgiserver2.py  2014-02-27 23:48:01.041324206 -0800
@@ -75,7 +75,7 @@
            'WorkerThread', 'ThreadPool', 'SSLAdapter',
            'CherryPyWSGIServer',
            'Gateway', 'WSGIGateway', 'WSGIGateway_10', 'WSGIGateway_u0',
-           'WSGIPathInfoDispatcher', 'get_ssl_adapter_class']
+           'WSGIPathInfoDispatcher', 'get_ssl_adapter_class', 'socket_errors_to_ignore']

 import os
 try:

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1296

**Comment by jaraco** [comment]
This should be fixed now that wsgiservers are unified.
