### ISSUE TITLE
Serving Static Content

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1305]
Originally reported by: **Dung Che Tan (Bitbucket: [ctandung13](http://bitbucket.org/ctandung13), GitHub: Unknown)**

---

I follow to set a static directory at
http://docs.cherrypy.org/en/latest/progguide/files/static.html

But when run: cherryd -i cpapp -c prod.conf. Report with error
...Value: 'cherrypy.Application(cpapp.Root()', config must be valid python

I think **init**.py was not called to load cpapp module?

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1305

**Comment by webknjaz** [comment]
Looks like the original author missed the `)` in their command
