### ISSUE TITLE
HTTP instead of HTTPS

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1322]
Originally reported by: **Anonymous**

---

Source: cherrypy/process/servers.py
Class: ServerAdapter
Routine: _get_base
Line: if getattr(self.httpserver, 'ssl_certificate', None):

self.httpserver doesn't appear to have ssl_certificate.

Switching the line to either of the following will work:
if getattr(self, 'ssl_certificate', None):
if getattr(self.httpserver.ssl_adapter, 'certificate', None):

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1322

**Comment by 500swapnil** [comment]
I would like to help fix this issue

**Comment by webknjaz** [comment]
Thanks, waiting for the PR then. Plz don't forget to add tests and make TravisCI build green :)

**Comment by jaraco** [comment]
This issue was addressed in c8f07984 and d1be8384. If there are ongoing issues with the implementation, please file a new report explaining under what conditions the current logic fails expectations.
