### ISSUE TITLE
Missing: cherrypy/wsgiserver/ssl_pyopenssl

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1323]
Originally reported by: **Anonymous**

----------------------------------------

CherryPy 3.2.6 (https://pypi.python.org/simple/CherryPy/CherryPy-3.2.6-py2.py3-none-any.whl) does not include the file **cherrypy/wsgiserver/ssl_pyopenssl.py**

To reproduce:

1. pip install cherrypy==3.2.6

2. python -c 'import cherrypy.wsgiserver.ssl_pyopenssl'

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1323

**Comment by jaraco** [comment]
Yep. It's a problem with wheels and the dimorphism of cherrypy on Py2/Py3. Perhaps now that the wsgiserver modules are unified, the ssl_pyopenssl can be unified also. Until then, your only option is to upgrade to Python 3 or not use the wheel.
