### ISSUE TITLE
URL with hyphen cannot run

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1324]
Originally reported by: **Anonymous**

----------------------------------------

Hello, I have a problem with cherrypy

@cherrypy.expose(alias='zh-cn')
def zh_cn(self, **params):
    return get_template('china.html').render(title = 'china dialect')

@cherrypy.expose(alias='zh-tw')
def zh_tw(self, **params):
    return get_template('taiwan.html').render(title = 'taiwan dialect')

@cherrypy.expose(alias='zh-sg')
def zh_sg(self, **params):
    return get_template('singapore.html').render(title = 'singapore dialect')

this does not work when I try go 
http://www.example.com/sayings/zh-sg

how to make it work?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1324

**Comment by nitincoded** [comment]
If anyone's still looking up this issue, the bug exists in the current release i.e. CherryPy 8.1.2.

The following is an example that uses an **underscore**, and **works perfectly**:

```
class BugCheck:
  @cherrypy.expose('hy_fen')
  def hyphen(self):
    cherrypy.response.headers['Content-Type'] = 'text/plain'
    return 'Hyphenated'
```

The following is an example that uses a **hyphen**, and **returns a 404**:

```
class BugCheck:
  @cherrypy.expose('hy-fen')
  def hyphen(self):
    cherrypy.response.headers['Content-Type'] = 'text/plain'
    return 'Hyphenated'
```

**Comment by nitincoded** [comment]
This issue is a duplicate of #1071

The resolution of the issue is to use "@cherrypy.expose('hy_fen')" and CherryPy would serve URLs in any of the following forms:
- /hy-fen
- /hy.fen
- /hy+fen
- /hy_fen
- /hy!fen
- /hy@fen

As this solution addresses the problem, this issue can be closed.

**Comment by jaraco** [comment]
Cool. Thanks for sharing.
