### ISSUE TITLE
Add jaraco as admin on cherrypy

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1326]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

----------------------------------------

The latest release script adds milestones and versions to the Bitbucket project, but requires admin privileges to do so. Can I have admin privileges on the repo in order to mechanize the creation of versions?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1326

**Comment by webknjaz** [comment]
This does look out-of-date
