### ISSUE TITLE
Python 27(64) Windows pip install misplaces tutorial.conf

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1327]
Originally reported by: **Jeff Anderson (Bitbucket: [jbanderson](http://bitbucket.org/jbanderson), GitHub: [jbanderson](http://github.com/jbanderson))**

----------------------------------------

Tutorial.conf is installed at C:\Python27\Lib\site-packages\PURELIB\cherrypy

Once copied into C:\Python27\Lib\site-packages\cherrypy\tutorial it makes it past the exception. 

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1327

**Comment by zephyrfalcon** [comment]
I had the same problem on Mac OS X 10.11.5, using a Homebrew installation of Python 3.5, and the latest version of CherryPy (5.4.0). Using the `--no-use-wheel` option mentioned above (although deprecated, apparently?) fixed the problem.

**Comment by webknjaz** [comment]
Invalid. CherryPy does not ship wheel anymore
