### ISSUE TITLE
"wsgiserver2" demanded by cherrypy.quickstart but only wsgiserver3 found

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1329]
Originally reported by: **Anonymous**

----------------------------------------

I tried a simple cherrypy.quickstart with cherrypy 3.5.0, but it complained that it could not find wsgiserver2.

I reinstalled 3.2 4 to fix my problem, and it was gone.

Sorry for not providing enough specifics.
I am on windows - new python and installing in global libraries, no virtualenv.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1329

**Comment by webknjaz** [comment]
CherryPy doesn't use wheels anymore.
