### ISSUE TITLE
Use portend for port checking/waiting

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1332]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

I've extracted and made more general purpose the port checking routines in cherrypy.process.servers in a new package called [portend](https://pypi.python.org/pypi/portend).

CherryPy should consider using that package.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1332

**Comment by webknjaz** [comment]
@jaraco to use it, first switch tests to run against all supported versions.
And there's a dependency for `tempora.timing`. Don't you think it's an overhead to depend on another package just to use a stopwatch?

**Comment by jaraco** [comment]
It is extra overhead, and yes, it's worth the overhead. After several years of accepting that 'copy/paste' is acceptable, I'm of the opinion that if someone is willing to maintain a library with suitable functionality that it's better to use that library than to create a fork of that functionality (by inlining it). The maintenance costs of subtly divergent implementations of essentially the same functionality are far greater than the costs of incorporating dependencies.

**Comment by webknjaz** [comment]
Okay, I agree with that
