### ISSUE TITLE
Accessing Cherrypy wsgi in application

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1337]
Originally reported by: **Anonymous**

---

Is it possible to access the stats in cherrypy's wsgiserver (cherrypy.wsgiserver.CherryPyWSGIServer.stats['xxxx']) and log them in my application?  I 'm getting the lambda function result when I do but I am likely not understanding how the lambda works in the context of the stats.

Also, how does one determine the client's ip address that accessed the wsgi server?
server.ConnectionClass.remote_addr <-- returned None
server.gateway.env['REMOTE_ADDR']

```
#!python
    from cherrypy import wsgiserver

    server = wsgiserver.CherryPyWSGIServer((WEB_SERVICES_SERVER_ADDRESS, WEB_SERVICES_SERVER_PORT),
                                           application, server_name=base_url_name)

    server.stats['Enabled'] = True
    server.start()


        logger.info("[CherryPy Stats] Queue: %s, Threads: %s, Threads Idle: %s, Socket Errors: %s, "
                    "Accepts: %s, Requests: %s",
                    server.stats['Queue'], server.stats['Threads'], server.stats['Threads Idle'],
                    server.stats['Socket Errors'], server.stats['Accepts'], server.stats['Requests'])

```

Output of logger:

[CherryPy Stats] Queue: <function <lambda> at 0x2424a28>, Threads: <function <lambda> at 0x2424aa0>, Threads Idle: <function <lambda> at 0x2424b18>, Socket Errors: 0, Accepts: 2, Requests: <function <lambda> at 0x2424b90>

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1337

**Comment by webknjaz** [comment]
This should probably go to cheroot repo

**Comment by jaraco** [comment]
Indeed, this was a question that went unanswered. I suspect no one had the time to investigate and write up an answer. The short answer is we don't know and one will have to dig into the code to find the answer.
