### ISSUE TITLE
Consider deprecating one of two tools

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1338]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

----------------------------------------

In Pull Request #42, Sylvain suggests deprecating one of two tools. Clarify which tools and explore that possibility.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1338

**Comment by webknjaz** [comment]
@jaraco I think this is out-of-date. Closing

**Comment by jaraco** [comment]
Fine by me. @Lawouach feel free to revive this effort as time permits.
