### ISSUE TITLE
Tools and decorators break automatic documentation generation

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1348]
Originally reported by: **Gerwin van de Steeg (Bitbucket: [gerwinvandesteeg](http://bitbucket.org/gerwinvandesteeg), GitHub: Unknown)**

----------------------------------------

Since CherryPy is used frequently to build APIs, and these same people would like to use automatic documentation generation for their applications using tools such as Sphinx. The currently in place implementation of the tools/toolbox and even the basic expose method of cherrypy when used as a decorator break this functionality completely.

We would need to add in a means to preserve:
- __name__
- __doc__
- method/function arguments

With those, automatic documentation generation should start to work again.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1348

**Comment by jaraco** [comment]
> even the basic expose method of cherrypy when used as a decorator break this functionality completely

The expose decorator is not affected:

```
> $ cat test-expose.py
import inspect

import cherrypy


@cherrypy.expose
def foo(self, other):
    "Docs"

print(foo.__name__)
print(foo.__doc__)
sig = inspect.signature(foo)
print(sig)
$ python test-expose.py
foo
Docs
(self, other)
```

**Comment by jaraco** [comment]
Similarly, `cherrypy._cpconfig.Config.__call__` returns the original function and not a wrapper:

```
$ cat test-config.py
import inspect

import cherrypy


def bar(): pass


@cherrypy.config(**{'foo': bar})
def foo(self, other):
    "Docs"


print(foo.__name__)
print(foo.__doc__)
sig = inspect.signature(foo)
print(sig)
$ python test-config.py 
foo
Docs
(self, other)
```

Therefore, I'm marking this issue as invalid. Feel free to open a new ticket about a specific tool or decorator (or set thereof) that masks the function/method signature.
