### ISSUE TITLE
SignalHandler.handlers dict ignored in SignalHandler.__init__()

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1358]
Originally reported by: **dketov (Bitbucket: [dketov](http://bitbucket.org/dketov), GitHub: [dketov](http://github.com/dketov))**

----------------------------------------

http://docs.cherrypy.org/en/latest/pkg/cherrypy.process.html?highlight=signalhandler#cherrypy.process.plugins.SignalHandler says 'You can modify what signals your application listens for, and what it does when it receives signals, by modifying SignalHandler.handlers, a dict of {signal name: callback} pairs' but it is completely replaced by

    75      def __init__(self, bus):
    76          self.bus = bus
    77          # Set default handlers
    78          self.handlers = {'SIGTERM': self.bus.exit,
    79                           'SIGHUP': self.handle_SIGHUP,
    80                           'SIGUSR1': self.bus.graceful,
    81                           }

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1358

**Comment by webknjaz** [comment]
You just need to unsubscribe, modify handlers and subscribe again
