### ISSUE TITLE
reloading 'cherrypy' after reloading 'logging' causes exception

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1363]
Originally reported by: **ferguzz (Bitbucket: [ferguzz](http://bitbucket.org/ferguzz), GitHub: [ferguzz](http://github.com/ferguzz))**

----------------------------------------

To reproduce:

    import logging
    import cherrypy

    reload(logging)
    reload(cherrypy)

Output:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/tom.myers/AppDynamics/codebase/agent/python/env/lib/python2.7/site-packages/cherrypy/__init__.py", line 337, in <module>
        log = _GlobalLogManager()
      File "/Users/tom.myers/AppDynamics/codebase/agent/python/env/lib/python2.7/site-packages/cherrypy/_cplogging.py", line 186, in __init__
        self.error_log.addHandler(NullHandler())
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 669, in __init__
    Filterer.__init__(self)
    TypeError: unbound method __init__() must be called with Filterer instance as first argument (got NullHandler instance instead)

This can be avoided be reloading 'cherrypy._cplogging' before reloading 'cherrypy'.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1363

**Comment by webknjaz** [comment]
@jaraco should we do anything about this?

**Comment by jaraco** [comment]
Perhaps not. I can't see how any package can in general support the arbitrary reloading of select modules from itself and the modules on which it depends. If there were a routine in CherryPy doing this reloading, then that routine would need to be responsible for ensuring the ordering of the reloading produced a consistent result. I don't think there's anything CherryPy can do to support this use case.

I invite suggestions or a revived discussion, but in the meantime, let's close it.
