### ISSUE TITLE
Documentation on index method contradicts itself

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1364]
Originally reported by: **glennwikle (Bitbucket: [glennwikle](http://bitbucket.org/glennwikle), GitHub: Unknown)**

----------------------------------------

On this page: https://cherrypy.readthedocs.org/en/3.2.6/concepts/dispatching.html

In the Index Methods section it says, "*unlike all other page handlers, [the index method] cannot take positional arguments*"

Then later in the Positional Arguments section it gives an example of an index method with positional arguments:

  *For example, the URI "/branch/leaf/4" might result in the call: app.root.branch.leaf(4), or app.root.index(branch, leaf, 4) depending on how you have your handlers arranged.*

I also think there are quotes missing around branch and leaf so that part should read *app.root.index('branch', 'leaf', 4)*

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1364

**Comment by jaraco** [comment]
I believe this ticket is no longer valid. Searching the code base, not 'positional arguments' nor 'Positional Arguments' do appear in the docs, and there's no such file for 'dispatching'.
