### ISSUE TITLE
CherryPy SimpleCookie renders with \r

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1369]
Originally reported by: **Anonymous**

----------------------------------------

I came across this incipient bug while debugging an old CP app that was being upgraded _to_ CP 2.3 (if you can believe that)

The app had never run in mod_wsgi before, so I thought that would be fun to try... oops.  I was left with this awful newline bug because mod_wsgi was not accepting the \r that was being left behind when the Cookie headers were being rendered.   (there was a split '\n' in the code). In any event, please see my pull request for the solution.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1369

**Comment by webknjaz** [comment]
CherryPy doesn't support such ancient Python's anymore.
