### ISSUE TITLE
Custom domain going away

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1371]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

----------------------------------------

Bitbucket is removing custom domains. I got this message when pushing to bitbucket:

```
remote: *******************************************************************
remote:    Bitbucket is disabling custom domains (CNAMEs) on 2015-07-01.
remote: 
remote:    The account that owns this repository has a CNAME configured.
remote:    Please update your scripts and your team to use the bitbucket.org URL:
remote:    https://bitbucket.org/cherrypy/cherrypy
remote: 
remote:    For more information: https://confluence.atlassian.com/x/Eg4zDQ
remote: *******************************************************************
```

Let's disable the custom domain. Are there any sites that refer to it?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1371

**Comment by jaraco** [comment]
Time moves on.
