### ISSUE TITLE
tut06.py

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1375]
Originally reported by: **Lasha Kitia (Bitbucket: [lasha_kitia](http://bitbucket.org/lasha_kitia), GitHub: Unknown)**

---

its './static' and not './public'

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1375

**Comment by AlexHoff1** [comment]
There was a clarification note at the end of tutorial 6 that explained the /public /static situation.
