### ISSUE TITLE
Installed in Python3 cherryd has hashbang "#!c:\python\python.exe"

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1379]
Originally reported by: **saaj (Bitbucket: [saaj](http://bitbucket.org/saaj), GitHub: [saaj](http://github.com/saaj))**

----------------------------------------

Initially I though it is a regression since 387f661. But the same thing happens in 3.6 as well. Here's docker file to verify. It doesn't matter whether it's installed globally or into a virtualenv.

```
#!bash

FROM ubuntu:trusty

MAINTAINER CherryPy QA Team

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get --no-install-recommends -qy install python3 python3-pip

RUN pip3 install CherryPy

CMD bash -c "cat `whereis cherryd | grep -o '/.*'` && ls -l `whereis cherryd | grep -o '/.*'`"
```

Then 

```
#!bash

docker build -t cherrypy/py3bug .
docker run --rm -it cherrypy/py3bug
```

For 3.8 the output is:

```
#!bash

#!c:\python\python.exe

import cherrypy.daemon

if __name__ == '__main__':
    cherrypy.daemon.run()
-rw-r--r-- 1 root root 101 Aug  2 16:38 /usr/local/bin/cherryd
```

Also you can see that it's not executable.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1379

**Comment by webknjaz** [comment]
Closing for the same reason as #1381
