### ISSUE TITLE
cherryd not found, pip thinks it is installing cherrypy>=3.6.0 onto windows?

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1381]
Originally reported by: **Blake Walsh (Bitbucket: [blake_walsh](http://bitbucket.org/blake_walsh), GitHub: Unknown)**

----------------------------------------

This is an issue which occurs in Cherrypy versions higher than 3.5.0

Environment:
The environment the problem is occurring under is: 

* OS: Ubuntu 15.04
* Virtual Environment: pyenv with pyenv-virtualenv
* Python version: python3.4/3.5
* CherryPy versions: 3.6.0, 3.7.0, 3.8.0
* Installed using: `pip install cherrypy==3.8.0`

Attempting to run cherryd results in the message:
`pyenv: cherryd: command not found`

Please note: *This same setup works perfectly with cherrypy<=3.5.0, the problem first occured when I did a `pip install --upgrade cherrypy`, but I can easily reproduce the problem in a fresh pyenv environment*

## Analysis of problem and manual fix

A file `cherryd` is created along with other executable scripts under `.../<env>/bin`, it is put in the same place as `pip` and `easy_install` and all other scripts, all of these other scripts work fine, so far so good. However `cherryd` is not set to be executable, and more horribly for an Ubuntu environment the file starts with:

`#!c:\python\python.exe`

The hashbang for all other scripts under the `<env>/bin` folder is sensible for the environment and do not make any outrageously incorrect assumptions about the environment (Note that pip install also installs components under `.../site-packages/PURELIB/cherrypy`)

If I manually replace the hashbang with the hashbang from the other scripts, and manually set the executable flag, then I can run `cherryd` just as with 3.5.0, with this manual fix it works fine.

## Also
These problems do not occur if I download Cherrypy-3.8.0.tar.gz and install it into the env using `python setup.py install`. It occurs when using `pip install cherrypy` or installing manually from the whl - note that the version of pip does not matter as the same problem occurred with every version of pip I tested.

---

The problem seems to be that pip is installing a whl package for a windows environment, but this only creates a problem with cherryd since cherrypy is pure python enough for the package to (otherwise) work on Linux too.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1381

**Comment by webknjaz** [comment]
This issue is invalid for now since (1) win wheels ain't deployed anymore (#1393) and (2) it works for current latest version in my pyenv.
Also, one may avoid using wheel by adding `--no-use-wheel` or `--no-binary` (depending on pip version)
Closing.
