### ISSUE TITLE
HTTP2?

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1388]
Originally reported by: **Red_M (Bitbucket: [Red_M](http://bitbucket.org/Red_M), GitHub: Unknown)**

----------------------------------------

Is there going to ever be hope that Cherrypy will implement  HTTP2 for the built in HTTP server?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1388

**Comment by nitincoded** [comment]
There was a dream of building this way back in 2013 with #1276 , so one of the two can be marked as a duplicate.

The quickest way to close an enhancement issue is to mark it as a duplicate 😄
