### ISSUE TITLE
Tutorial 5: Track my end-user’s activity

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1390]
Originally reported by: **Andrés Zamora (Bitbucket: [andreszamora](http://bitbucket.org/andreszamora), GitHub: [andreszamora](http://github.com/andreszamora))**

---

In http://docs.cherrypy.org/en/latest/tutorials.html#id7
cherrypy.session.get('mystring') instead of cherrypy.session['mystring']

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1390

**Comment by webknjaz** [comment]
@jaraco should this even be changed?

**Comment by AlexHoff1** [comment]
Explored the subtle differences between these calls, and decided that the silent None returned by the .get would be more confusing.
