### ISSUE TITLE
We need to stop the delivery of pre-built packages

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1393]
Originally reported by: **Sylvain Hellegouarch (Bitbucket: [Lawouach](http://bitbucket.org/Lawouach), GitHub: [Lawouach](http://github.com/Lawouach))**

---

Hi guys,

The latest release of 3.8.1 had a bit of problem. A wheel and a Windows installer were uploaded. 

Once installed via the Windows installer, the cherryd script contained the following shebang:
# !/Users/picong/.virtualenv/cp27/bin/python

This is obviously not what the maintained intended I believe. Unfortunately, it breaks deployment in some cases.

Note also the name of the installer:

```
CherryPy-3.8.1.macosx-10.10-x86_64.exe
```

Confusing I think ;)

So, for now, I'm going to remove the installer and the wheel from Pypi. I don't see why we need any of those as we're a pure library anyhow.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1393

**Comment by webknjaz** [comment]
AFAIK this is not relevant anymore.
