### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'accept'

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1395]
Originally reported by: **Anonymous**

---

We are using CherryPy 3.8.0. We have found following tracaback from cherryPy:

>   ERR 2015-12-07 00:05:56,453 cherrypy.error 19493 'HTTPServer Thread-6' : [07/Dec/2015:00:05:56] ENGINE Error in HTTPServer.tick
>   Traceback (most recent call last):
>     File "/xxx/venv/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1968, in start
>     File "/xxx/venv/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2020, in tick
>   AttributeError: 'NoneType' object has no attribute 'accept'
>    [_cplogging.py:216] [base.py:521]
> From brief code inspection it looks like a race condition when stopping the server.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1395

**Comment by AlexHoff1** [comment]
If this is still an issue file a ticket in cheroot, since wsgiserver has been moved to that project.
