### ISSUE TITLE
Main navigation missing a link to CherryPy Package page

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1396]
Originally reported by: **John Grant (Bitbucket: [j_grant](http://bitbucket.org/j_grant), GitHub: Unknown)**

---

In the CherryPy docs - http://docs.cherrypy.org/ - the left hand navigation is missing a link to the **all important Package page** - http://docs.cherrypy.org/en/stable/pkg/cherrypy.html

The only way to find it is to search for 'package', see attachment.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1396

**Comment by webknjaz** [comment]
Already done
