### ISSUE TITLE
Fix JSX parsing error in tutorial 10

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1398]
Originally reported by: **Anonymous**

----------------------------------------

Please merge pull request 115 to fix this.  It took me a long time to figure out why the code in tutorial 10 would not work.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1398

**Comment by nicklasb** [comment]
The PR was merged, closing:
https://bitbucket.org/cherrypy/cherrypy/pull-requests/115/add-babel-browser-script-to-html-code-in/diff
