### ISSUE TITLE
AttributeError: 'listiterator' object has no attribute 'next'

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1408]
Originally reported by: **Anonymous**

----------------------------------------

While stopping service cherrypy logged error:
```
ERR 2016-03-12 20:48:32,460 cherrypy.error.140129365106640 11286 'CP Server Thread-7' : [12/Mar/2016:20:48:32]  Traceback (most recent call last):
  File "site-packages/cherrypy/_cpwsgi.py", line 180, in trap
  File "site-packages/cherrypy/_cpwsgi.py", line 277, in next
AttributeError: 'listiterator' object has no attribute 'next'
 [_cplogging.py:216]
```

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1408

**Comment by jaraco** [comment]
I'm surprised that this would happen - it seems by my reading of the code that attribute .next is only accessed on Python 2, and even on Python 2.7.10, a listiterator does have the next attribute. Still, now that Python 2.6 is required, this issue should be straightforward to fix.

**Comment by capitalterefe** [comment]
use `__next__()` instead if you are on Python 3
