### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1410]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

----------------------------------------

In order to be more visible and friendly to more contributors, CherryPy should consider moving to Github.

Github is the canonical and preferred hosting for most open source projects.

I'm willing to help with the process, but I first want to get the nod from @cyraxjoe and @Lawouach. Also, we'll need to create a CherryPy org (if there's not a better one to host it).

I propose migrating the existing issues to Github using https://github.com/jeffwidman/bitbucket-issue-migration or one of its many forks. I'm happy to test and execute that.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1410

**Comment by jaraco** [comment]
The migration is complete. CherryPy can now be found at https://github.com/cherrypy/cherrypy. I'll be doing some additional cleanup work like:

- hide issues in bitbucket
- update readme and other documentation to point at github
- cut a new release so the released version refers to github
- review and accept pull requests in bitbucket

**Comment by ngrilly** [comment]
@jaraco How did you manage to keep the same issue IDs in BitBucket and GitHub?

**Comment by jaraco** [comment]
@ngrilly - the [bitbucket_issue_migration project](https://github.com/jeffwidman/bitbucket-issue-migration) is designed to do that. It does it by first requiring that the target repo have no existing issues. It then creates new issues in github, inserting dummy issues if there are gaps in the bitbucket numbering, and then lets github assign the numbers, which usually align with the numbers from bitbucket.

**Comment by ngrilly** [comment]
@jaraco Thanks. Nice hack :-)
