### ISSUE TITLE
Autoreload can't handle module / __main__

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1411]
Originally reported by: **Anonymous**

----------------------------------------

I try to run `python -m mymodule` (and `mymodule/` contains `__main__.py`). The module then spawns a CherryPy server. Everything works until it tries to reload itself, where it tries to run `/path/to/python mymodule/__main__.py`, without importing `mymodule`. This makes my module to throw various `ImportError`s that claim `mymodule` cannot be found.

Could you share any tips how to organize the code, or change the way I run the server, to make reloading work?

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1411

**Comment by jaraco** [comment]
My guess is that the autoloading feature is simply not aware of the `-m` entry technique. I was not aware that `python -m foo` would implicitly import the package.

```
$ mkdir foo
$ cat > foo/__main__.py
print("Ran __main__")
import foo
$ python -m foo
Ran __main__
$ cat > foo/__init__.py
print("imported foo")
$ python -m foo
imported foo
Ran __main__
```

I'm pretty sure you can work around the issue by adding `import mymodule` in your `__main__`. Did you try that? If that doesn't work, what happens?

**Comment by sevmonster** [comment]
Didn't see that this had an issue already.

See #1436, both issues are caused by the same situation.
This bug has been around for a few years now.

**Comment by jaraco** [comment]
I suspect that the autoreloader functionality has never supported launching as `-m`, which I believe is the underlying issue here. To work around the issue, you probably need to avoid launching using `-m`.

If someone would like to devise a fix, I suspect using the `runpy` module, mentioned in [PEP 338](https://www.python.org/dev/peps/pep-0338/) might be way to do it.

**Comment by batterseapower** [comment]
Bit tricky to fix because of http://bugs.python.org/issue14208
