### ISSUE TITLE
Enable CI for the repo

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1412]
Originally reported by: **Sviatoslav Sydorenko (Bitbucket: [webknjaz](http://bitbucket.org/webknjaz), GitHub: [webknjaz](http://github.com/webknjaz))**

----------------------------------------

Make automatic tests run on cherrypy.

Here's CI I found recently https://codeship.com/, which works with bitbucket as well. And it's relatively easy to set it up.

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1412

**Comment by jaraco** [comment]
Following the move to Github, this is complete.
