### ISSUE TITLE
Move www.cherrypy.org to Github hosting.

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1421]
CherryPy maintains a web site at http://www.cherrypy.org, hosted by webfaction. Who maintains that site? How can one suggest updates to it?

**Comment by Lawouach** [comment]
The site source is on bitbucket: https://bitbucket.org/cherrypy/cherrypy.bitbucket.org

The site is hosted on Robert's account on webfaction. Some of us have an ssh account to access it. The whole update is rarher manual.

**Comment by jaraco** [comment]
I'm tempted to migrate that code into a 'site' or 'www' branch in this repository. Although... since it's a static site, we could move it to /cherrypy/cherrypy.github.io, and then it would be rendered at http://cherrypy.github.io, and we could add a CNAME to have it appear from www.cherrypy.org (with the right cname entry in the domain). I'm reluctant to give up webfaction hosting, given their history with the project. Still, I feel simplicity of management that github brings beats out respect for our legacy.

Thoughts on that move? Who maintains the DNS for cherrypy.org?

**Comment by Lawouach** [comment]
I think it's the right move to group everything on github.io. I don't believe Rémi will mind (I can ask him).

As for the domain, it might be trickier. He still owns it and I don't know if he'll be willing to let it go. I will ask.

**Comment by jaraco** [comment]
Repo migrated and the new site is present at http://cherrypy.github.io.

**Comment by Lawouach** [comment]
Okay, I've actually changed the DNS so it pointed it to cherrypy.github.io. This will resolve soon.

**Comment by Lawouach** [comment]
okay that wasn't that simple. I'll keep you posted.

**Comment by jaraco** [comment]
I see. The solution is to add a `CNAME` file containing only the hostname, in this case www.cherrypy.org.

**Comment by Lawouach** [comment]
The CNAME will prevent the emails from working properly it seems. An A record might be better.

I know it will not sound intuitive but, once we have set the A record in webfaction's panel for the domain, we will need to follow this:

https://help.github.com/articles/setting-up-your-pages-site-repository/

**Comment by jaraco** [comment]
I've set up these pages before. It's pretty straightforward - create the file and set the DNS.

> An A record might be better.

If you use an A record, you have to update the IP address(es) every time github updates theirs.
Ping me in Gitter if I can help.

**Comment by webknjaz** [comment]
@Lawouach you need to add `CNAME` file containing text `cherrypy.org` to https://github.com/cherrypy/cherrypy.github.io repo

And then set up two A records for `cherrypy.org` to point to `192.30.252.153` and `192.30.252.154`.

Doc: https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

P.S. CNAME entries should in no way affect email. The thing is you cannot set CNAME for your root domain, but you can set it for subdomains (like `www`). Thus the solution for `cherrypy.org` needs to be setting `A` record and additionally you may add CNAME `www` pointing to the domain itself (usually `@` wildcard)

**Comment by webknjaz** [comment]
@jaraco @Lawouach this issue is stuck for months. Is there any way to speed it up?

**Comment by Lawouach** [comment]
Looks like it's working now.

```
$ dig docs.cherrypy.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> docs.cherrypy.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20801
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1460
;; QUESTION SECTION:
;docs.cherrypy.org.		IN	A

;; ANSWER SECTION:
docs.cherrypy.org.	3532	IN	CNAME	cherrypy.github.io.
cherrypy.github.io.	3484	IN	CNAME	github.map.fastly.net.
github.map.fastly.net.	2340	IN	CNAME	prod.github.map.fastlylb.net.
prod.github.map.fastlylb.net. 16 IN	A	151.101.12.133

;; Query time: 18 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Thu Sep 29 10:34:19 CEST 2016
;; MSG SIZE  rcvd: 168
```

**Comment by Lawouach** [comment]
Going forward, you probably want to ping the owner of that domain so you can take ownership.

**Comment by Lawouach** [comment]
meh... wrong domain.

Again, I don't want to change the domain settings as I don't own it. Please consider approaching Rémi Delon instead.

**Comment by Lawouach** [comment]
Hopefully this time is right

```
$ dig cherrypy.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> cherrypy.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40335
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cherrypy.org.          IN  A

;; ANSWER SECTION:
cherrypy.org.       2108    IN  A   192.30.252.153
cherrypy.org.       2108    IN  A   192.30.252.154

;; Query time: 5 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Thu Sep 29 11:25:16 CEST 2016
;; MSG SIZE  rcvd: 62
```

DNS caching for a few hours maybe.

**Comment by webknjaz** [comment]
A records already point to github for me as well. MX records are left untouched, meaning that mail will still be processed by webfraction:

```
$ dig cherrypy.org any

; <<>> DiG 9.10.3 <<>> cherrypy.org any
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11116
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cherrypy.org.          IN  ANY

;; ANSWER SECTION:
cherrypy.org.       86310   IN  NS  ns3.webfaction.com.
cherrypy.org.       86310   IN  NS  ns4.webfaction.com.
cherrypy.org.       3510    IN  A   192.30.252.153
cherrypy.org.       3510    IN  A   192.30.252.154
cherrypy.org.       86310   IN  NS  ns1.webfaction.com.
cherrypy.org.       86310   IN  NS  ns2.webfaction.com.

;; Query time: 36 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Sep 29 13:28:24 EEST 2016
;; MSG SIZE  rcvd: 159
```

```
$ dig cherrypy.org mx

; <<>> DiG 9.10.3 <<>> cherrypy.org mx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53919
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;cherrypy.org.          IN  MX

;; ANSWER SECTION:
cherrypy.org.       3599    IN  MX  10 mx7.webfaction.com.
cherrypy.org.       3599    IN  MX  10 mx8.webfaction.com.
cherrypy.org.       3599    IN  MX  10 mx9.webfaction.com.

;; Query time: 54 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Sep 29 13:28:13 EEST 2016
;; MSG SIZE  rcvd: 115
```

**Comment by Lawouach** [comment]
Thanks. So we're good?

**Comment by webknjaz** [comment]
Yes, I think so.
