### ISSUE TITLE
Regression in client expectation with Location header

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1440]
In girder/girder#1362, they report that their test suite begins to fail with CherryPy 5.4.0 due to #1432. I'm thinking we need to revisit that change in light of that report.

When I approved that pull request, I was thinking that the value should have been encoded to bytes in order to fulfill a network request. On a second examination, I see that there are other values in the `cherrypy.response.headers` that aren't bytes (such as Content-Type, set just above).

I'm inclined now to back out the change, but I want to first give @poofeg a chance to revisit the change and suggest perhaps a better solution.

**Comment by poofeg** [comment]
I think it would be better solution to URL encode (percent-encoding) the redirect URL. It is suitable for all Python versions.
