### ISSUE TITLE
support multi backends for session (  redis，mysql etc)

### ISSUE THREAD

**Issue by derek0377** [cherrypy/cherrypy#1449]
Hi:
 would support multi backends for session (  redis，mysql etc) ?

Thanks~

**Comment by webknjaz** [comment]
Hi,

I'm not sure regarding mysql, but you may take a look at these snippets implementing redis session backend:
https://bitbucket.org/webknjaz/blueberrypy-wk/src/cb2753de29c4ec0f1be00baf2e828b35e0939b47/src/blueberrypy/session.py?at=default&fileviewer=file-view-default#session.py-33:91
https://bitbucket.org/webknjaz/blueberrypy-wk/src/cb2753de29c4ec0f1be00baf2e828b35e0939b47/src/blueberrypy/command.py?at=default&fileviewer=file-view-default#command.py-269:270

**Comment by derek0377** [comment]
@webknjaz , really thank you!

**Comment by webknjaz** [comment]
@jaraco do you think additional storage backends should be added to cherrypy's codebase?

**Comment by jaraco** [comment]
I don't think so. It's [trivially easy](https://github.com/jaraco/jaraco.mongodb/blob/master/jaraco/mongodb/sessions.py) for another library to implement a Session subclass and for users to require and configure that implementation. What I do think CherryPy should do is keep in the documentation references to all stable session implementations. I'd further say that if any one implementation becomes dominantly used, it may be considered for incorporation into the CherryPy codebase.
