### ISSUE TITLE
Information disclosure on bad requests

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1451]
Hi all!

I have discovered an information disclosure issue within the web server of cherrypy. By sending invalid characters in the URL it runs into an exception and returns the exception message (without stack trace) to the browser.

Trigger: Send something invalid in the URL, like: %zz (without URL encoding it)
Expected behaviour: Generic "Bad Request" response from the web server
Faulty behaviour present: Exception text like "invalid literal for int() with base 16: b'zz'" (without stack trace) is returned as a response.

![asdf](https://cloud.githubusercontent.com/assets/20280659/16558118/e58a0ed8-41e3-11e6-98ad-f05d548561ea.png)

with best regards!

**Comment by jaraco** [comment]
You're right. A 500 error here is inappropriate. The only question I have is what's the best response? What does the HTTP spec have to say about `%ZZ` where ZZ is not hex? My instinct agrees with yours that this should be a 400 bad request, but I can also imagine non-hex characters would simply be unmatched in the unquoting.

Looking at the `urllib.parse.unquote` behavior, it seems to only unquote valid hex digits:

```
>>> urllib.parse.unquote('%ab')
'�'
>>> urllib.parse.unquote('%42')
'B'
>>> urllib.parse.unquote('%zz')
'%zz'
```

This finding leads me to think that non-hex digits should not raise an error at all but should simple be unmatched in the unquoting.

**Comment by ghost** [comment]
Maybe my description was not clear enough. Cherrypy is currently already responding with 400 "Bad Request" (see screenshot), which is fine. It just shouldn't disclose error messages!

![1467709184](https://cloud.githubusercontent.com/assets/20280659/16579347/9c5b8432-429f-11e6-90ee-cf36b42a9640.png)

I assume 400 "Bad Request" is the correct response because of the following research results:

The RFC 3986 (https://www.ietf.org/rfc/rfc3986.txt) definitely mentions that a ‘%’ itself has to be encoded as ‘%25’ in order to avoid issues (last paragraph in chapter 2.4.). But it looks more like a conclusion than a definition…

Looking at the way other web servers (ngnix, apache, IIS) and large web sites (Amazon, Yandex, Microsoft) handle ‘%zz’, 400 “Bad Request” seems to be the norm:

https://www.google.de/%zz
https://www.amazon.de/277-6121422-8654062%zz
https://www.yandex.ru/%zz
https://httpd.apache.org/%zz
https://support.microsoft.com/%zz
http://180.250.108.149:9981/%zz (obviously an IIS)

with best regards!

**Comment by ghost** [comment]
I think the solution here is quite easy. In wsgiserver3.py you can find several calls to "self.simple_response()". Apparently it is called whenever something goes wrong and cannot be passed to the web application to be handled. Most of the time it is called correctly with the arguments "status" and a custom "message". But twice it happens that it is called with "status" and "ex.args[0]" as the message.

I believe that you should never ever take exception messages and send them back to the client. Attackers can make use of these direct responses and tailor their attacks. If the client is too stupid to send a proper request it should only receive "Bad Request" and no details as a response. 

In my code, I changed the two occurrences of **self.simple_response("400 Bad Request", ex.args[0])** to **self.simple_response("400 Bad Request", "400 - Bad Request")**

**Comment by ghost** [comment]
Here is a diff that I created after patching the issue locally (for cherrypy 6.0.2). It fixes this problem and the other one I posted. Apply it if you like it.

[patch.txt](https://github.com/cherrypy/cherrypy/files/348124/patch.txt)

**Comment by jaraco** [comment]
I'm disinclined to address this issue. In my opinion, the information disclosure is minimal, compared to other disclosure. Especially given that this is an open-source project, in which a given attacker has access to the full implementation, I don't think masking error messages to be obscure is of immense value, and definitely leads to a detriment when diagnosing issues. Furthermore, a high-security deployment would probably have other mechanisms to more uniformly mask error messages - either through a WSGI layer or a reverse-proxy or load balancer, which could readily mask all 400 errors.

I'd be open to a tool which if enabled would mask all errors. We might even consider enabling that tool by default in the 'production' environment. However, it feels inappropriate to mask useful error messages piecemeal at the source.

**Comment by ghost** [comment]
Well it is up to you, but here are some thoughts I have about it:
- Ideally an attackers should not know in the first place which web server is deployed, hence he can not browse the source code for issues.
- No need get into high-security high-end details (in such case I personally would choose a different web server anyways). Nevertheless security should be standard and information disclosure is simply not  a security best practice (a patch would be simple - as it is already done right in most spots. I actually would say it was just forgotten in the current situation)
- show my a single common web server (apache, ngnix, iis,...) that passes exception messages back to the browser (in a prod config).
- exception messages might be comfortable for development or debugging purposes but not in a production environment. Especially, since CherryPy is proud to run in production environments. 

Thank's for your time!
Best regards!
