### ISSUE TITLE
cherrpy -- 6.0.x - dependency of six.py

### ISSUE THREAD

**Issue by thezoggy** [cherrypy/cherrypy#1454]
upgraded from cherrpy 5.1.0 to 6.0.2 in our project, it appears that in the upgrade now users are expected to have the six.py module... -- no mention of this in your change logs --

This has caused our app to be broken unexpectedly for many nas users. 
Can you please add `six.py` (from https://pypi.python.org/pypi/six) in the /cherrypy/lib folder so this dependency is included?

**Comment by thezoggy** [comment]
breaking change: https://github.com/cherrypy/cherrypy/commit/86e928d458ca501a601ea1c7f25f8add2855c336

**Comment by jaraco** [comment]
This change was made intentionally. CherryPy now has a dependency on six, a third-party package. The suggestion to include six in the library is both unsuitable and undesirable. CherryPy would be better served to _require_ six and share it with other packages that rely on it.

My best recommendation is that when you install CherryPy in your project, you use a tool like pip or easy_install to install both CherryPy and its dependencies, as defined in the setup.py.

Vendoring these dependencies, as you suggest, would be difficult and ultimately intractable. You're right that the project could vendor six, but then it will run up against this challenge next time a dependency is added to the project.

I acknowledge that the changelog for the 6.0 release could have included more detail about this aspect of the change.

Do you have any issues with installing six in your target environments?

**Comment by Safihre** [comment]
Well, we (sabnzbd) make some small changes (related to an extra feature and 2 bugs)  to Cherrypy and include it with the package. Before this was easy: Cherrypy did not have any dependencies. Now it does. 

Technically it should be oke for the NAS systems to update their packages, but we were just caught by surprise after releasing a beta version of our next release. Since on Windows/OSX six is usually installed.

**Comment by thezoggy** [comment]
we dont install cherrypy in the project.. we include it. thus not knowing of the dependency hurt when we deployed

we cant have others install it due to the amount of bugs we find/patch..  thus we have to include it (patched version).

**Comment by thezoggy** [comment]
we included six.py ourselves, but still you should prob note the dependency in your requirements for 6.x+

**Comment by jaraco** [comment]
Good suggestion. It is done.
