### ISSUE TITLE
Missing `nose` dependency when testing

### ISSUE THREAD

**Issue by endemic** [cherrypy/cherrypy#1457]
After installing CherryPy 6.1.1 and pytest 2.9.2 into a fresh Python 3.5.1 venv, I copy/pasted the [testing example](http://docs.cherrypy.org/en/latest/advanced.html#testing-your-application), attempted to run it (`py.test -s test_echo_app.py`), and saw the following:

``` bash
test.py:2: in <module>
    from cherrypy.test import helper
venv/lib/python3.5/site-packages/cherrypy/test/helper.py:29: in <module>
    import nose
E   ImportError: No module named 'nose'
```

`pip install nose` fixed the problem, but my assumption was that installing CherryPy would also install all its dependencies.

**Comment by jaraco** [comment]
Nose is a test requirement, not an install requirement. Perhaps there's a way to declare that. I'm not sure how with nose.

**Comment by webknjaz** [comment]
@jaraco it could be added as `tests_require` into `setup.py`

**Comment by webknjaz** [comment]
I'll PR dependency declaration, which aims to invoke `tox` for running all tests.

**Comment by webknjaz** [comment]
#1459
