### ISSUE TITLE
Use pytest framework for tests

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1463]
CherryPy currently relies on the nose framework for running tests. I suspect it has mostly small reliance on the specifics of nose, so it should be a fairly straightforward change to support using pytest as the runner.

There are many reasons the project should switch to pytest over nose:
- Pytest has better failure reporting, including assert rewrites. With pytest, if something fails, it reports the traceback, and the variables in the scope, and what values were present that failed an assertion.
- Pytest has assert rewrites - so that simple asserts can be easily assessed.
- Pytest does nice diffs of lists and dicts, masking the common elements and quickly getting to the differences that caused the failure.
- Pytest has nicer semantics for selecting and deselecting tests.
- Pytest has better configurability around test collection.
- Pytest has a bigger suite of plugins, better community support, and more rapid issue resolution.
- Pytest has built in support for pluggable fixtures and monkeypatching (mocks).

I realize some of these assertions I've made are subjective, but in my experience, py.test is superior in almost every way. It's a constant frustration to me that I can't use some of the powerful features of pytest.

I do love nose for its namesake, and the minimal output during test runs is nice, but those benefits pale in comparison to those I'm missing above.

Are there any objections to dropping nose and adopting pytest as the test framework?

**Comment by webknjaz** [comment]
Sounds reasonable. I've heard lots of good feedbacks about py.test as well.

**Comment by coady** [comment]
Re "minimal output during test runs is nice":  py.test's verbosity options can be set in `setup.cfg` as well.

**Comment by jaraco** [comment]
For some stupid reason, Travis is putting the 3.5 test in the allowed failures: https://travis-ci.org/cherrypy/cherrypy/builds/186426365

But it's not doing that on master. What's weird is there's [no difference in the matrix definition between the pytest branch and the master branch](https://github.com/cherrypy/cherrypy/compare/0a9ee7bc80c4c630d6b16463af833babb208a753...a7ce6324f4a0272e10fba37a4dde778556cfb9b9#diff-354f30a63fb0907d4ad57269548329e3), the latter of which runs Python 3.5 tests normally.

**Comment by jaraco** [comment]
Well, 96d9db98 seemed to fix that.

**Comment by jaraco** [comment]
After restarting a couple of the jobs showing spurious failures, I have a [clean build of CherryPy on pytest](https://travis-ci.org/cherrypy/cherrypy/builds/186428583).

I'm going to merge this into master now, and file tickets for the individual test failures as needed.

**Comment by webknjaz** [comment]
@jaraco You removed Python 3.2 from Travis CI config.
It seems we should completely wipe 3.1/3.2 from classifiers in `setup.py` as well as from officially supported versions everywhere.
Do you mind?

**Comment by jaraco** [comment]
The latest release officially supports Python 3.2, even though the tests don't run properly, due primarily to the issue with tox. I plan to drop support for Python 3.2, but I'll wait to see what happens with tox-dev/tox#428 first. If tox is willing to support Python 3.2, CherryPy can too.
