### ISSUE TITLE
7.1 install error on Windows

### ISSUE THREAD

**Issue by bsamek** [cherrypy/cherrypy#1467]
7.0 installs successfully on the AWS EC2 Windows 2012 R2 base image ami-3c32b12b (with Git and Python 2.7.12). However, the 7.1 installation returns an error:

Installed c:\python27\lib\site-packages\mongo_orchestration-0.6.3-py2.7.egg
Processing dependencies for mongo-orchestration==0.6.3
Searching for CherryPy>=3.5.0
Reading https://pypi.python.org/simple/CherryPy/
Best match: CherryPy 7.1.0
Downloading https://pypi.python.org/packages/b7/dd/e95de2d7042bd53009e8673ca489effebd4a35d9b64b75ecfcca160efaf6/CherryPy-7.1.0.zip#md5=6b32d36c30a496dcdb7764a5c354fcc9
Processing CherryPy-7.1.0.zip
Writing c:\users\admini~1\appdata\local\temp\2\easy_install-cwvpqk\CherryPy-7.1.0\setup.cfg
Running CherryPy-7.1.0\setup.py -q bdist_egg --dist-dir c:\users\admini~1\appdata\local\temp\2\easy_install-cwvpqk\CherryPy-7.1.0\egg-dist-tmp-zanxh1
zip_safe flag not set; analyzing archive contents...
cherrypy._cpmodpy: module references __file__
cherrypy._cptree: module references __file__
cherrypy.lib.covercp: module references **file**
cherrypy.lib.cpstats: module references **file**
cherrypy.lib.gctools: module MAY be using inspect.getframeinfo
cherrypy.lib.profiler: module references **file**
cherrypy.process.plugins: module references **file**
cherrypy.scaffold.**init**: module references **file**
cherrypy.test.benchmark: module references **file**
cherrypy.test.checkerdemo: module references **file**
cherrypy.test.helper: module references **file**
cherrypy.test.modfastcgi: module references **file**
cherrypy.test.modfcgid: module references **file**
cherrypy.test.modpy: module references **file**
cherrypy.test.modwsgi: module references **file**
cherrypy.test.test_caching: module references **file**
cherrypy.test.test_config: module references **file**
cherrypy.test.test_config_server: module references **file**
cherrypy.test.test_core: module references **file**
cherrypy.test.test_logging: module references **file**
cherrypy.test.test_misc_tools: module references **file**
cherrypy.test.test_request_obj: module references **file**
cherrypy.test.test_routes: module references **file**
cherrypy.test.test_session: module references **file**
cherrypy.test.test_states: module references **file**
cherrypy.test.test_static: module references **file**
cherrypy.test.test_virtualhost: module references **file**
cherrypy.test.test_wsgiapps: module references **file**
cherrypy.tutorial.tut01_helloworld: module references **file**
cherrypy.tutorial.tut02_expose_methods: module references **file**
cherrypy.tutorial.tut03_get_and_post: module references **file**
cherrypy.tutorial.tut04_complex_site: module references **file**
cherrypy.tutorial.tut05_derived_objects: module references **file**
cherrypy.tutorial.tut06_default_method: module references **file**
cherrypy.tutorial.tut07_sessions: module references **file**
cherrypy.tutorial.tut08_generators_and_yield: module references **file**
cherrypy.tutorial.tut09_files: module references **file**
cherrypy.tutorial.tut10_http_errors: module references **file**
creating c:\python27\lib\site-packages\cherrypy-7.1.0-py2.7.egg
Extracting cherrypy-7.1.0-py2.7.egg to c:\python27\lib\site-packages
Adding cherrypy 7.1.0 to easy-install.pth file
Installing cherryd script to c:\Python27\Scripts

Installed c:\python27\lib\site-packages\cherrypy-7.1.0-py2.7.egg
error: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'c:\users\admini~1\appdata\local\temp\2\easy_install-cwvpqk\CherryPy-7.1.0\cherrypy\test\static\????? ???????.html'

**Comment by jaraco** [comment]
Here are [the changes between 7.0.0 and 7.1.0](https://github.com/cherrypy/cherrypy/compare/v7.0.0...v7.1.0).

**Comment by jaraco** [comment]
Looks like [this commit](14d20220f8a5) is implicated, as it adds a file with non-ascii characters to the package. Still, that shouldn't break the install.

**Comment by jaraco** [comment]
I tried replicating on a Windows 10 instance in Powershell on Python 2.7.9 with pip 1.5.6 and 8.1.2, but every install was successful.

**Comment by jaraco** [comment]
Oh, looks like you might be using easy_install, not pip.

**Comment by jaraco** [comment]
With `easy_install`, I'm able to replicate the failure.

**Comment by jaraco** [comment]
When I run with `easy_install -v`, I get more detail:

```
Installed c:\program files\python27\lib\site-packages\cherrypy-7.1.0-py2.7.egg
changing mode of c:\users\jaraco\appdata\local\temp\easy_install-dbjnrl\CherryPy-7.1.0\cherrypy\test\static\????? ???????.html to 200
chmod failed: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'c:\\users\\jaraco\\appdata\\local\\temp\\easy_install-dbjnrl\\CherryPy-7.1.0\\cherrypy\\test\\static\\????? ???????.html'
error: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'c:\\users\\jaraco\\appdata\\local\\temp\\easy_install-dbjnrl\\CherryPy-7.1.0\\cherrypy\\test\\static\\????? ???????.html'
```

**Comment by jaraco** [comment]
I was able to replicate the underlying failure with this simple script:

```
# encoding: utf-8

from __future__ import unicode_literals

import os
import shutil

os.mkdir('temp')

with open('temp/Слава Україні.html', 'w'):
    pass

print(os.listdir(b'temp')[0])

shutil.rmtree(b'temp')
```

On Windows, this script will crash with:

Python 2

```
Traceback (most recent call last):
  File "C:\Users\jaraco\p\cherrypy\issue-1467.py", line 15, in <module>
    shutil.rmtree(b'temp')
  File "C:\Program Files\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Program Files\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'temp\\????? ???????.html'
```

or Python 3

```
Traceback (most recent call last):
  File "C:\Users\jaraco\p\cherrypy\issue-1467.py", line 15, in <module>
    shutil.rmtree(b'temp')
  File "c:\python\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\python\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\python\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: b'temp\\????? ???????.html'
```

Unix apparently isn't subject to this issue. Consider Python 3.5.2 on Mac OS:

```
$ python ~/p/cherrypy/issue-1467.py 
b'\xd0\xa1\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xb0 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd1\x96\xcc\x88\xd0\xbd\xd1\x96.html'
```

**Comment by marunguy** [comment]
I have a similar problem when install CherryPy 7.1 using pip on Windows.
https://groups.google.com/forum/#!topic/cherrypy-users/7G30-UfSqtU

**Comment by jaraco** [comment]
This issue can be fixed ~~by upgrading to Setuptools 25.1.2 (releasing imminently)~~ ~~or by using pip to install CherryPy~~ or by upgrading to Python 3.

**Comment by marunguy** [comment]
The same error still occurs when install CherryPy 7.1 using pip on Winodws.

```
D:\pydevenv\win32>pip install -U setuptools
Collecting setuptools
  Using cached setuptools-25.1.2-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 25.1.1
    Uninstalling setuptools-25.1.1:
      Successfully uninstalled setuptools-25.1.1
Successfully installed setuptools-25.1.2
```

```
D:\pydevenv\win32>pip install -U CherryPy
Collecting CherryPy
  Using cached CherryPy-7.1.0.tar.gz
Exception:
Traceback (most recent call last):
  File "d:\devtool\py27x86\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\devtool\py27x86\lib\site-packages\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "d:\devtool\py27x86\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "d:\devtool\py27x86\lib\site-packages\pip\req\req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "d:\devtool\py27x86\lib\site-packages\pip\download.py", line 810, in unpack_url
    hashes=hashes
  File "d:\devtool\py27x86\lib\site-packages\pip\download.py", line 653, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "d:\devtool\py27x86\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "d:\devtool\py27x86\lib\site-packages\pip\utils\__init__.py", line 577, in untar_file
    with open(path, 'wb') as destfp:
IOError: [Errno 22] invalid mode ('wb') or filename: 'd:\\users\\me\\appdata\\local\\temp\\pip-build-ef4yey\\CherryPy\\cherrypy/test/static/\xd0\xa1\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xb0 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd1\x97\xd0\xbd\xd1\x96.html'
```

**Comment by jaraco** [comment]
I'm not able to replicate the issue with pip 8.1.2, so I suspect the user was using an older version of pip:

```
C:\Users\jaraco> C:\Users\jaraco\.virtualenvs\issue3894\Scripts\python -m pip --version
pip 8.1.2 from C:\Users\jaraco\.virtualenvs\issue3894\lib\site-packages (python 2.7)
C:\Users\jaraco> C:\Users\jaraco\.virtualenvs\issue3894\Scripts\python -m pip install cherrypy==7.1.0
Collecting cherrypy==7.1.0
ï»¿  Using cached CherryPy-7.1.0.tar.gz
Collecting six (from cherrypy==7.1.0)
ï»¿  Downloading six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: cherrypy
  Running setup.py bdist_wheel for cherrypy ... done
ï»¿  Stored in directory: C:\Users\jaraco\AppData\Local\pip\Cache\wheels\48\bb\36\837f964b8aa03a1a7ef0cfb47f42dbcc73b2fe
e745276d2c10
Successfully built cherrypy
Installing collected packages: six, cherrypy
Successfully installed cherrypy-7.1.0 six-1.10.0
C:\Users\jaraco> C:\Users\jaraco\.virtualenvs\issue3894\Scripts\python -m pip uninstall -y cherrypy
Uninstalling CherryPy-7.1.0:
  Successfully uninstalled CherryPy-7.1.0
C:\Users\jaraco> C:\Users\jaraco\.virtualenvs\issue3894\Scripts\python -m pip install --no-use-wheel cherrypy==7.1.0
DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.
Collecting cherrypy==7.1.0
ï»¿  Using cached CherryPy-7.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in c:\users\jaraco\.virtualenvs\issue3894\lib\site-package
s (from cherrypy==7.1.0)
Skipping bdist_wheel for cherrypy, due to binaries being disabled for it.
Installing collected packages: cherrypy
  Running setup.py install for cherrypy ... done
Successfully installed cherrypy-7.1.0
```

**Comment by jaraco** [comment]
In pypa/pip#3894, I've reported that the issue could not be replicated. I suspect all you need to do is upgrade your pip and it will install.
