### ISSUE TITLE
Set session data while testing?

### ISSUE THREAD

**Issue by ibrewster** [cherrypy/cherrypy#1470]
I am writing tests for my CherryPy app using cherrypy.test.helper.CPWebCase subclasses. One thing I need to test is that my code at one point correctly handles the situation where a session variable is set to an invalid value. From CherryPy code I would just call `cherrypy.session['varname']='bad_value'` or the like to set the session variable, but trying to do this in my testing code gives an error - presumably because the testing code is in a different thread. So how can I set cherrypy session variables from my testing code?

One ugly approach I thought of was simply writing an exposed function that takes an arbitrary key and value and sets that in the session object, but I would need to be able to limit this to be called by testing functions only somehow - that is not the sort of thing I would want to expose to the world.

**Comment by webknjaz** [comment]
The short answer is to patch `cherrypy.session` with a dummy instance of `RamSession`. Extended answer to this question can be found [@ SO](https://stackoverflow.com/a/39044461/595220).

@jaraco plz close this issue and label it with `question` tag.
