### ISSUE TITLE
What do I do if I think I found a security problem

### ISSUE THREAD

**Issue by EternityForest** [cherrypy/cherrypy#1471]
Just curious as to what the protocol would be to report such things if I did in fact find one(Not sure if I did). Is it best to create an issue out in the open or to send a private message.

**Comment by jaraco** [comment]
Thanks for asking.

Unless you think it's going to have a widespread impact, then just file a ticket. If you think it'll be widespread and dangerous to disclose the detail in public, then reach out to me or one of the other maintainers privately in Gitter to assess.
