### ISSUE TITLE
Memcached session backend server address cannot be configured

### ISSUE THREAD

**Issue by michal-juranyi** [cherrypy/cherrypy#1472]
Memcached server address seems to be hardcoded as class attribute and can't be configured through standard config. I think it must be quite common case to have shared memcached or at least hosted on different machine.

**Comment by jaraco** [comment]
Seems like a reasonable request - would you be able to provide a pull request to fix the issue?

**Comment by michal-juranyi** [comment]
I reviewed the code again and found out that there is a for cycle in setup method which passes all session configs to class attributes with the same name. So this isn't an issue right now.
