### ISSUE TITLE
Consider providing extras in setup.py

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cherrypy#1480]
#### Background

There are some features in cherrypy relying on third-party packages. These packages are not required to run 'hello world', but they are mandatory it some cases.
They are not even documented.
#### Examples

For example, there's `RoutesDispatcher` requiring `routes` to be installed:

``` python
In [7]: import cherrypy

In [8]: cherrypy.dispatch.RoutesDispatcher
Out[8]: cherrypy._cpdispatch.RoutesDispatcher

In [9]: cherrypy.dispatch.RoutesDispatcher()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-9dac1dec18e6> in <module>()
----> 1 cherrypy.dispatch.RoutesDispatcher()

~/.pyenv/versions/3.5.2/envs/cptest-pyenv-virtualenv/lib/python3.5/site-packages/cherrypy/_cpdispatch.py in __init__(self, full_result, **mapper_options)
    507         parameters. By default they won't be.
    508         """
--> 509         import routes
    510         self.full_result = full_result
    511         self.controllers = {}

ImportError: No module named 'routes'
```

By the way, it's being skipped in Travis tests (which should also be fixed).

Other optional requirements are `nose` if user tries using `cherrypy.test.helper`:

``` python
In [1]: from cherrypy.test import helper
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c4c383c4e751> in <module>()
----> 1 from cherrypy.test import helper

~/.pyenv/versions/3.5.2/envs/cptest-pyenv-virtualenv/lib/python3.5/site-packages/cherrypy/test/helper.py in <module>()
     27     import subprocess
     28
---> 29 import nose
     30
     31 _testconfig = None

ImportError: No module named 'nose'
```

It's also not obvious dependency, since in docs `py.test` is the suggested test runner (and from my experience trying to run such tests with `nosetests` stucks the terminal!)

Finally, memcached backend also requires installing appropriate client:

``` python
In [1]: from cherrypy.lib.sessions import MemcachedSession

In [2]: MemcachedSession.setup()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f2731d8ba194> in <module>()
----> 1 MemcachedSession.setup()

~/.pyenv/versions/3.5.2/envs/cptest-pyenv-virtualenv/lib/python3.5/site-packages/cherrypy/lib/sessions.py in setup(cls, **kwargs)
    613             setattr(cls, k, v)
    614
--> 615         import memcache
    616         cls.cache = memcache.Client(cls.servers)
    617     setup = classmethod(setup)

ImportError: No module named 'memcache'
```
#### Suggested actions
- [x] Inspect codebase and find all 'side effect' dependencies (@jaraco do you recall any I didn't mention?)
- [x] Add `extras` to `setup.py` allowing to enable any of above:
  - [x] [xcgi]
    - [x] flup [add python specifiers]
  - [x] ~~mod_python~~ [cannot be installed via pip]
  - [x] [ssl]
    - [x] pyOpenSSL
  - [x] [json]
    - [x] simplejson
  - [x] [doc]
    - [x] docutils
    - [x] sphinx_rtd_theme
  - [x] [multienv_tests]
    - [x] tox
  - [x] [:sys_platform == "win32"]
    - [x] pywin32
  - [x] ~~psycopg2~~ [removed](https://github.com/cherrypy/cherrypy/commit/50efcdcafe8221b80812f36bfacb6e86a1325cc0#commitcomment-18846277)
  - [x] ~~wsgiconq~~ #1484 (removed)
  - [x] [test_tools]
    - [x] coverage
    - [x] nose
    - [x] nose-testconfig
    - [x] mock [for py<3.3]
    - [x] objgraph
  - [x] [memcached_session]
    - [x] python-memcached [done via #1476]
  - [x] [routes_dispatcher]
    - [x] routes
- [x] Add docs

**Comment by jaraco** [comment]
The tox.ini file defines "deps" including nose, mock, Routes. If we move to pytest, the test requirements would probably be declared in "tests_require" in setup.py. Still, some of these aren't strictly required of tests but are optional to be included (and possibly tested).

**Comment by webknjaz** [comment]
My point is not about testing of cherrypy itself, but about usability of enabling feature flags for end-users.

**Comment by jaraco** [comment]
Yes, that seems reasonable, although a requirement of `cherrypy[routes]` is nominally more clear than `cherrypy routes`, and `cherrypy[routes,memcached-sessions]` may be less clear than a requirement of `cherrypy routes memcached`. Adding extras gives the benefit of making the feature officially supported, but it also adds the obligation of officially supporting that feature.

I'm okay with seeing the extras declarations added, and maybe some docs, but once you do that, you have have three places to maintain that relationship (in the docs, in the package metadata, and in the code itself). If you think the benefits justify that effort, then let's do it.

**Comment by webknjaz** [comment]
Yes, I think it's worth it. I'll prepare PR.
