### ISSUE TITLE
Synchronize with cheroot

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1481]
I very much appreciate the work that cheroot has done to factor out the HTTP Server portion of CherryPy into a standalone HTTP Server.

The effort seems to have been abandoned. I take some blame in that as well.

I'd like to revive the effort, but I see a few obstactles.
1. Cheroot was released, but never officially. The [only releases are beta releases](https://pypi.python.org/simple/cheroot/).
2. The project appear to be a fork of CherryPy, but the code base diverged a long time ago and was never consumed by CherryPy, so reconciling the differences may be a massive effort.
3. The [project repo](/cherrypy/cheroot) has issues disabled.

Now that CherryPy allows for dependencies to be defined, I think it's at a better place to factor out the wsgiserver. 

Here's what I propose:
1. Abandon the existing cheroot codebase. Maybe there are some gems there, and they'll remain in the history in case someone wants to dig them up.
2. Replace the existing cheroot with wsgiserver from cherrypy. As a drop-in replacement, it will be compatible with CherryPy.
3. Keep the cheroot tests that pass but disable or remove the rest.
4. Document CherryPy tests passing as a temporary condition for acceptable stability.
5. Cut the first stable release (5.0) and iterate from there.
6. Re-enable issues in Cheroot.

Then, iterate on the goals and shortcomings.

Thoughts?

**Comment by jaraco** [comment]
I discovered that the /cherrypy/cheroot project, although it's based on the same cherrypy history, due to the transition from Mercurial to Git, no longer is considered related to the cherrypy history as found here on Github. Therefore, what I've done is rebase the cheroot 4.0.0b2 changes onto a checkout of cherrypy (still against 3.2.2 as before), and pushed those changes up to the cheroot origin under the tag `archive/cheroot-4`. Now I'll push the latest cherrypy master (with a related git history) up as the cheroot master and re-enact the refactor into a separate project.

**Comment by jaraco** [comment]
I've also tagged the old master as archive/old-cheroot-master, in case anybody ever wants to go find that history.

**Comment by jaraco** [comment]
Now in the cheroot master, which is up-to-date with the cherrypy master, I'll review the refactor that [happened here](https://github.com/cherrypy/cheroot/commit/577b83acef2281d11537fb7974c913b4f7a5bd3c) and try to re-apply it to the current CherryPy project tree.

**Comment by jaraco** [comment]
So the tests are substantially passing against the new cheroot (currently just linked to the github repo). For some reason, the Python 2 tests are exiting promptly. I see the same when I test locally, so it shouldn't be too difficult to track down. In the meantime, the functionality remains in the [cheroot branch](/cherrypy/cherrypy/tree/cheroot).

**Comment by jaraco** [comment]
After restoring a missing `__init__.py` in cheroot, the CherryPy tests now pass against the master of cheroot. The CherryPy tests are still relying on `cherrypy.test.helper` and `cherrypy.test.webtest`. I believe more refactoring will need to happen in those modules before they can start to rely on the cheroot versions.

**Comment by Safihre** [comment]
Do we need to refill issues regarding the `wsgiserver` on the new repo? 
In my case it's #1509 and #1552. But surely there are more in the Issues list here at cherrypy.

**Comment by webknjaz** [comment]
I think you meant #1523

**Comment by webknjaz** [comment]
@Safihre PRs which are merged are already there. Others may need to be cherry-picked to `cheroot` if they affect `wsgiserver`

**Comment by Safihre** [comment]
Actually I meant #1552, typo!

**Comment by jaraco** [comment]
Yes, if you would please re-file that PR with cherrypy/cheroot.

**Comment by jaraco** [comment]
This work is essentially done. What remains is cherrypy/cheroot#3.

**Comment by Safihre** [comment]
@jaraco I was actually asking about [all the open issues about the `wsgiserver` listed here on CherryPy-repo](https://github.com/cherrypy/cherrypy/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20wsgiserver), if they won't be forgotten.

**Comment by jaraco** [comment]
Well, they won't be forgotten - they just need to be addressed in cheroot. I'm not going to migrate those issues. They can continue to have a home here until such a time as they're fixed in the upstream cheroot or migrated there manually.
