### ISSUE TITLE
cherrypy.request.body.read() not document

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1482]
can't find it (should be here: https://cherrypy.readthedocs.io/en/3.3.0/refman/_cpreqbody.html).

**Comment by webknjaz** [comment]
Current version is `7.1.0`. Plz check the latest doc to see up-to-date information: http://docs.cherrypy.org/en/latest/pkg/cherrypy.html?highlight=request.body#cherrypy._cprequest.Request.body

**Comment by webknjaz** [comment]
Closing due to http://stackoverflow.com/q/39112752/595220#comment65617034_39112752
