### ISSUE TITLE
WSGI applications are required to return bytes.

### ISSUE THREAD

**Issue by fgallaire** [cherrypy/cherrypy#1489]
Needs @jaraco advice about:
fgallaire/wsgiserver#2

**Comment by jaraco** [comment]
Graham makes a good argument. I want to remove as many references to ISO-8859-1 from the code as possible, and removing this leniency is one place where that can be done. The tests continue to pass if text is refused with a ValueError, so I'm inclined to simply reject text values. Thanks for raising this here.
