### ISSUE TITLE
Vulnerabilities were found in CherryPy/3.1.2 WSGI Server

### ISSUE THREAD

**Issue by nomadtunguska** [cherrypy/cherrypy#1491]
1. Verbose error messages
   Example:
   <HTTP REQUEST>
   GET /<INPUT type="text" value='<SCRIPT>alert("XSS")</SCRIPT>'> HTTP/1.1
   Host: {target}

<HTTP RESPONSE>
HTTP/1.1 500 Internal Server Error
Content-Length: 526
Content-Type: text/plain

Traceback (most recent call last):
  File "/logs2/splunk/lib/python2.7/site-packages/cherrypy/wsgiserver/**init**.py", line 1229, in communicate
    req.parse_request()
  File "/logs2/splunk/lib/python2.7/site-packages/cherrypy/wsgiserver/**init**.py", line 317, in parse_request
    self._parse_request()
  File "/logs2/splunk/lib/python2.7/site-packages/cherrypy/wsgiserver/__init__.py", line 397, in _parse_request
    rp = int(req_protocol[5]), int(req_protocol[7])
ValueError: invalid literal for int() with base 10: '"'
1. Cleartext submission of password
2. Cookie without Secure flag set
   Example:

<HTTP REQUEST>
POST /en-US/account/login HTTP/1.1
Host: {target}

cval=1031731019&return_to=%2Fen-US%2F&username=admin&password=password

<HTTP RESPONSE>
HTTP/1.1 200 OK
Expires: Thu, 26 Oct 1978 00:00:00 GMT
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
Content-Type: text/html;charset=utf-8
Date: Thu, 01 Sep 2016 12:06:51 GMT
Content-Length: 8480
Cache-Control: no-store, max-age=0, no-cache, must-revalidate
Set-Cookie: cval=1031731019
Set-Cookie: session_id_2082=08a7740d0a402c81dc0b2a0c6ecd323d1411335e; httponly; Path=/
Connection: close
Server: CherryPy/3.1.2 WSGI Server

Best Regards,
Nomad
Independent Security Researcher

**Comment by webknjaz** [comment]
1. v3.1.2 is an out-of-date version of CherryPy
2. Please be more verbose
3. Confirm your issue with `master` version
4. Also [follow these instructions](/cherrypy/cherrypy#i-have-found-a-bug) to proceed

**Comment by jaraco** [comment]
You probably only need to set the environment to `production` to hide the verbose error messages. I'm pretty sure this request is invalid as a result, so I'm closing, but do clarify and we can re-open as appropriate.
