### ISSUE TITLE
Restricting File Upload?

### ISSUE THREAD

**Issue by EternityForest** [cherrypy/cherrypy#1498]
It appears that when someone uploads a file, it gets placed on disk immediately, before any user code is called.

Is this correct? And if so, is there a security issue due to the possibility of someone repeatedly uploading large files and using up disk bandwidth, or even possibly destroying an SD card by exceeding write endurance?

Would it be practical to add some sort of file filter such that any attempted uploads would be filtered through a function, which could decide what to do with the raw stream and either return a file handle, or some higher level object created from the stream, or just reject it entirely?

Thanks for your time!

**Comment by webknjaz** [comment]
File is not being saved to disk unless you do this explicitly. In your request handler you may access the `request.body` readable file-like object and then read this stream, process and write anywhere you want.

Please check these modules for more info regarding your question and request processing implementation:
https://github.com/cherrypy/cherrypy/blob/master/cherrypy/_cprequest.py#L323-L329
https://github.com/cherrypy/cherrypy/blob/master/cherrypy/_cpreqbody.py#L362-L363

**Comment by EternityForest** [comment]
So I was doing some testing with an unrelated bug in some other code and noticed that uploading files causes a file like /tmp/#4460225 to be created and immediately deleted, so something does appear to be written to disk.

Also, documentation says "When a client uploads a file to a CherryPy application, it's placed
on disk immediately."

Is the documentation out of date?  Do I have a config option set that I don't know about?

**Comment by webknjaz** [comment]
Could you please provide a source code snippet with an app example?

**Comment by EternityForest** [comment]
Allright here's a minimal example for linux, I don't have a windows machine handy.

```python
import cherrypy,html
class HelloWorld(object):
    def index(self,file=None):
        return 'File:'+html.escape(repr(file))+"""<form method="POST" enctype="multipart/form-data">
                <input name="file" type="file"></input><input type="submit"></form>"""
    index.exposed = True

cherrypy.quickstart(HelloWorld())
```

Then in bash(I don't know how to test this on windows):
`sudo fatrace|grep python`

Every time a large file is uploaded, I get something like this which appears to be coming from the cherrypy process:

```
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
python3(9793): W /tmp/#4460211 (deleted)
```

**Comment by webknjaz** [comment]
I guess you are right: https://github.com/cherrypy/cherrypy/blob/master/cherrypy/_cpreqbody.py#L500-L515
It looks like temporary file is being created.

Also, [CherryPy raises HTTP 413 error](https://github.com/cherrypy/cherrypy/blob/master/cherrypy/_cpreqbody.py#L805) in case if the file len exceeds `maxbytes` value. [Here's an example of setting it 100 bytes limit for a file upload](http://docs.cherrypy.org/en/latest/_modules/cherrypy/test/test_config_server.html):

```python
#! /usr/bin/env python

import cherrypy, html


class HelloWorld:
    @cherrypy.expose
    @cherrypy.config(**{'request.body.maxbytes': 100})
    def index(self, file=None):
        file_repr = html.escape(repr(file))
        return f""""
            File: {file_repr}
            <form method="POST" enctype="multipart/form-data">
                <input name="file" type="file">
                <input type="submit">
            </form>
        """

cherrypy.quickstart(HelloWorld())
```

**Comment by webknjaz** [comment]
I'm assuming that there's no concerns left here.

**Comment by EternityForest** [comment]
I think we're good. I was able to use maxbytes to limit uploads, and I've created a patch with unit tests and documentation that allows you to set up a callback to have a dynamic maxbytes based on ip address or auth tokens.

It also makes maxrambytes configurable, as the default 1000 bytes is less than ideal for some uses.

I don't know if there's interest in this upstream, but it's useful for certain embedded devices that use a ramdisk for /tmp and often don't have much spare ram. In those devices you might want authorized users to be able to upload large files but you definitely wouldn't want just anyone DoSing all your ram.

If there is interest, here's my changed code.
https://github.com/EternityForest/cherrypy/tree/dynamic-upload-limit

**Comment by webknjaz** [comment]
@EternityForest well, this looks interesting.

Could you please create a PR to upstream, so we'd review it and probably merge?
It will be required that you fix some style issues, which currently break the build on linters stage and I also noticed some unintentional bugs in docs.

It would be easier for @jaraco and me to decide in which way/form this could affect upstream if we see it in PR, we must consider usability for the community, not just one user.

**Comment by EternityForest** [comment]
Allright, here's the PR. I would have done it sooner, but I've heard some projects have rules about not accepting unannounced PRs, and I wasn't sure.

**Comment by webknjaz** [comment]
@EternityForest no worries. The worst thing that could happen: (1) someone suggests better solution or/and (2) you are asked to improve certain things to be compliant with "rules".

P.S. If you want to know more about open source, check out this website https://opensource.guide/. It's a good collection of guides

**Comment by webknjaz** [comment]
Here's another way for you to change request max size on fly with current upstream. You may create a [hook, which would run just before the body processing](http://docs.cherrypy.org/en/latest/extend.html#per-request-functions) logic called, which would amend the required property:
```python
#! /usr/bin/env python

import cherrypy, html


@cherrypy.tools.register('before_request_body')
def conditional_maxbytes_config():
    if True:  # <-- your conditional here
        cherrypy.request.body.maxbytes = 1000


class HelloWorld:
    @cherrypy.expose
    @cherrypy.config(**{'request.body.maxbytes': 100})  # default
    @cherrypy.tools.conditional_maxbytes_config()
    def index(self, file=None):
        file_repr = html.escape(repr(file))
        return f""""
            File: {file_repr}
            <form method="POST" enctype="multipart/form-data">
                <input name="file" type="file">
                <input type="submit">
            </form>
        """

cherrypy.quickstart(HelloWorld())
```

**Comment by EternityForest** [comment]
Hmmm. Maybe it would be better to implement this as just an included tool?

**Comment by webknjaz** [comment]
Please post your suggestion as code snippet, I'm not sure I totally get your idea. I'll keep the ticket open for discussion.

**Comment by EternityForest** [comment]
You could create a built-in tool that would let you validate uploads something like this, for a similar
easy to use API, and without having to modify the core if you decide that the feature doesn't belong directly in the request handling code.
```python
@cherrypy.config(**{'tools.large_upload.on': True, 'tools.large_upload.callback': my_callback})
@cherrypy.expose
def some_url(self, **kwargs):
    pass
```

You could even add a method like this, that would automatically set up a function to allow long verified uploads with a callback.
```python
@cherrypy.allow_large_request(my_verify_func)
@cherrypy.expose
def some_url(self, **kwargs):
    pass
```

**Comment by webknjaz** [comment]
Here's a way to achieve your goal with custom body processor:

```python
#! /usr/bin/env python

import cherrypy, html


@cherrypy.tools.register('before_request_body')
def custom_processor_body_limit():
    request = cherrypy.serving.request
    _old_proc = request.body.processors['multipart/form-data']

    def new_processor(entity):
        if int(entity.headers.get("Content-Length", 0)) > 1000:
            raise cherrypy.HTTPError(413)
        _old_proc(entity)

    request.body.processors['multipart/form-data'] = new_processor


class HelloWorld:
    @cherrypy.expose
    @cherrypy.tools.custom_processor_body_limit()
    def index(self, file=None):
        file_repr = html.escape(repr(file))
        return f""""
            File: {file_repr}
            <form method="POST" enctype="multipart/form-data">
                <input name="file" type="file">
                <input type="submit">
            </form>
        """

cherrypy.quickstart(HelloWorld())
```

**Comment by webknjaz** [comment]
Regarding build-in tool/decorator, I still don't know whether users need yet another method of limiting request payload.
[Zen of Python](https://www.python.org/dev/peps/pep-0020/) has this nice principle: *There should be one-- and preferably only one --obvious way to do it.*
And I've shown you 3 ways already.

**Comment by webknjaz** [comment]
@EternityForest did any of my code examples satisfy your needs?

**Comment by EternityForest** [comment]
The tool looks like a perfectly good solution for my use case(when combined with increasing maxrambytes), thanks!

I still think maxrambytes should be configurable though.

**Comment by webknjaz** [comment]
Alright, let's follow the review process in PR then. I've posted my thoughts there.
