### ISSUE TITLE
Cherrypy does not pass -O parameter on AutoReload

### ISSUE THREAD

**Issue by cinatic** [cherrypy/cherrypy#1500]
Hi guys,

i just noticed that if i start the engine with python -O myStarter.py and cherrypy reloaded via its autoreload functionality, it starts without -O again. Really annoying because i use different configurations on release system

**Comment by webknjaz** [comment]
It is re-exec with `sys.argv`: https://github.com/cherrypy/cherrypy/pull/1450/files#diff-be33a4f55d59dfc70fc6452482f3a7a4R407

The thing is that only trailing arguments (those after script or command) are getting into `sys.argv`:

``` python
$ python -O -i 
Python 3.5.0 (default, Nov 12 2015, 10:49:15) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.argv
['']
>>> 

$ python -O -c 'import sys; print(sys.argv)'
['-c']

$ python -c 'import sys; print(sys.argv)' -O 
['-c', '-O']
```

**Comment by webknjaz** [comment]
As a workaround I suggest setting `PYTHONOPTIMIZE` environment variable, which does the same thing:

``` bash
$ python --help
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options and arguments (and corresponding environment variables):
...
-O     : optimize generated bytecode slightly; also PYTHONOPTIMIZE=x
-OO    : remove doc-strings in addition to the -O optimizations
..
arg ...: arguments passed to program in sys.argv[1:]
...
```

E.g.

``` bash
$ PYTHONOPTIMIZE=1 python myStarter.py
# or
$ export PYTHONOPTIMIZE=1
$ python myStarter.py
```

**Comment by cinatic** [comment]
thank you very much for pointing this out and the workaround. 

the export variable works great but python -O starter.py -O will fail too

**Comment by webknjaz** [comment]
why would it fail?

**Comment by webknjaz** [comment]
Notes:
I've found this approach of getting python interpreter using `ctypes` http://stackoverflow.com/a/28338254/595220, but it only works in Python 2 for me. Running under Python 3 results in returning only the first char of each argument.

Still there's `sys.flags`, which looks much more hacky to me to use

``` python
>>> import sys
>>> sys.flags
sys.flags(debug=0, py3k_warning=0, division_warning=0, division_new=0, inspect=1, interactive=1, optimize=1, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, tabcheck=0, verbose=0, unicode=0, bytes_warning=0, hash_randomization=0)
```

**Comment by webknjaz** [comment]
Meanwhile, I'll leave these here for further investigation:
http://stackoverflow.com/a/6683222/595220
http://stackoverflow.com/a/28414807/595220

**Comment by webknjaz** [comment]
@jaraco what do you think about all of this?

**Comment by jaraco** [comment]
It seems that when cherry py launches the new process it could try to start a process with as much of the same environment as the parent process. For optimize, it could set os.environ[PYOPTIMIZE] = sys.flags.optimize. 

but actually, auto reloader is meant for development mode, where optimize probably isn't needed. Auto reloader should probably not be used in production. 

Can @cinatic elaborate on what is the harm for not retaining interpreter flags? Could you simply disregard this difference?

**Comment by cinatic** [comment]
i totally agree with that AutoReload is not designed to use in a production system. On the other hand it just not works, if you need it, for whatsoever reason. But even then it is possible to use some kind of workaround.

I thought you should be at least aware of it

**Comment by webknjaz** [comment]
@jaraco I've managed to make `ctypes` approach working in both Python 2 and Python 3. I think, I'll try implementing it in cherrypy.
