### ISSUE TITLE
Response streaming does not work

### ISSUE THREAD

**Issue by stenci** [cherrypy/cherrypy#1502]
The following code inspired by the [documentation](http://docs.cherrypy.org/en/latest/advanced.html#streaming-the-response-body) does not work. The result is buffered and sent to the client at once.

```
import cherrypy
import time

class Root:
    @cherrypy.expose
    def thing(self):
        cherrypy.response.headers['Content-Type'] = 'text/plain'
        def content():
            yield "Hello, "
            time.sleep(3)
            yield "world"
        return content()
    thing._cp_config = {'response.stream': True}

print(cherrypy.__version__)
cherrypy.quickstart(Root())
```

**Comment by webknjaz** [comment]
@stenci don't you think `time.sleep()` blocks the thread?

**Comment by webknjaz** [comment]
It seems, this depends on the client you use. See http://stackoverflow.com/a/31922706/595220

Basically you may use this command to confirm it's working

``` bash
curl --trace-ascii - localhost:8080/thing
```

This works for me with the following src:

``` python
#! /usr/bin/env python

import cherrypy
import time

class Root:
    @cherrypy.expose
    @cherrypy.config(**{'response.stream': True})
    def thing(self):
        cherrypy.response.headers['Content-Type'] = 'text/plain'
        yield 'Hi, ' * 100
        time.sleep(3)
        yield 'there!'


if __name__ == '__main__':
    cherrypy.quickstart(Root())
```

**Comment by stenci** [comment]
I tried with Chrome, Firefox, IE, Edge and curl, and no one shows the streaming. I tried the example with longer buffer (I used your example and multiplied by 10000 on the first yield just to make the buffer longer), but the output comes out all at once. 

My scripts that spend hours importing thousands of files into a database used to show the progress using the `yield` with an older version of CherryPy / Python / Windows, but now I see nothing. 

I don't know where the regression is, but the documentation [here](http://docs.cherrypy.org/en/latest/advanced.html#streaming-the-response-body) describes something that was working and now is impossible (at least in my configuration).

I have:
- CherryPy 8.1.0
- Python 3.5.2 (Anaconda) 32 bit
- Windows 10.1607

**Comment by webknjaz** [comment]
I've already confirmed that it is working. You may check this with command I posted above.

Here's handler yielding additional timestamps:

``` python
#! /usr/bin/env python

from datetime import datetime
import time
import cherrypy

class Root:
    @cherrypy.expose
    @cherrypy.config(**{'response.stream': True})
    def thing(self):
        cherrypy.response.headers['Content-Type'] = 'text/plain'
        yield 'Hi, ' * 100
        yield str(datetime.now())
        yield '================='
        time.sleep(3 * 2)
        yield str(datetime.now())
        yield 'there!'


if __name__ == '__main__':
    cherrypy.quickstart(Root())
```

``` shell
$ curl --trace-ascii - localhost:8080/thing
== Info:   Trying ::1...
== Info: connect to ::1 port 8080 failed: Connection refused
== Info:   Trying 127.0.0.1...
== Info: Connected to localhost (127.0.0.1) port 8080 (#0)
=> Send header, 83 bytes (0x53)
0000: GET /thing HTTP/1.1
0015: Host: localhost:8080
002b: User-Agent: curl/7.46.0
0044: Accept: */*
0051: 
<= Recv header, 17 bytes (0x11)
0000: HTTP/1.1 200 OK
<= Recv header, 24 bytes (0x18)
0000: Server: CherryPy/8.1.0
<= Recv header, 39 bytes (0x27)
0000: Content-Type: text/html;charset=utf-8
<= Recv header, 37 bytes (0x25)
0000: Date: Mon, 19 Sep 2016 18:22:41 GMT
<= Recv header, 28 bytes (0x1c)
0000: Transfer-Encoding: chunked
<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 439 bytes (0x1b7)
0000: 190
0005: Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, 
0045: Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, 
0085: Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, 
00c5: Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, 
0105: Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, 
0145: Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, 
0185: Hi, Hi, Hi, Hi, 
0197: 1a
019b: 2016-09-19 21:22:41.744041
Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, Hi, 2016-09-19 21:22:41.744041<= Recv data, 23 bytes (0x17)
0000: 11
0004: =================
=================<= Recv data, 32 bytes (0x20)
0000: 1a
0004: 2016-09-19 21:22:47.750253
2016-09-19 21:22:47.750253<= Recv data, 11 bytes (0xb)
0000: 6
0003: there!
there!<= Recv data, 5 bytes (0x5)
0000: 0
0003: 
== Info: Connection #0 to host localhost left intact
```

Do you see timestamps? Their difference is 6 seconds. The output to console has stopped for 6 seconds as in handler too. This is my proof.

So look for bottlenecks in your scripts.

**Comment by stenci** [comment]
In Windows all the clients seem to buffer, so it seems to be a lower level problem in Windows.

Both Firefox and curl on Linux stream the output as expected, regardless of whether the CherryPy server runs on Windows or Linux.

Both Firefox and curl on Windows buffer the output. The output of curl on Windows shows the correct timestamps, but the whole content is displayed at once at the end.

The [documentation](http://docs.cherrypy.org/en/latest/advanced.html#streaming-the-response-body) already says:

> In general, it is safer and easier to not stream output

Perhaps it is worth adding:

> ... and it doesn't work well in Windows clients

I will run my scripts from Firefox running on Ubuntu on VirtualBox, so I can keep track of the progress without rewriting them. It's an horrible workaround, but it's the easiest way for me.

Thanks for your help

**Comment by webknjaz** [comment]
Just checked that streaming works well in Google Chrome under Windows 8.1
Perhaps this will save you from running VM :)

**Comment by stenci** [comment]
I used Windows 8.1 for a while, but I was allergic :) 

Unfortunately my app interacts with CAD, CAM Lotus and other antique software only available in Windows :(

**Comment by stenci** [comment]
A little update: last Friday I had to use a virtual Ubuntu machine to track the streaming of the page, today it works as expected on Chrome on Windows 10!  YAY

The output of curl and the behavior of Chrome and Firefox have changed: now I see the content as it is streamed by the server. Edge and IE still buffer the whole content before showing it.

A few Windows updates were pushed. I don't know which one affected the behavior.
