### ISSUE TITLE
Update docs link @ PYPI

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cherrypy#1503]
[CherryPy page at PYPI](https://pypi.python.org/pypi/CherryPy) contains link to [v5.1.0 docs at pythonhosted](http://pythonhosted.org/CherryPy/).

@jaraco please change it to http://docs.cherrypy.org/

**Comment by jaraco** [comment]
It's not possible to delete the docs, but I've uploaded a redirect per [this answer](http://stackoverflow.com/a/6531582/70170).
