### ISSUE TITLE
Py_GetArgcArgv is not available under Windows 10 (Python 2.7.12)

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cherrypy#1506]
@Safihre reports an issue with new re-spawn mechanism (#1504):

``` python
Traceback (most recent call last):
  File "C:\Users\x\Documents\GitHub\sabnzbd\cherrypy\process\wspbus.py", line 380, in _do_execv
    args = self._get_true_argv()
  File "C:\Users\x\Documents\GitHub\sabnzbd\cherrypy\process\wspbus.py", line 413, in _get_true_argv
    ctypes.pythonapi.Py_GetArgcArgv(ctypes.byref(argc), ctypes.byref(argv))
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'Py_GetArgcArgv' not found
```

My guess it that `Py_GetArgcArgv` is not available under that OS.

**Comment by webknjaz** [comment]
@Safihre could you please run contents of `_get_true_argv()` method step by step and identify which functions are available under  `ctypes.pythonapi`?

**Comment by webknjaz** [comment]
It looks this function is either not available under windows, or requires python-dev headers to be installed. My suggestion it to `try-except` this falling back to `sys.argv`. Alternatively we could try re-constructing original interpreter arguments with `sys.flags`.

**Comment by Safihre** [comment]
It seems all functions are available, except `Py_GetArgcArgv`.
I manually ran the other functions and they returned fine.

**Comment by webknjaz** [comment]
https://stem.torproject.org/_modules/stem/util/system.html
(And `Py_GetArgcArgv` seems to not be available under PyPy)

**Comment by webknjaz** [comment]
@Safihre does something like `dir(ctypes.pythonapi)` return anything?

**Comment by Safihre** [comment]
```
>>> pprint.pprint(dir(ctypes.pythonapi))
['_FuncPtr',
 '__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_func_flags_',
 '_func_restype_',
 '_handle',
```

**Comment by webknjaz** [comment]
It doesn't look like a full list. There's no `]` in output. Did you cut anything?

**Comment by Safihre** [comment]
Oh yeah, just 1: 🐹 

```
>>> pprint.pprint(dir(ctypes.pythonapi))
['_FuncPtr',
 '__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_func_flags_',
 '_func_restype_',
 '_handle',
 '_name']
```

**Comment by Safihre** [comment]
Think it will need that try/except!

**Comment by webknjaz** [comment]
Done. I've extended suggested workaround to guess interpreter args from `sys.flags` and `sys.warningoptions`. Feel free to test fixes :)

**Comment by Safihre** [comment]
👍 Confirmed it's working now!

**Comment by Safihre** [comment]
@webknjaz new problem with this:
When we freeze the app to an .exe (using py2exe), restart is not working because it's passing the wrong arguments.
Somehow it comes up with this:

```2016-11-29 22:08:08,905::INFO::[_cplogging:219] [29/Nov/2016:22:08:08] ENGINE Re-spawning C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe -E -OO -S C:\Users\xxx\Documents\GitHub\SABnzbd-1.2.x2-win32-bin\SABnzbd-1.2.x2\SABnzbd-console.exe```

The ```-E -OO -S``` are probably added during the freeze-process of py2exe.

**Comment by webknjaz** [comment]
@Safihre 
1) please file a new issue for that
2) please state whether it worked with some of earlier versions of CherryPy there
3) AFAIK these tools like py2exe never worked really well

**Comment by webknjaz** [comment]
Ref: #1526
