### ISSUE TITLE
CherryPy 8.1.1 install error on Windows using pip

### ISSUE THREAD

**Issue by marunguy** [cherrypy/cherrypy#1508]
When install CherryPy 8.1.1. on Windows, a error occurred.

```
D:\pydevenv\win32>pip install -U CherryPy
Collecting CherryPy
  Using cached CherryPy-8.1.1.tar.gz
Requirement already up-to-date: six in d:\devtool\py27x86\lib\site-packages (from CherryPy)
Collecting pywin32 (from CherryPy)
  Could not find a version that satisfies the requirement pywin32 (from CherryPy) (from versions: )
No matching distribution found for pywin32 (from CherryPy)
```

The installer of ["pywin32"](https://pypi.python.org/pypi/pywin32/) module is not available in pip.
But, the installer of ["pypiwin32"](https://pypi.python.org/pypi/pypiwin32) module is available in pip. 

I think that "pywin32" module is changed to "pypiwin32" in setup.py for convenience.

**Comment by webknjaz** [comment]
It seems you are right. I'll change that
