### ISSUE TITLE
error reading HTTP PATCH request's body

### ISSUE THREAD

**Issue by gitKearney** [cherrypy/cherrypy#1516]
When trying to process an HTTP PATCH request, the line

`cherrypy.request.json`

fails with an error: `AttributeError: 'Request' object has no attribute 'json' `

The cause of the error is in line 315 of _cherrypy_/__cprequest.py_

The line needs to be changed from

`methods_with_bodies = ('POST', 'PUT')`  **wrong**
to 
`methods_with_bodies = ('POST', 'PUT', 'PATCH')` **correct**

[// Related SO question](http://stackoverflow.com/questions/40534890/cherrypy-read-patch-body)

**Comment by webknjaz** [comment]
@gitKearney could you please send us a pull request with tests accompanying it?

**Comment by gitKearney** [comment]
@webknjaz I created a branch and am committing to it. I'm super new to Git, and contributing, so, I probably did everything wrong :'-( I'm sorry!

I created a new directory called "tests" which contains a simple server and a controller. I also created a simple script to send a PATCH request using _requests_

**Comment by gitKearney** [comment]
Hey, I think I did that properly, I forked the cherryPy branch, then
created a test directory with the serve, controller, and a caller.

If I did that improperly, I'm sorry. Just let me know what I need to do to
fix it

Kearney J. Taaffe

**Comment by webknjaz** [comment]
@gitKearney I've commented on your PR. Let's keep further communication there.
