### ISSUE TITLE
Cherrypy freezes on many parallel requets

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1518]
Dear cherrypy team,
Dear community,

I've observed that cherrypy freezes when many requests are sent in parallel, causing a denial of service situation. One can always overflow systems with too many requests, but in this case the system remains dead afterwards. The socket is still open and I can connect to it via Telnet, but requests are not handled anymore.

You can evaluate by launching BurpSuite Pro (or a similar tool) sending (in my case) 10000 requests with 15 threads in parallel.

Increasing the number of 'request_queue_size' when initializing the CherryPyWSGIServer, does not fix the issue but delays the issue to a higher load. With an request_queue_size increased to 32 I can send the 10000 requests with 15 threads in parallel. Increasing the request_queue_size to 64 then causes the issue again. Hence, as soon as the load is too high to get properly handled with the set request_queue_size, cherrypy freezes and remains dead.

Again: I know, too many requests cause denial of service at some point, but the thing is: the system should not remain dead after the DoS situation is over.

I originally discovered this issue via a vulnerability scan, but it seems to be independent of the request. It also occurs just sending a GET request to "/"

I was running cherrypy 6.0.2 on Ubuntu 14.04.5 LTS and already updated to the latest cherrypy version 8.1.2 but the issue remains.

**Comment by webknjaz** [comment]
Could you please provide us with any logs/tracebacks cherrypy generates?
P.S. Normally you would limit requests with nginx or similar proxy, wouldn't you?

**Comment by ghost** [comment]
Hi,

there are no error logs (they are empty), it just stops working. 

I'm using cherrypy as the web server of my application which is written in Flask. I love to have a web server native in python as it doesn't require any installation or configuration after deployment. 

This is the code I launch with:

```
# Init Flask application
app = myflask.Flask(myFlaskConfig, __name__, template_folder="templates", static_folder='static')

# Enable WSGI access logging
appLogged = TransLogger(app, logger_name="wsgi.access")

# Initialize WSGI server running the application
cherrypyReqQueueSize = 32 
server = wsgiserver.CherryPyWSGIServer((app.config.get("LISTENING_IP"), app.config.get("LISTENING_PORT")),  appLogged, request_queue_size=cherrypyReqQueueSize)

# Launch CherryPy WSGI server
server.start()
```

regarding your "P.S.": Why would I use cherrypy as the web server, when I need to put an Nginx in front - instead of directly using Nginx as my web server? I know for high availability/performance solutions I'd need to do so, but I don't need anything high secure/available. However, of course I want to have my small application still alive after someone temporary sends large amounts of data (e.g. a vulnerability scan where I don't care whether all these requests are properly responded to temporary)

**Comment by webknjaz** [comment]
Then I don't understand for what do you need cherrypy? You could use flask's server as well.
I cannot investigate anything with no info. The only thing I can suggest is to check for `MemoryError` exception in logs. I recall some issue with it, which seem to be still open.

**Comment by webknjaz** [comment]
I'm going to close this issue, unless you've got anything to add. Anyway, feel free to re-opening it once you provide more relevant info

**Comment by jaraco** [comment]
I agree it would be preferable for the web server to be robust under extreme load. What we would need to solve this is an analysis of the code to determine where the issue lies. That is, first demonstrate that the issue doesn't occur when creating a simple multi-threaded HTTP server on Python under the same load, then to add in the behaviors that CherryPy's wsgiserver does until the undesirable behavior is elicited. Additionally, test across a few representative Python versions (probably 2.7 and 3.x latest stable) and platforms (at least Linux and Windows) to confirm that the behavior isn't unique to a particular environment.

Having that investigation, I believe we'd be able to take action to correct for the behavior.

**Comment by ghost** [comment]
To answer the previous post, I chose Cherrypy because it states about itself to be production-ready.

> Out of the box, Cherrypyincludes its own production-ready HTTP server to host your application...

Furthermore, it can do multi-threading, while the flask web server is just a single-threaded development server. So in my opinion it was the perfect solution: simple, no installation, reliability but without setting up a high-available infrastructure with multiple hosts/software.

I repeat myself saying, a simple Nessus vulnerability scan should neither bring a production-ready, nor a development server down (respectively freeze it). 

However, we did some more detailed investigation by now and I would suggest to close this ticket. We still do not know what exactly caused the issue, whether it would be something that could be fixed within Cherrypy, or whether something different locked the Python GIL, or what else could have gone wrong. At the end we found a solution and gave up on finding the reason of the issue. The issue was hard to track because it did not cause any log messages, furthermore it was feeling quite random (not easy to reproduce) and there was nothing to see while debugging the running application. Last but not least the changes we made to fix the issue are totally not logical.

### So, how did our code look like and how could we solve the issue?

Basically, we were initializing a flask application. The flask application itself initialized a database connection using SQLalchemy (remote connection to a PostgreSQL database). To test the database connection, we executed a simple SELECT query ("SELECT 1"). Subsequently we mounted the fully initialized flask application including the database connection onto the Cherrypy web server. During high load after between 3.000 and 15.000 requests everything stopped working all out of a sudden. The web server's socket was still open and answering, but HTTP requests were not replied to anymore. Somehow everything was stuck. 

To hunt down the issue we started removing code piece by piece. Finally, we found out that simply removing the SELECT query we added to test the database connection as described above, fixed the issue. It is no issue to execute any database query within a request context (happening in a dedicated thread), but caused the delayed freeze once if it gets executed during the initialization (happening in the main thread). Weird.

Our fix was to remove the database test during the initialization in the main thread and to put it within the request context before each request of a user. The test was meant to raise a warning to the administrator if the database connection is not working. Now it does not warn on startup of the application anymore but at the first user's request. Not as intended, but better than a regularly freezing application :)

Thank you all for your time and patience!

**Comment by webknjaz** [comment]
@aosdf6dd wow, that is awkward. This is probably related to GIL. If you were using cherrypy's infrastructure I would suggest you doing such connectivity check inside of CherryPy Plugin.

Thank you for documenting your case :)

**Comment by mewalig** [comment]
I've been seeing similar problems and trying to track and fix them for some time now since we started to use cherrypy several years ago. I agree entirely with @aosdf6dd that the term "production-ready" was *grossly inaccurate* given the number of and severity of various issues we have found during that time and had to fix. We chose cherrypy for the same reasons mentioned above, but in hindsight we would not have chosen cherrypy had we known at the time the level of instability we were stepping into.

Anyway, as of now, the last major issue we are having is this one that is difficult to track down. Logs stop working, server becomes unresponsive. In my case, it seems to have something to do with SSL errors that happen in the normal course of SSL connections not being handled properly, possibly in combination with timeouts. My guess is that these issues are killing threads, and after enough of these failed responses occur, there are no more threads left to service the requests. A possible quick-and-dirty solution would be to have some way for the master thread to poll the threads for life, and kill+revive any zombies.

After much work committed to keeping cherrypy, we are finally going to throw in the towel and giving up on it and find another web engine, but I post this in the small chance that the above information may prove helpful to solving this elusive issue.

**Comment by webknjaz** [comment]
> My guess is that these issues are killing threads, and after enough of these failed responses occur, there are no more threads left to service the requests. A possible quick-and-dirty solution would be to have some way for the master thread to poll the threads for life, and kill+revive any zombies.

You may be partially right here. The thread pool size is static unless you use something like cherrypy-dynpool. A few recent versions of Cheroot have more intelligent connection pool handling (contributed by @the-allanc) that supposedly makes the problem go away.
As for killing threads, your suggestion is incorrect: Python doesn't have any supported/stable mechanism for killing threads from the outside (hacks don't count as they introduce a huge risk of corrupting the Python runtime). If something blocks the control flow inside a thread, it'll be stuck until unblocked (usually it happens inside of your handler.

**Comment by ghost** [comment]
@mewalig 

At the end, I believe, we've been tuning with these CherryPy arguments. I think they helped us to keep operating that web service.

```python
        SERVER = wsgi.Server(
            listener,
            app_logged,

            # Some reworked settings in order to handle more requests.
            request_queue_size = 128,  # Larger socket queue buffer than the default 5
            accepted_queue_size=128,
            numthreads=1000,
            max=4
        )
```

Generally, although I've been a fanboy for quite some time, we did not just dump Cherrypy but Python as a whole. I know better now, weak type safety (causing the IDE to lose track), runtime errors (causing errors to pop up in the customer's runtime environment after release), indentation (breaking code format and potentially leading to severe bugs after copy/paste) and the GIL (a throttle by design) are the world's biggest evils ;-)

**Comment by mewalig** [comment]
Thank you @webknjaz and @aosdf6dd, this is all super helpful and much appreciated (will definitely be trying those suggested settings). @aosdf6dd, totally agree re python and weak typing in general-- I feel like I went through a very similar experience and change in perspective. may I ask what you migrated to and how that's been working out for you?

**Comment by ghost** [comment]
I re-wrote everything in Golang. Took me at least half a year, but I'm quite happy now. Sometimes a major "refactoring" is a good idea, anyways, haha. It definitely fixed my pain points and runs so smooth. It's easy and efficient. Absence of inheritance makes everything easy to follow, at the cost of a little bit more copy/paste sometimes. 

The downside is, if you need something more exotic (e.g. older ciphers, active directory cross domain ticket authentication,...), it might not be there (yet), or might not be professionally maintained. Sometimes there are multiple candidates for a library, yet it isn't not so clear which one would be the future proof choice.  But the common things are available and well crafted. 

Spoiler: There will be no way around JetBrains Goland IDE, unless you prefer notepad ;-)

**Comment by mewalig** [comment]
Thank you @aosdf6dd, really appreciate the insight.

@webknjaz (or anyone else): while thread killing isn't feasible, what would be the simplest way to implement a mechanism that would allow me to find out at any time, without going into any debug mode or killing the process, if any threads have become unresponsive (assuming unresponsive is defined as just not responding within a known expected time period)? I'd think a simple centralized log where each entry has thread id + start/stop + current timestamp should suffice
