### ISSUE TITLE
Tutorial 8  - 404 not found - /generator 

### ISSUE THREAD

**Issue by matt-paul** [cherrypy/cherrypy#1521]
When running this code, and clicking on 'Give it now' button, it returns a 404 not found error for the path /generator

**Comment by Giancarlos** [comment]
Do you mind posting your code you're running?

**Comment by webknjaz** [comment]
@matt-paul Please show us your code.

**Comment by webknjaz** [comment]
I assume you have fixed your issue. If not, feel free to drop some detail here :)
