### ISSUE TITLE
[enhancement]Request to add attribute "ssl_ciphers" to "cherrypy._cpserver.Server" as "ssl_certificate".

### ISSUE THREAD

**Issue by WXITWangPeng** [cherrypy/cherrypy#1523]
Hi Team,
    Our security team got a request recently, need to dynamicly set cipher suites of https connections.
   Since Python(version >= 2.7.9) already supports API 

"context.set_ciphers()", then we can add attribute "ssl_ciphers", and transfer it to "ssl_builtin.py". Thus, if cherrypy use builtin ssl lib, it can dynamicly configure the cipher suites.
   
   I have a solution to add the attribute as the attachment, could you please help to review it?

[cherry_modify.zip](https://github.com/cherrypy/cherrypy/files/605285/cherry_modify.zip)

Thanks,
Cindy

**Comment by webknjaz** [comment]
Please create a Pull Request for this. It's not 90-s: we don't exchange emails with patches nowadays.

**Comment by webknjaz** [comment]
Okay, you've sent PR #1524. Closing the issue as a duplicate. Let's move discussion to that PR.
