### ISSUE TITLE
How can I install cherrypy offline ???

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1532]
I want to install cherrypy offline ,but pip install --find-links= . did not work....

**Comment by jaraco** [comment]
Works for me:

```
$ pip download -d saved cherrypy                           
Collecting cherrypy
  Using cached CherryPy-8.1.3-py3-none-any.whl
  Saved ./saved/CherryPy-8.1.3-py3-none-any.whl
Collecting six (from cherrypy)
  Using cached six-1.10.0-py2.py3-none-any.whl
  Saved ./saved/six-1.10.0-py2.py3-none-any.whl
Successfully downloaded cherrypy six
$ # disconnect network
$ python -m venv env                                       
$ env/bin/python -m pip install --find-links=saved cherrypy
Collecting cherrypy
Collecting six (from cherrypy)
Installing collected packages: six, cherrypy
Successfully installed cherrypy-8.1.3 six-1.10.0
```

Voila! Enjoy.

**Comment by ghost** [comment]
This is for Python 3 operation, what about python 2 ?? Python 2 cherry is not whl file, it's a zip file .
For python 2 this operation should blocked in step Collecting cherrypy and show some connection error. it must be need connect internet..

**Comment by ghost** [comment]
Can I copy cherrypy directory in site-packages for other non-internet computer...

**Comment by jaraco** [comment]
Hmm. you're right. There are a couple of issues here. First, the wheel cannot be universal. Now that we have releases, we should be able to cut python 2 wheels. The second issue is that the use of Setuptools_scm means a source distro will require setuptools_scm installed in advance to succeed. I think I have some suggestions for you that I'll explore tomorrow.

**Comment by jaraco** [comment]
@ccyg: Can you try with CherryPy 8.4.0 (releasing imminently)? It includes wheels for Python 2 so should be suitable for you to replicate the recipe above.

**Comment by ghost** [comment]
yes!!! I try to install and succeed.  can you put those operation in cherry document for other guys has seem problems like me, cause I find this solution for several days and much suffered. 

# pip download -d .  cherrypy

then download cherrypy  and  pypiwin32  and six 

# pip install --find-links=.  cherrypy

**Comment by jaraco** [comment]
@ccyg: Sounds like it would be an excellent addition to the [StackOverflow wiki](http://stackoverflow.com/documentation/cherrypy/topics). Please consider adding it there (that way you also get the credit).
