### ISSUE TITLE
Cannot install cherypy on Python 3.6 + Windows 10, Error : Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by jmzoda** [cherrypy/cherrypy#1537]
Cli text is just below.
Thank you

C:\Program Files\Python36\Scripts
λ pip3.6 install cherrypy==8.3
Collecting cherrypy==8.3
  Using cached CherryPy-8.3.0-py3-none-any.whl
Collecting six (from cherrypy==8.3)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pypiwin32; sys_platform == "win32" (from cherrypy==8.3)
  Using cached pypiwin32-219.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JM\AppData\Local\Temp\pip-build-tox4900r\pypiwin32\setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'

Command "python setup.py egg_info" failed with error code 1 in C:\Users\JM\AppData\Local\Temp\pip-build-tox4900r\pypiwin32\

C:\Program Files\Python36\Scripts
λ pip3.6 install cherrypy==8.2
Collecting cherrypy==8.2
  Downloading CherryPy-8.2.0-py3-none-any.whl (457kB)
    100% |████████████████████████████████| 460kB 1.6MB/s
Collecting pypiwin32; sys_platform == "win32" (from cherrypy==8.2)
  Using cached pypiwin32-219.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JM\AppData\Local\Temp\pip-build-tnmg6033\pypiwin32\setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'

Command "python setup.py egg_info" failed with error code 1 in C:\Users\JM\AppData\Local\Temp\pip-build-tnmg6033\pypiwin32\

**Comment by jaraco** [comment]
Looks like pypiwin32 doesn't support Python 3. :(

**Comment by jaraco** [comment]
Looks like it's a [bug that pypiwin32 doesn't want to fix](https://sourceforge.net/p/pywin32/bugs/522/).

**Comment by jaraco** [comment]
The issue is that pypiwin32 doesn't support source builds on Python 3 and doesn't have binary builds for Python 3.6.

**Comment by jaraco** [comment]
I've filed [a ticket upstream](https://sourceforge.net/p/pywin32/bugs/734/).

**Comment by jmzoda** [comment]
Thank you for the investigation

**Comment by jaraco** [comment]
I tried working out a workaround by making a build on Python 3.6, but it turns out pywin32 doesn't build on Python 3.6 yet. I run into errors relating to build environments. I think we'll have to temporarily drop support for this package on Python 3.6 to avoid the errors.

**Comment by jaraco** [comment]
v8.3.1 releasing now should probably work by bypassing that requirement.

**Comment by jmzoda** [comment]
I tried the latest version 8.5.0 and it works fine. Great job!
Thank you so much :)

**Comment by ghost** [comment]
In case anyone is curious, I have set up an organization to attempt to get pywin32 to work on Python 3.6. It looks like it may be a significant amount of work. See pywin32/pypiwin32#2

**Comment by ghost** [comment]
@jaraco The binaries for py3.6 have been uploaded.

**Comment by jmzoda** [comment]
Great job. Thank you

**Comment by dennylab** [comment]
I have this problem with v10.2.2 and py361 win32.
Changed my version now to 8.9.0.

EDIT: Strange because it worked while using pip install but not while using pip install -r requirements.txt. Maybe because of my other dependencies?

```
# Find out latest version: Example: python3 -m pip install --download . flask or https://pypi.python.org
# Check if new version is available: Use pycharm

# LX
# ========
#git+https://github.com/labsolutionlu/jinja
svgwrite==1.1.11
pyparsing==2.1.10
lxml==3.7.3 --install-option="build_ext" --install-option="-I/usr/local/include/libxml2" --install-option="-I/usr/local/include/libxslt"
docxtpl==0.3.5
pycrypto==2.6.1
psutil==5.2.2 # Benchmark tool
apscheduler==3.3.1 # Scheduler
cherrypy==8.9.0 # Cockpit and redmine2jira, Why not v10.2.2? See https://github.com/cherrypy/cherrypy/issues/1537
ws4py==0.4.2 # Cockpit
paramiko==1.18.2 # Why not v2? cryptography dependency. See http://bitprophet.org/blog/2016/04/23/paramiko-2.0-is-coming/

#xamlwrite was cloned from mozman/svgwrite@1.1.6. We cannot fork and push the changes because only what was needed was changed by obo. We need to cleanup first!

git+https://github.com/labsolutionlu/louie.git@py3 # pyscxml dependency. Installed before scxml because I removed the dependency from scxml setup.py
git+https://github.com/labsolutionlu/PySCXML.git@py3
suds-py3==1.3.3.0

XlsxWriter==0.9.6

# Dev
# ========
nose2==0.6.5
python_redmine==2.0.2
jira==1.0.10
requests==2.17.3 # Google Translate

# LX API
# ========
flask==0.12.2
graphql-core==1.1
graphene==1.4
git+https://github.com/labsolutionlu/graphene-sqlalchemy
flask_graphql==1.4.1
flask_cors==3.0.2
cx_Oracle==5.3

# LX
# ========
# Must be the last line! Because of "--install-option" (is global and pased to the other packages below)
git+https://github.com/labsolutionlu/Pillow.git@3.4.2_imagingft --install-option="build_ext" --install-option="--disable-jpeg" --install-option="--disable-zlib"
```

**Comment by jaraco** [comment]
@labsolution: I don't think you have this problem exactly. CherryPy 10.2.2 installs fine for me on a Windows machine.

```
PS C:\> rwt pypiwin32
Collecting pypiwin32
  Downloading pypiwin32-220-cp36-none-win_amd64.whl (9.0MB)
    100% |████████████████████████████████| 9.0MB 131kB/s
Installing collected packages: pypiwin32
Successfully installed pypiwin32-220
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z

PS C:\> rwt cherrypy
Collecting cherrypy
  Downloading CherryPy-10.2.2-py2.py3-none-any.whl (435kB)
    100% |████████████████████████████████| 440kB 1.1MB/s
Collecting six (from cherrypy)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pypiwin32; sys_platform == "win32" (from cherrypy)
  Using cached pypiwin32-220-cp36-none-win_amd64.whl
Collecting cheroot>=5.2.0 (from cherrypy)
  Downloading cheroot-5.5.0-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 2.0MB/s
Collecting portend>=1.6.1 (from cherrypy)
  Downloading portend-1.8-py2.py3-none-any.whl
Collecting tempora (from portend>=1.6.1->cherrypy)
  Downloading tempora-1.7-py2.py3-none-any.whl
Collecting pytz (from tempora->portend>=1.6.1->cherrypy)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 1.3MB/s
Installing collected packages: six, pypiwin32, cheroot, pytz, tempora, portend, cherrypy
Successfully installed cheroot-5.5.0 cherrypy-10.2.2 portend-1.8 pypiwin32-220 pytz-2017.2 six-1.10.0 tempora-1.7
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Note, I'm using [rwt](/jaraco/rwt) to install using pip without having to set up a virtualenv, but you'd get the same behavior from pip in a virtualenv.

That you're apparently getting the error above must be implicated by something in your environment or usage, so if there's an ongoing issue, you'll need to provide more information.

**Comment by dennylab** [comment]
He was using the whl of pypiwin32-220 while installing cherrypy-10.2.2 with pip install,. But he was using pypiwin32-119 zip!? while installing cherrypy-10.2. using my requirements.txt file...

**Comment by ghost** [comment]
pypiwin32 may have different version numbers for different python versions.

**Comment by jaraco** [comment]
I did notice there's no source dist for 220, so any attempt to install source only or using an installer other than pip will be unlikely to work.

**Comment by ERaunig** [comment]
Still a problem 

`C:\Users\e.raunig>pip install --no-cache-dir cherrypy
Collecting cherrypy
  Downloading CherryPy-11.1.0-py2.py3-none-any.whl (439kB)
    100% |████████████████████████████████| 440kB 6.0MB/s
Collecting jaraco.classes (from cherrypy)
  Downloading jaraco.classes-1.4.1-py2.py3-none-any.whl
Collecting portend>=2.1.1 (from cherrypy)
  Downloading portend-2.2-py2.py3-none-any.whl
Collecting six>=1.11.0 (from cherrypy)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting cheroot>=5.8.3 (from cherrypy)
  Downloading cheroot-5.8.3-py2.py3-none-any.whl (65kB)
    100% |████████████████████████████████| 71kB 7.2MB/s
Collecting pypiwin32; sys_platform == "win32" (from cherrypy)
  Downloading pypiwin32-219.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 6.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\EA4F9~1.RAU\AppData\Local\Temp\pip-build-cfcqknzx\pypiwin32\setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Building pywin32", pywin32_version)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\EA4F9~1.RAU\AppData\Local\Temp\pip-build-cfcqknzx\pypiwin32\`

**Comment by webknjaz** [comment]
@ERaunig you need to install `pypiwin32-220` version. It looks like your `pip` didn't catch up with it preferring sdist (zip), which is not available for `v220`. But there's wheels you could use. So please use them.
I'm going to guess that you use outdated `pip`/`setuptools`, or use Python version, which is different from `3.6`, since there's only two wheels available (https://pypi.python.org/pypi/pypiwin32):

* pypiwin32-220-cp36-none-win32.whl
* pypiwin32-220-cp36-none-win_amd64.whl

So go and ask pywin32 maintainers to provide sdist and/or all the wheel matrix in PYPI.

**Comment by ERaunig** [comment]
Thanks,

I had IT revert to 3.6 and now pip runs fine.

Sorry for the mixup.
