### ISSUE TITLE
Tests hang, process fails to die, leaves network stack hosed

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1541]
I've twice now run into this rare condition on macOS 10.12. I'm running CherryPy tests and at some point during the tests, they stall indefinitely. A Ctrl+C indicates a keyboard interrupt, but the process fails to exit. I'm furthermore unable to kill the host process even with a SIGKILL.

If I fight with the OS for a while, I can usually get the process to die, but the network stack remains hosed. Requests through other apps like Firefox are unusably slow. Additionally, attempting to re-run the CherryPy tests results in an immediate failure with no error message at the first test, regardless of which test is indicated:

```
$ tox -- -v --pdb -k 'not test_auth_basic'
python develop-inst-noop: /Users/jaraco/Dropbox/code/public/cherrypy
python installed: backports.unittest-mock==1.2.1,-e git+gh://cherrypy/cherrypy@d1fd6a0f59bbbc45ea92113333869df276347f71#egg=CherryPy,coverage==4.3.1,graphviz==0.5.2,nose==1.3.7,nose-testconfig==0.10,objgraph==3.1.0,py==1.4.32,pytest==3.0.5,repoze.lru==0.6,Routes==2.3.1,six==1.10.0
python runtests: PYTHONHASHSEED='337537584'
python runtests: commands[0] | pytest -v --pdb -k not test_auth_basic
========================================================================= test session starts =========================================================================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /Users/jaraco/Dropbox/code/public/cherrypy/.tox/python/bin/python3
cachedir: .cache
rootdir: /Users/jaraco/Dropbox/code/public/cherrypy, inifile: 
plugins: backports.unittest-mock-1.2.1
collected 264 items 

cherrypy/test/test_auth_digest.py::DigestAuthTest::testDigest ERROR: InvocationError: '/Users/jaraco/Dropbox/code/public/cherrypy/.tox/python/bin/pytest -v --pdb -k not test_auth_basic'
_______________________________________________________________________________ summary _______________________________________________________________________________
ERROR:   python: commands failed
```

Logging out and back in will not correct the issue, but restarting the system does, so the issue seems to be related to something in the kernel getting into a bad state.

**Comment by jaraco** [comment]
I don't see that there's anything CherryPy can or should do about this issue, but I wanted to register it here in case I find anything new in the future.

**Comment by webknjaz** [comment]
I've had similar issue under GNU/Linux in case of using `nose` as a testrunner (tests got stuck, only `kill -9` helps), changing to `pytest` fixed the issue.
