### ISSUE TITLE
How to disable pipelining

### ISSUE THREAD

**Issue by chaiminghui** [cherrypy/cherrypy#1549]
Greetings,

I have one question, I am not sure if pipelining is enabled in default for cherrypy, if yes then how to disable it? Thanks in advance.

**Comment by webknjaz** [comment]
Hi @chaiminghui,
I am not sure what you mean, could you please be more specific about what you mean by saying 'pipeline'?
P.S. Best place to ask this kind questions is StackOverflow :)

**Comment by webknjaz** [comment]
I assume you've already found answer to your question. If not, please feel free to post additional details :)
