### ISSUE TITLE
Built-in SSL INAPPROPRIATE_FALLBACK not caught

### ISSUE THREAD

**Issue by Safihre** [cherrypy/cherrypy#1552]
* **I'm submitting a ...**
[x] bug report

* **Do you want to request a *feature* or report a *bug*?**
When using the built-in SSL, it will use `ssl.create_default_context()` which will disable the use of SSLv2 and SSLv3. 
However, when a client does connect with one of these protocols, it will throw an error.

```
19/01/2017 13:28 [19/Jan/2017:13:28:12] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/SABnzbd/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/share/CACHEDEV1_DATA/.qpkg/QSabNZBdPlus/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: INAPPROPRIATE_FALLBACK] inappropriate fallback (_ssl.c:661)
```

* **What is the expected behavior?**
Show an error to the client. 
We are aware that most probably this is some sort of port-scanning service, but still.

* **Please tell us about your environment:**

 Python version: 2.7.13
 OS: All
 Browser: ?

**Comment by Red-M** [comment]
That error is raised to the client in the TLS/SSL handshake as its trying to fallback to what I can only guess is a bad protocol, to try and get your server to talk to it so it can do not so nice things.

**Comment by Safihre** [comment]
Indeed the reason it should be caught by CherryPy :)

**Comment by Red-M** [comment]
You can't show this to the client, the TLS/SSL connection is aborted because the server literally cannot start the connection to show the web page or the error to the user. A modern web browser will show a message to said user.

**Comment by webknjaz** [comment]
@Red-M you are right. I think @Safihre asks for nicer logging instead of trace.

**Comment by Safihre** [comment]
Exactly!
I didn't think about it, but indeed the client won't get the message.

**Comment by Safihre** [comment]
Fix in https://github.com/cherrypy/cheroot/pull/4

**Comment by webknjaz** [comment]
cherrypy/cheroot#4 is merged, so I'm assuming this is fixed.
