### ISSUE TITLE
Make documentation available for multiple versions 

### ISSUE THREAD

**Issue by wolph** [cherrypy/cherrypy#1556]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

It would be great if a few extra versions (say... the last 10 major versions) would be available on readthedocs. I'm currently working on a project which is running an older version and I can't easily upgrade so it would be very useful to have some old versions available.

To enable them:

1. Go to: https://readthedocs.org/dashboard/cherrypy/versions/
2. Check the `Active` checkbox for a few of the vX.Y.Z checkboxes

**Comment by jaraco** [comment]
I'm not interested in supporting this. It may be the case that simply checking the boxes will render the docs, but there could be bugs and other follow up work (like cleaning out these builds). If someone would like to take this role, I can grant access to the project in RTD.

**Comment by wolph** [comment]
I have no problem taking care of this. Provided I can merge back changes similar to #1555 for the other branches so I can get it to work again.

**Comment by jaraco** [comment]
> Provided I can merge back changes

Seems you've already identified one problem. I'm not sure what you're thinking when you say merge back changes. The docs for older versions are already tagged. Are you proposing making changes to the docs and replacing the tags to the edited versions? I feel a little uneasy about that, though not strictly opposed.

I just don't see the value of going to all this effort (and potentially making a mess of the repository) just to make older docs available. The latest docs are largely viable for releases going back to 3.2. In the cases where specific versions of the docs are needed, they could be read from source in the github repo.

Can you clarify what it is you're proposing?

**Comment by wolph** [comment]
> Seems you've already identified one problem. I'm not sure what you're thinking when you say merge back changes. The docs for older versions are already tagged. Are you proposing making changes to the docs and replacing the tags to the edited versions? I feel a little uneasy about that, though not strictly opposed.

Yes, exactly. Without the changes in the `conf.py` the docs won't properly render as you can see here: http://cherrypy-wolph.readthedocs.io/en/v9.0.0/pkg/cherrypy.test.html

> I just don't see the value of going to all this effort (and potentially making a mess of the repository) just to make older docs available. The latest docs are largely viable for releases going back to 3.2. In the cases where specific versions of the docs are needed, they could be read from source in the github repo.

It shouldn't be all that much work to be honest. Otherwise I wouldn't be offering since I'm pretty busy as it is. Besides enabling the checkboxes and adding the `conf.py` changes I don't think anything needs to happen.

As for reading the source in the Github repo, that's obviously possible but rendered docs are easier to read than source in some cases :)

**Comment by jaraco** [comment]
@WoLpH Since I'm uneasy about the effect this will have no the repo, can you for just one version demonstrate what you have in mind in your fork of the repo? If it's not too ugly, I'll authorize you to do the same here.

**Comment by wolph** [comment]
Effectively it would come down to 2 changes:

1. Changing the `conf.py` to mock correctly: https://github.com/cherrypy/cherrypy/commit/d1213de11ef71ced252faef9140ed64855b93105
2. Regenerating the files in `docs/pkg`: https://github.com/cherrypy/cherrypy/commit/84aa2aba399ea764a2a081f80fbc8d0e488963be

The full diff: https://github.com/cherrypy/cherrypy/compare/v9.0.0...WoLpH:v9.0.0

**Comment by jaraco** [comment]
When I clone that repo, here's what I see in a SourceTree graph:

![image](https://cloud.githubusercontent.com/assets/308610/23022007/b9131bf6-f41c-11e6-8db8-67e027725548.png)

This change will mean that:
 - For every release 10.0.0 and earlier, there will be a new head not in any branch with the same two commits.
 - For these releases, the code in the repo won't match the code in the sdist (though the installed code will be the same).
 - The history (even for new releases) will no longer display the correct dates for these releases. Instead, they will show the date of the new tags:

![image](https://cloud.githubusercontent.com/assets/308610/23022416/a96fec72-f41e-11e6-829a-e068e758a475.png)

I suppose these issues could be largely mitigated by restoring these tags after building the docs. Those doc builds will have the incorrect dates for the releases, but at least future builds would not.

So I'm okay with this if you're willing to put the repo back like you found it after getting the docs to build. Sound good?

**Comment by wolph** [comment]
Hmmm.. that's a bit annoying indeed.
There might be another solution though... rewriting the history so it replaces the commit. I fear that adding them temporarily will cause the docs to break eventually.

I'll see if I can make it work somehow...

**Comment by webknjaz** [comment]
Rewriting `master`? This is definitely not a good idea.

**Comment by jaraco** [comment]
Unless you restore the tags to the original commits, you'll never solve the second issue (code in the sdist is a mismatch for code in the repo at the tag). I don't think re-writing will be acceptable here. The two options I see are building the docs against transient tags or just accepting the past for what it was (broken) and moving forward with future releases only.

**Comment by wolph** [comment]
Hmm... you're probably right. Breaking the repository is definitely not worth it so I guess we should just leave it as is.

Thanks for the help :)
