### ISSUE TITLE
cherrypy logo redesigned

### ISSUE THREAD

**Issue by meyt** [cherrypy/cherrypy#1561]
a new logo for cherrypy i suggested, how it's look?

![cherrpy-logo-redesign svg](https://cloud.githubusercontent.com/assets/10482278/22872575/7e9da562-f1cf-11e6-8721-f09b9ca5b47c.png)

[cherrpy-logo-redesign.svg.zip](https://github.com/cherrypy/cherrypy/files/770218/cherrpy-logo-redesign.svg.zip)

**Comment by alecz20** [comment]
Which is this one supposed to replace? The Logo, the favicon.ico, both?
I'm not much for changing what is not broken but I am not against change; what is the reason for the new logo?

**Comment by jaraco** [comment]
It's cute, and clever. It feels a little flat, which could be a good thing. I like how it incorporates Python, whereas the current icon is just a cherry. I'm +0, but happy with it.

**Comment by meyt** [comment]
@alecz20 it's just an idea about new logo for future usage, if main contributors decide for improve the website visual looks or somethings like that. i think cherrypy really deserve to have larger community than now, and i hope it will helpful for that reason :)

**Comment by meyt** [comment]
@jaraco Thanks, this drawing in first step, i will improve it for look better if can be acceptable idea.
