### ISSUE TITLE
Can't use server with SSL

### ISSUE THREAD

**Issue by nickgermaine** [cherrypy/cherrypy#1563]
Arch Linux, Python3.6, Webpy0.40, cherrypy/tree/remove-wsgiserver2

I'm writing a webpy application that is essentially an API/web scraper.  It is connected to from a chrome extension on an https site, so I need to run webpy with an SSL.  So I generated my own using openssl, and added this code:

    from web.wsgiserver import CherryPyWSGIServer
    from web.wsgiserver.ssl_builtin import BuiltinSSLAdapter

    ssl_cert = open(os.path.abspath(os.path.join(os.path.curdir, 'security/server.crt')), "r")
    ssl_key = open(os.path.abspath(os.path.join(os.path.curdir, 'security/server.key')), "r")

    #print(ssl_cert)
    CherryPyWSGIServer.ssl_adapter = BuiltinSSLAdapter(ssl_cert, ssl_key)

After numerous problems, I made some progress.  Made changes as mentioned here: https://bugs.launchpad.net/webpy/+bug/1174185

Now, I'm getting this:
  File "/usr/lib/python3.6/site-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 46, in <module>
    class SSL_fileobject(wsgiserver.CP_makefile):
TypeError: function() argument 1 must be code, not str

It's referring to the ssl_cert and ssl_key variables.  

I'm really not sure how to convert str to code, as I'm not aware of any "code" type.  Could be a problem in webpy wsgi server that is calling the cherrypy stuff, not sure.  Here is a full traceback:

Traceback (most recent call last):
  File "main.py", line 44, in <module>
    app.run()
  File "/usr/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/application.py", line 341, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "/usr/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/wsgi.py", line 59, in runwsgi
    return httpserver.runsimple(func, server_addr)
  File "/usr/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/httpserver.py", line 169, in runsimple
    server = WSGIServer(server_address, func)
  File "/usr/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/httpserver.py", line 221, in WSGIServer
    server.ssl_adapter = create_ssl_adapter(server.ssl_certificate, server.ssl_private_key)
  File "/usr/lib/python3.6/site-packages/web.py-0.40.dev0-py3.6.egg/web/httpserver.py", line 207, in create_ssl_adapter
    from cherrypy.wsgiserver.ssl_pyopenssl import pyOpenSSLAdapter
  File "/usr/lib/python3.6/site-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 46, in <module>
    class SSL_fileobject(wsgiserver.CP_makefile):
TypeError: function() argument 1 must be code, not str

**Comment by alecz20** [comment]
Does it work if you use something like this?
```
cherrypy.server.ssl_module = 'builtin'
cherrypy.server.ssl_certificate = ssl_cert
...
cherrypy.quickstart()
```

where `ssl_cert` is a PEM certificate file (includes the key)

**Comment by nickgermaine** [comment]
OK. The cert I was using was a CRT. I will try with this and let you know.

**Comment by webknjaz** [comment]
AFAICS web.py uses copy-pasted wsgiserver, which has been moved into a separate package called [`cheroot`](https://github.com/cherrypy/cheroot). I'd suggest using it instead as it may have recent bugfixes merged in. I think it's now much more convenient to open such issues there.

**Comment by webknjaz** [comment]
Also you may wait until web.py adopts cheroot.
Ref: webpy/webpy#401

**Comment by webknjaz** [comment]
Feel free to reopen this issue in cheroot repo once web.py absorbs it :)
