### ISSUE TITLE
ws4py 0.3.5 incompatible with cherrypy 10.1.1

### ISSUE THREAD

**Issue by heppg** [cherrypy/cherrypy#1565]
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

When using cherrypy 10.1.1 with ws4py 0.3.5, I get following error message:
pi@raspberrypi:~/scratchClient $ python src/scratchClient.py -c ./config/config_arduino_uno.xml
Traceback (most recent call last):
  File "src/scratchClient.py", line 151, in <module>
    import server.scratchClientServer
  File "/home/pi/scratchClient/src/server/scratchClientServer.py", line 40, in <module>
    from ws4py.server.cherrypyserver import WebSocketPlugin, WebSocketTool
  File "/usr/local/lib/python2.7/dist-packages/ws4py/server/cherrypyserver.py", line 72, in <module>
    from cherrypy.wsgiserver import HTTPConnection, HTTPRequest, KnownLengthRFile
ImportError: No module named wsgiserver

Workaround: use cherrypy==8.1.0 ws4py==0.3.5

- Python version: 2.7.9
- OS: raspberry pi, raspbian 2017-01-11, embedded web server in 'scratchClient'

**Comment by webknjaz** [comment]
Hello @heppg,

This module `cherrypy.wsgiserver` was factored out into a separate package `cheroot`, it's not an issue of CherryPy. This should be fixed inside of `ws4py` itself.

The issue for this already exists in the appropriate repo: https://github.com/Lawouach/WebSocket-for-Python/issues/205.
And there's also a PR fixing this: https://github.com/Lawouach/WebSocket-for-Python/pull/206.

So please ping @Lawouach to proceed with merging it.
