### ISSUE TITLE
Searches in the documentation don't work

### ISSUE THREAD

**Issue by stenci** [cherrypy/cherrypy#1571]
Clicking on any result of any search on the documentation returns a 404 error.

For example click on any result of the following search:

http://docs.cherrypy.org/en/latest/search.html?q=something&check_keywords=yes&area=default#

**Comment by webknjaz** [comment]
@jaraco is in charge of docs hosting, let's see if he'll be able to track down the issue there

**Comment by jaraco** [comment]
I won't have time to track this down.

**Comment by webknjaz** [comment]
Oh.. I see what's happening.
Here's an example URL: `http://docs.cherrypy.org/en/latest/advanced.rst.html?highlight=something`

Note `.rst` in the filename, it's used to be just `advanced.rst.html`

**Comment by webknjaz** [comment]
This has been fixed at some point and now it's working fine.
