### ISSUE TITLE
Web Application on embedded system

### ISSUE THREAD

**Issue by gabriel-yahav** [cherrypy/cherrypy#1574]
HI ,

I'm planning to develop a web application that can manage a limited resource embedded system

(CPU speed ~ 500 MHz, vmlinux (at most 25-40 MB), RAM ~ 500MB) and I considered using

CherryPy infrastructure as the backend HTTP server running on the device .

The application won't include any DB, the backend should be able to run system command 

and probably user-logins (that are defined locally on the device). 

Do you thing the framework can function on such hardware ?  Performance is really critical .

Furthermore, do you have a support with SSL ?

Thanks !

**Comment by jaraco** [comment]
I would expect the footprint of CherryPy to be not significantly larger than a Python HTTPServer, so should fit comfortably in your specs.

CherryPy does include some SSL support, using pyopenssl and also Python builtin SSL implementations. If there's no documentation about it, you may need to dig into the code (also see [cheroot](https://github.com/cherrypy/cheroot)) or [ask questions on StackOverflow](http://stackoverflow.com/questions/tagged/cherrypy).
