### ISSUE TITLE
Encode URLs in redirect responses

### ISSUE THREAD

**Issue by mar10** [cherrypy/cherrypy#1577]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The standard response page for 30x errors contains the target URL as `href` as well as clear text.

* **What is the expected behavior?**
Even though browsers *mostly* will not display the result, but redirect instead, you never know:
Any input from unknown sources should be html-escaped.

* **Please tell us about your environment:**
CherryPy 3.8 until 10.1

**Comment by jaraco** [comment]
It's not clear to me what this report is trying to say until I look at the PR. Can you elaborate on what is unexpected by the current behavior, maybe by giving an example of how it could be problemmatic?

**Comment by webknjaz** [comment]
@jaraco if one uses `raise HTTPRedirect(..)` it produces HTTP response with an HTML page in body. That page lists urls `<a href={{attr}}>{{text}}</a>` and it looks like `{{text}}` is empty there.

**Comment by mar10** [comment]
This issue was initially triggered by a customer that runs SonarQube against a our CherryPy based app.
One of the security findings was a potential XSS vulnerability related to this.

I think they tried to send a GET request with some script code embedded in the URL args.
Since the sender is not authenticated, our redirects to a login page.
The redirect URL has the original URL added as parameter.

Consider this 
```py
    class RedirectApp(object):
        def index(self, **kwargs):
            raise cherrypy.HTTPRedirect("example.com/login?redir=<script>alert(1);</script>")
        index.exposed = True
    
    cherrypy.quickstart(RedirectApp())
```
CherryPy will respond with a 303 response that also contains an `<a>` tag in its body.
The link is currently generated like this:
```py
            msg += '<a href=%s>%s</a>.'
            msgs = [msg % (saxutils.quoteattr(u), u) for u in self.urls]
```
In general, URLs may contain special characters like '<' (even if they are url-quoted as '%3c'), they should be html-escaped before inserted into html:
```py
            msg += '<a href=%s>%s</a>.'
            msgs = [msg % (saxutils.quoteattr(u), escape_html(u)) for u in self.urls]
```
This response page is hardly ever displayed by a browser, because it would redirect instead, but it is still considered a vulnerability of criticality HIGH by certain test suites.
