### ISSUE TITLE
Version number should mention CherryPy and Cheroot

### ISSUE THREAD

**Issue by mar10** [cherrypy/cherrypy#1579]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Currently the server version is reported like 'CherryPy/10.1'
The version number was taken from the Server object, which has moved to the Cheroot project recently (which has its own version numbers).
cherrypy/cheroot#5 changed this, so the Cheroot server now reports its version number correctly.

I propose that CherryPy reports its version number now like 'CherryPy/10.1 Cheroot/5.1'.

**Comment by webknjaz** [comment]
Thank you for your contribution!
