### ISSUE TITLE
Correct content-type leads to ValueError (unicode)

### ISSUE THREAD

**Issue by kienerj** [cherrypy/cherrypy#1584]
* **I'm submitting a bug report.**

* **What is the current behavior?**

My application returns data that is ASCII Text however this text has a special meaning and custom mime type. (It's chemical data:  https://en.wikipedia.org/wiki/Chemical_file_format#The_Chemical_MIME_Project)

If I don't set a content-type (defaults to html)  or set it to `text/plain` but works but is semantically incorrect.  If I set content type to one of the aboves, say for example `chemical/x-mdl-molfile` I get an error:

```python
  File "/home/.conda/envs/webservices/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/.conda/envs/webservices/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 831, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.

Set the content-type of a response:

`cherrypy.response.headers['Content-Type'] = 'chemical/x-mdl-molfile'`

* **What is the expected behavior?**

Same output as with content-type `text/plain`

* **What is the motivation / use case for changing the behavior?**

Correctness.

* **Please tell us about your environment:**

- Python version: 3.5.2 (anaconda python)
- OS: Ubuntu 16.04
- Browser: Chrome | Firefox | IE (Error happens in backend, browser unrelated)

**Comment by webknjaz** [comment]
@kienerj the traceback you submitted looks incomplete, could you please post it all?
Also please mind posting minimum reproducible hello-world style code snippet demonstrating the issue.

**Comment by jaraco** [comment]
I presume you're using the encoding tool. That's good. The encoding tool has an option `text_only`, which defaults to True. My guess is that because your content-type doesn't begin with `text/`, then it's not considered as text and is thus not encoded by the encoding tool.

`chemical` isn't a [registered media type](http://www.iana.org/assignments/media-types/media-types.xhtml), so that's probably why you wouldn't expect it to be recognized.

If you set `text_only=False` on the encoding tool for your app, does that correct the behavior?

**Comment by kienerj** [comment]
@webknjaz 

Adding that to the default helloworld tutorial causes the issue:

    import os.path
    import cherrypy

    class HelloWorld:

        @cherrypy.expose
        def index(self):
            cherrypy.response.headers['Content-Type'] = 'chemical/x-mdl-molfile'
            return 'Hello world!'


    tutconf = os.path.join(os.path.dirname(__file__), 'tutorial.conf')
    if __name__ == '__main__':

        cherrypy.quickstart(HelloWorld(), config=tutconf)


It is the complete trace I get. Only thing missing is the  first line:

Traceback (most recent call last):

@jaraco 

I'm not consciously using the encoding tool ( I don't know it, new to cherrypy). Is this on by default or does setting the response header activate it? Anyway adding ' tools.encode.text_only = False` to the config does fix the issue.

i think this is related to Issue #1123

**Comment by webknjaz** [comment]
It looks you are right. Seems it's exactly the same issue.
@jaraco should we catch this somewhere and put more explicit error message to log?

**Comment by exocomet** [comment]
Sorry for digging this up. I just ran into an issue after upgrading from Python 2.7 to 3.7. In my case I return a base64 encoded gif, with these settings, and got the same Exception as @kienerj 

    cherrypy.response.headers['Content-Type'] = 'image/gif'
    cherrypy.response.headers['Content-Encoding'] = 'base64'

I found this [post](https://stackoverflow.com/a/55039512/417133) on StackOverflow helpful, but I couldn't find any other documentation about the `text_only=False` setting. I read the source, but it's not clear to me why this Encoder setting is needed anyway? What does it, are there any side effects if I set this globally?

**Comment by webknjaz** [comment]
@exocomet this may be happening because `str` is `bytes` under Python 2 and `unicode` under Python 3.

Here's where it's used in code: https://github.com/cherrypy/cherrypy/blob/1980247/cherrypy/lib/encoding.py#L71

P.S. Posting new questions in old issues is not a good idea for getting attention. Locking this one.
