### ISSUE TITLE
from cherrypy import wsgiserver -> ImportError: cannot import name wsgiserver

### ISSUE THREAD

**Issue by VJalili** [cherrypy/cherrypy#1585]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
```
>>> from cherrypy import wsgiserver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name wsgiserver
```

* **What is the expected behavior?**
Using the latest version of `cherrypy` I'm expecting to be able to perform this import. I could temporarily resolve the issue going back to version `8.9.0`. But I'm wondering if there any better solution. 

* **Please tell us about your environment:**

- Python version: 2.7.10
- OS: macOS Sierra
- Browser: Opera

**Comment by webknjaz** [comment]
@VJalili It's been moved to [`cheroot`](https://github.com/cherrypy/cheroot): see the [changelog](http://docs.cherrypy.org/en/latest/history.html#v9-0-0).

Ref #1481

**Comment by dwilches** [comment]
So the solution is to not use:
```
from cherrypy import wsgiserver
```
But instead:
```
import wsgiserver
```

**Comment by webknjaz** [comment]
No @DWilches, the generic solution is:
```python
try:
    from cheroot.wsgi import Server as WSGIServer
except ImportError:
    from cherrypy.wsgiserver import CherryPyWSGIServer as WSGIServer
```

**Comment by dimyme** [comment]
works for me:  line 3271

```
        # from cherrypy   import           wsgiserver                                  # This will fail for CherryPy >= 9                                   ###    TODO
        from cheroot.wsgi import Server as WSGIServer
        self.options['bind_addr'] = (self.host, self.port)
        self.options['wsgi_app'] = handler

        certfile = self.options.get('certfile')
        if certfile:
            del self.options['certfile']
        keyfile = self.options.get('keyfile')
        if keyfile:
            del self.options['keyfile']

        server =              WSGIServer(**self.options)  ##    wsgiserver.CherryPyWSGIServer(**                  WSGIServer.CherryPyWSGIServer(**
```

**Comment by premsoftorg** [comment]
pip install web.py==0.40.dev1 

This above command should solve the issue. Open your python or conda environment execute above command. It will work like a charm.
