### ISSUE TITLE
Unable to get session object durring get.

### ISSUE THREAD

**Issue by fullstackpancham** [cherrypy/cherrypy#1601]
Hi ,
I am new to python and working on a project in cherrypy 3 and python 3.6.it uses module controller to call a API .eg. localhost/Login the module controller will find the method named as Login in main file and call it get data from it generate response from it.every method is called from main file from callModule method in which it pass session to each method as parameter but the passed session get None durring get .I have checked that it start creating session with the required data and create object but unable to get that object during get.I am stuck in this Please provide me solution.

**Comment by webknjaz** [comment]
You've already posted question to [SO](https://stackoverflow.com/q/44307194/595220),
it's not an issue for github. Please stick there or ask at gitter as per README. But anyway you'll be asked to post your code snippet. Nobody is going to write code for you.
