### ISSUE TITLE
rfile.read(0) creates infinite loop + memory hog that crashes server if not killed fast enough

### ISSUE THREAD

**Issue by mewalig** [cherrypy/cherrypy#1602]
I'm submitting a bug report

When processing a POST with chunked encoding, read(0) on rfile will go into an infinite loop that hogs memory until the process is killed or the server crashes (I'm not sure whether this issue also exists with non-chunked encoding). I am using Django and sample code to reproduce is:

        if request.method == 'POST':
            f = request.META.get('wsgi.input')
            # f will be type cherrypy.wsgiserver.wsgiserver2.ChunkedRFile
           x = f.read(0)
           ...

sample curl to reproduce:

    curl -X POST -d @bunch_of_data.dat 'http://...'

The problem seems to be in cheroot/server.py, where read() does not differentiate between size being None and size being zero. it goes into an infinite loop and the following line will eat up more and more memory until none is left:

    data += self.buffer

 To fix, insert the indicated lines below:

    def read(self, size=None):
        data = EMPTY

        if size == 0:   ### INSERT THIS LINE
            return data ### INSERT THIS LINE

        while True:
            if size and len(data) >= size:
                return data

            if not self.buffer:
                self._fetch()
                if not self.buffer:
                    # EOF
                    return data

            if size:
                remaining = size - len(data)
                data += self.buffer[:remaining]
                self.buffer = self.buffer[remaining:]
            else:
                data += self.buffer

am running with Python version: 2.7 on osx

**Comment by webknjaz** [comment]
Ref: #1486

**Comment by webknjaz** [comment]
@mewalig could you please create a PR with a change you propose?

**Comment by mewalig** [comment]
done
https://github.com/cherrypy/cheroot/pull/30
