### ISSUE TITLE
Portend(2.1.2)/Tempora(1.8) missing dependency

### ISSUE THREAD

**Issue by jrivera294** [cherrypy/cherrypy#1606]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

Install Cherrypy via pip install (https://pypi.python.org/pypi/CherryPy) fails.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.

Just run a pip install cherrypy

Use -U to force the update if you have it installed in your environment.

It happens with the current version (pip install cherrypy==10.2.2

Log:
Collecting portend>=1.6.1 (from cherrypy)
  Downloading http://pypiserver.taric.local/packages/portend-2.1.2-py2.py3-none-any.whl
Collecting tempora>=1.8 (from portend>=1.6.1->cherrypy)
  Could not find a version that satisfies the requirement tempora>=1.8 (from portend>=1.6.1->cherrypy) (from versions: 1.7, 1.7.1)
No matching distribution found for tempora>=1.8 (from portend>=1.6.1->cherrypy)

* **What is the expected behavior?**

A clean install without dependency errors

* **Please tell us about your environment:**

- Python version: 2.7.X
- OS: Ubuntu 16.04 LTS
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

The dependency bug comes from the portend==2.1.2 dependency, that depends at the same time of tempora==1.8, that doesn't exists in the pypi server.

It happens because the current dependency rule in cherrypy ask for portend (>=1.6.1), the package manager download the lastet version portend 2.1.2, and few days ago portend changes it dependencies rules to ask for tempora (>=1.8).

Actually, the problem isn't in CherryPy, but it can be solved using fixed dependencies rules, and update they when a new version of CherryPy is tested, to avoid that a change on these dependencies causes problems like this, or worse, a bug on a stable CherryPy version.

To solve this problem I had to manually install first a stable version of portend (1.8), to satisfy the dependency before install CherryPy.

**Comment by webknjaz** [comment]
Ref jaraco/tempora#4

**Comment by jaraco** [comment]
Umm. I'm unable to replicate your report.

```
$ ~/.envs/sandbox/bin/pip install -t /tmp/issue1606 cherrypy
Collecting cherrypy
  Using cached CherryPy-10.2.2-py2.py3-none-any.whl
Collecting six (from cherrypy)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cheroot>=5.2.0 (from cherrypy)
  Using cached cheroot-5.7.0-py2.py3-none-any.whl
Collecting portend>=1.6.1 (from cherrypy)
  Using cached portend-2.1.2-py2.py3-none-any.whl
Collecting tempora>=1.8 (from portend>=1.6.1->cherrypy)
  Using cached tempora-1.8-py2.py3-none-any.whl
Collecting pytz (from tempora>=1.8->portend>=1.6.1->cherrypy)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Installing collected packages: six, cheroot, pytz, tempora, portend, cherrypy
Successfully installed cheroot-5.7.0 cherrypy-10.2.2 portend-2.1.2 pytz-2017.2 six-1.10.0 tempora-1.8
```

I'm not sure why your pip isn't discovering tempora. It may be due to the fact that PyPI is currently hiding 1.8 in favor of 1.7.1... but that doesn't explain why it's also finding 1.7.

I suspect you're not actually doing `pip install cherrypy` but you're installing from a non-canonical repository (http://pypiserver.taric.local)... and that repo has a stale cache.

Can you confirm that your PyPI server is in fact reporting the same thing as PyPI for the 'simple' endpoint for `tempora`, specifically that 1.8 appears there?

**Comment by jaraco** [comment]
Moreover, CherryPy has continuous integration tests that would fail if these dependencies couldn't be met, but [do not fail](https://travis-ci.org/cherrypy/cherrypy/jobs/250833336). The issue is almost surely local to your environment.

**Comment by jrivera294** [comment]
@jaraco You are right, I forgot to disable my pypi server to test.

If you do a pip search tempora you can see that it's exposing this:
```
tempora (1.7.1)                                 - Objects and routines
                                                  pertaining to date and time
                                                  (tempora)
  INSTALLED: 1.8
  LATEST:    1.7.1
````

I did a pip install and it downloaded the 1.8, but the latest still show 1.7.1 lol

Anyway, it seems to be a problem between my pypi server and https://pypi.python.org/

Thanks!

**Comment by jaraco** [comment]
Cool. I'll update PyPI to show 1.8 as the latest. I wanted to refrain from making any changes while you were investigating.

**Comment by jrivera294** [comment]
Perfect. Tempora 1.8 is available on my server now.

Thanks again =)
