### ISSUE TITLE
Bug: TypeError: __init__() got an unexpected keyword argument 'proxy_mode'

### ISSUE THREAD

**Issue by time-river** [cherrypy/cherrypy#1622]
* **I'm submitting a ...**
bug report， and solution

* **What is the current behavior?**
```log
[17/Aug/2017:12:51:41] ENGINE TypeError("__init__() got an unexpected keyword argument 'proxy_mode'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cheroot/server.py", line 929, in communicate
    req = self.RequestHandlerClass(self.server, self)
  File "/usr/lib/python2.7/site-packages/CherryPy-11.0.1.dev70+g1b979c3e-py2.7.egg/cherrypy/_cpwsgi_server.py", line 27, in __init__
    server, conn, proxy_mode=True
TypeError: __init__() got an unexpected keyword argument 'proxy_mode'
```

* **What is the motivation / use case for changing the behavior?**

Deps:
```
install_requires = [
    'six',
    'cheroot>=5.2.0,!=5.8.0',
    'portend>=2.1.1',
]

# cheroot < 5.8.0
class HTTPRequest(object):
    def __init__(self, server, conn):

# cheroot >= 5.8.0
class HTTPRequest(object):
    def __init__(self, server, conn, proxy_mode=False, strict_mode=True):
```
cheroot version should >= 5.8.0

* **Please tell us about your environment:**
```log
python version: 2.7.13
cherroot version: cheroot-5.4.0
cherrypy version: 11.0.1.dev70+g1b979c3e
```

**Comment by webknjaz** [comment]
Thanks for report @time-river! I'll think of a better way to handle this dependencies diversity.

@jaraco do you think it's okay to change requirements to `>= 5.8.1` or pass missing args conditionally, depending on Cheroot version available?

**Comment by webknjaz** [comment]
@time-river I'd like to keep this open until it's fixed.

**Comment by jaraco** [comment]
@webknjaz I'm perfectly fine with CherryPy being as strict as necessary about the minimum cheroot required.

**Comment by webknjaz** [comment]
@jaraco great, I'll apply the restriction then.

P.S. Given that [the situation with nginx reverse proxy has been solved on Gitter](https://gitter.im/cherrypy/cherrypy?at=599428c0614889d47553541b) I'm going to remove [this compatibility layer](https://github.com/cherrypy/cherrypy/commit/c87bc9f73740dfe35e4d2ca9082dccb6278bdc53#diff-374eff2e4f53210da8f97f72e832e5d5R27) along with invalid tests, which assume that sending absolute URIs in request line is okay.
