### ISSUE TITLE
Error executing py code in 'Give us a rest' tutorial 

### ISSUE THREAD

**Issue by hungapl** [cherrypy/cherrypy#1629]
#
* **I'm submitting a ...**
bug report

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Error during execution

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
Created py file following tutorial 'http://docs.cherrypy.org/en/latest/tutorials.html#tutorial-7-give-us-a-rest'
Used command "python tut07.py" to execute
Encountered error:
```python
Traceback (most recent call last):
  File "/home/hungap/development/machinelearning/python/examples/cherrypy-rest-example.py", line 35, in <module>
    cherrypy.quickstart(StringGeneratorWebService(), '/', conf)
TypeError: expose_() missing 1 required positional argument: 'func'

```

* **What is the expected behavior?**
Server will start running

* **What is the motivation / use case for changing the behavior?**
Correcting the tutorial

* **Please tell us about your environment:**

- Python version: 3.6.1
- OS: Ubuntu 16.04
- Cherrypy 3.8.0

**Comment by hungapl** [comment]
I just checked the Cherrypy I have locally is pretty dated (the latest version is 11.0), it seems the Anaconda 4 channel is only providing version 3.8.0.  After updating to the latest cherrypy, the python code runs fine. 
 Apologies for this, I will close this issue.

**Comment by webknjaz** [comment]
No worries, have fun exploring CherryPy :)

**Comment by hungapl** [comment]
It is working really well.  This is just what I needed and with very little coding required as well, many thanks!
