### ISSUE TITLE
cherrypy.engine doesn't remove subscribed events on shutdown/exit

### ISSUE THREAD

**Issue by danlamanna** [cherrypy/cherrypy#1631]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
When shutting down CherryPy and restarting it, the listeners in `cherrypy.engine` persist.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
Run the following snippet of code:
```python
import cherrypy

class Root(object):
    @cherrypy.expose
    def index(self):
        return "hello world"

def print_a():
    print('a')

def print_b():
    print('b')

cherrypy.server.unsubscribe()
cherrypy.tree.mount(Root(), '/')
cherrypy.engine.subscribe('start', print_a)
cherrypy.engine.start()
cherrypy.engine.stop()
cherrypy.engine.exit()

cherrypy.server.unsubscribe()
cherrypy.tree.mount(Root(), '/')
cherrypy.engine.subscribe('start', print_b)
cherrypy.engine.start()
cherrypy.engine.stop()
cherrypy.engine.exit()
```

Note that when viewing the output, the second time CherryPy starts it prints both a and b.

* **What is the expected behavior?**
The second server start should only print b.

* **What is the motivation / use case for changing the behavior?**
Providing a test environment which doesn't require an individual process for each test.

* **Please tell us about your environment:**

- Python version: 2.7.14
- OS: Arch Linux Kernel 4.12.13

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

Perhaps there is a shorthand for making the Bus clean up after itself on shutdown, but it wasn't immediately obvious to me.

**Comment by webknjaz** [comment]
The behavior is not a bug, if you subscribed *before* bus `start()`, why do you think `stop()` should do cleanup?

Feel free to unsubscribe manually:
```python
cherrypy.engine.unsubscribe('start', print_a)
```

PR implementing cleanup is welcome, it shouldn't be hard to iterate through listeners and unsubscribe them: https://github.com/cherrypy/cherrypy/blob/master/cherrypy/process/wspbus.py#L194

I'm going to guess that it would be enough to reset `_priorities` and `listeners` properties. But of course I'll require tests as a part of PR.

**Comment by sahansk2** [comment]
Hello, may I take on this issue?

**Comment by jaraco** [comment]
I believe it's a design intention that `cherrypy.engine` be a convenient global variable that represents the one and only engine that most users will use. Therefore, the expectation you report wasn't considered essential for the current design.

That said, I can think of a few ways to help meet the expectation you've described:

> Providing a test environment which doesn't require an individual process for each test.

Here, I can imagine meeting the goal in more than one way:

- Have an engine automatically reset on certain events, as is expected above. I'm not exactly clear though what the event is. Is it the `engine.exit()` or the next `subscribe()` or maybe something else?
- Expect that for the use case, it's the caller's responsibility to tear down, reset, or replace the engine when necessary.
- Provide a function or method to reset the engine (but the caller still needs to call it on demand).

The best approach probably hinges mainly on:

> I'm going to guess that it would be enough to reset `_priorities` and `listeners` properties. But of course I'll require tests as a part of PR.

Let's figure out exactly what it would take to support multiple engines or resetting the main engine. Let's also ponder the tradeoffs that might happen if a single engine is shared in concurrent processing (e.g. threads, coroutines).

Sahan, thanks for offering to take it on. Yes, please explore the above concerns, evaluate the implementation, and propose a solution or solutions with tradeoffs. Good luck!
