### ISSUE TITLE
macOS job failing

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1655]
With the tag of CherryPy 11.1, the macOS tests ran, but the [Python 3.6 cheroot master test failed](https://travis-ci.org/cherrypy/cherrypy/jobs/294318580), and it's not clear to me why.

**Comment by webknjaz** [comment]
@jaraco this test was failing earlier as well (see cron runs @ Travis CI)

**Comment by webknjaz** [comment]
@jaraco do you think this is still relevant?

**Comment by jaraco** [comment]
I've lost track of this issue. We can revisit as time permits.
