### ISSUE TITLE
Can't set request.dispatch in _cp_config

### ISSUE THREAD

**Issue by romme** [cherrypy/cherrypy#1663]
Using cherrypy version 12.0.1, getting an exception which shows that MethodDispatches is not being used with this code.

```python
class Root:
	def __init__(self):
		self.helloworld = Helloworld()

@cherrypy.expose
class Helloworld:
	_cp_config = {
		'request.dispatch': cherrypy.dispatch.MethodDispatcher()
	}
	def GET(self):
		return 'hello world'
```

**Comment by webknjaz** [comment]
I'd say it's probably because the dispatcher is already selected by the time _cp_config is assigned.

@jaraco what would you suggest?

**Comment by jaraco** [comment]
The code already has [a comment](https://github.com/cherrypy/cherrypy/blob/34a72d557252e196826a364843de90fad066d263/cherrypy/_cprequest.py#L751-L753) that indicates this limitation. I have a docs update that more publicly documents this limitation.
