### ISSUE TITLE
Support wsgi.input_terminated flag

### ISSUE THREAD

**Issue by davidism** [cherrypy/cherrypy#1664]
(Assuming CherryPy supports chunked transfer encoding, I'm not directly familiar with this WSGI server / client.) Unfortunately the WSGI spec has no support for it. A standard was proposed by @mitsuhiko here: https://gist.github.com/mitsuhiko/5721547. If the WSGI server supports streams without a content length, it should set `environ['wsgi.input_terminated'] = True`. If a WSGI client sees this flag, it can ignore the content length and read the stream as-is. Other servers and clients are starting to support this.

**Comment by webknjaz** [comment]
@davidism CherryPy already ignores Content-Length in case of chunked transfer encoding: https://github.com/cherrypy/cherrypy/blob/9d95d40/cherrypy/_cpreqbody.py#L449

Also, the whole WSGI/HTTP layer has been moved to separate repo Cheroot a while ago. So the issue looks related to that project, not CherryPy itself.

@jaraco do you have any insights on this?

**Comment by webknjaz** [comment]
Ref Pylons/webob#278
Ref unbit/uwsgi#1428

**Comment by davidism** [comment]
The idea is for the server to be able to communicate to the client that the input is already terminated. So if someone wants to use the CherryPy WSGI server for their Flask app (an example I come across occasionally), Flask (Werkzeug) knows it can safely read the stream even though there's no content length.

It looks like CherryPy assumes the WSGI server will terminate input correctly, but this isn't the case for all servers. This proposal gives us a way for the server to explicitly state that it is safe to read the stream without a length, instead of the client needing to make assumptions.

In CherryPy's case, if cheroot handles reading chunked encoding, it should set `wsgi.input_terminated = True`. Then in CherryPy instead of looking at `Transfer-Encoding`, look at `wsgi.input_terminated`.

**Comment by webknjaz** [comment]
@davidism Does cherrypy/cheroot#66 look okay to you?
