### ISSUE TITLE
Allow namespace packages in dependencies

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1673]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

In #1671, we learned that there are users of CherryPy installing the package to environments that do not support namespace packages. As a result, we've removed those offending dependencies and are explicitly supporting those environments, meaning CherryPy cannot accept namespace packages for dependencies.

* **What is the expected behavior?**

CherryPy wishes to be able to adopt dependencies even on packages that use namespaces.

* **What is the motivation / use case for changing the behavior?**

Python explicitly presents namespace packages; there is useful functionality published in namespace packages; the real defect lies in the environments that can't support these packages.

Let's set a deadline and after which a new backward-incompatible release will restore support for these dependencies.

**Comment by webknjaz** [comment]
Could you please explicitly specify what are these environments and what is the underlying reason for them to not support such packages?

**Comment by jaraco** [comment]
The environments thusfar implicated are Pex, Celery, and py2exe. I do strongly encourage CherryPy users in those environments to file tickets with those projects upstream to add support for namespace packages to their product in order to avoid blocking the use of CherryPy when this change lands.

**Comment by webknjaz** [comment]
Well, I was talking about what prevents them from supporting namespaced packages.

**Comment by webknjaz** [comment]
@Safihre I think your project might be affected

**Comment by jaraco** [comment]
> what prevents them from supporting namespace packages?

jaraco/jaraco.classes#2 reports one error in celery and a [solution is described later](https://github.com/jaraco/jaraco.classes/issues/2#issuecomment-352273983).

That ticket links also to pantsbuild/pex#393, which appears to have been fixed.

The py2exe error is indicated in jaraco/jaraco.classes#3, where I'm still investigating, but some indications are that py2exe may be able to support namespace packages if those packages are able to declare/incorporate their support for py2exe.

**Comment by jaraco** [comment]
The upcoming CherryPy 17 release resolves this issue. Incompatible environments should pin to 'Cherrypy<17'.
