### ISSUE TITLE
Tests take too long to run

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1674]
![image](https://user-images.githubusercontent.com/308610/34082396-75076fda-e32b-11e7-9696-0cdbae5562da.png)

In my opinion, CI tests for releasing a pure-Python app like CherryPy should take less than 5 minutes, and definitely not more than 30.

**Comment by webknjaz** [comment]
@jaraco would it help if I add some conditional to stages/jobs, so it would run less of them? just the most important ones

**Comment by jaraco** [comment]
I'm beginning to think we should limit the macOS tests to just one run (maybe latest Python), just to provide some indication of whether or not the macOS factor is relevant, and even make the release not dependent on those tests, so they provide information like the Appveyor Windows tests, but don't block the releases.

**Comment by webknjaz** [comment]
@jaraco I've applied the condition to run long-run stages on cron or when triggered manually. Hope this helps.

**Comment by webknjaz** [comment]
(They'll run periodically, not affecting releases and normal pushes)

**Comment by webknjaz** [comment]
https://travis-ci.org/cherrypy/cherrypy/builds/321930756 (Ran for 5 min 28 sec, Total time 15 min 47 sec)
