### ISSUE TITLE
Autoreloader error '_constant_time' has no function, constant or global variable named '__loader__'

### ISSUE THREAD

**Issue by murilobr** [cherrypy/cherrypy#1675]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
On start cherrypy server its showing a log error message on Autoloader

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
```
ENGINE Error in background task thread function <bound method Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x10ffe99b0>>.
AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__loader__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 518, in run
    self.function(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 650, in run
    for filename in self.sysfiles() | self.files:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 634, in sysfiles
    hasattr(m, '__loader__') and
SystemError: <built-in function hasattr> returned a result with an error set

Exception in thread Autoreloader:
AttributeError: cffi library '_constant_time' has no function, constant or global variable named '__loader__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 518, in run
    self.function(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 650, in run
    for filename in self.sysfiles() | self.files:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 634, in sysfiles
    hasattr(m, '__loader__') and
SystemError: <built-in function hasattr> returned a result with an error set

[18/Dec/2017:09:46:39] ENGINE Started monitor thread 'Session cleanup'.
```

* **What is the expected behavior?**
No log error message

* **What is the motivation / use case for changing the behavior?**
This error prevents autoreloader reload the server on changes

* **Please tell us about your environment:**

- Cheroot version: 6.0.0
- CherryPy version: 13.0.0
- Python version: 3.6.2
- OS: OSX 10.13.2
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
None

**Comment by webknjaz** [comment]
Does this problem exist for previous versions of CherryPy/cheroot? Do you use official build of Python? Do you have any CFFI lib installed in your env? What if you try using sdist instead of a wheel?

**Comment by murilobr** [comment]
@webknjaz 

Does this problem exist for previous versions of CherryPy/cheroot?
No, but if I downgrade to previous versions (12.0.2/5.11.0) the problem persists.

Do you use official build of Python?
No, I'm using brew installation

Do you have any CFFI lib installed in your env?
Nothing installed by me.
My pip requirements are:
cherrypy
tenjin
pymongo
pytz
newrelic
pytest
Pillow
httpagentparser
requests
boto3
unidecode

What if you try using sdist instead of a wheel?
Sorry, I don't know what do you mean.
What I understood by sdist and wheel is that they are package formats (if I'm not wrong), I'm using pip to install the packages.

**Comment by webknjaz** [comment]
Could you please provide steps to reproduce this?

Regarding CFFI, I'd say cherrypy/cheroot both have pure-Python codebases. The only thing I can guess is that there might be some internal call to OS-specific C-extension in stdlib or one of the packages in your env.

We need to find out where does this `_constant_time` module come from.

**Comment by webknjaz** [comment]
Alright, it's likely one of the modules you have in your env doesn't support `hasattr()` correctly.

You could try some breakpoint [here](https://github.com/cherrypy/cherrypy/blob/master/cherrypy/process/plugins.py#L634) to tell us that module's name.

Meanwhile, I think, we could rewrite that piece of code using try/except.

**Comment by webknjaz** [comment]
Oh, and there's [some known issues with `hasattr`](https://hynek.me/articles/hasattr/), which I'd prefer to eliminate as well.

**Comment by webknjaz** [comment]
@murilobr hopefully f466ed0 will fix this. Feel free to reopen this issue if needed :)

**Comment by gramster** [comment]
This started happening for me. Things were working yesterday; today I added some code and I get this. The new code added dependencies on `requests` and `urllib`. AFAICT the problem is coming from the cryptography package which is a dependency of requests, specifically a module within that called _constant_time.lib.

The change referenced above fixes it.

**Comment by webknjaz** [comment]
@gramster is this reproducible with code from git master?

**Comment by webknjaz** [comment]
Oh, I missed the last sentence about fix:)
