### ISSUE TITLE
cannot import name parse_http_list

### ISSUE THREAD

**Issue by metaMMA** [cherrypy/cherrypy#1685]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
when I run a demo using python `python -m cherrypy.tutorial.tut01_helloworld` I receive the error in the title.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
Open a terminal, type 
```
git clone https://github.com/cherrypy/cherrypy.git
tar -xzf CherryPy-13.1.0.tar.gz
cd CherryPy-13.1.0
cp cherrypy/tutorial/tut01_helloworld.py .
python tut01_helloworld.py 
```
The following is returned:
```
Traceback (most recent call last):
  File "tut01_helloworld.py", line 10, in <module>
    import cherrypy
  File "/home/user/Documents/CherryPy-13.1.0/cherrypy/__init__.py", line 73, in <module>
    from ._cptools import default_toolbox as tools, Tool
  File "/home/user/Documents/CherryPy-13.1.0/cherrypy/_cptools.py", line 31, in <module>
    from cherrypy.lib import cptools, encoding, auth, static, jsontools
  File "/home/user/Documents/CherryPy-13.1.0/cherrypy/lib/auth.py", line 2, in <module>
    from cherrypy.lib import httpauth
  File "/home/user/Documents/CherryPy-13.1.0/cherrypy/lib/httpauth.py", line 27, in <module>
    from six.moves.urllib.request import parse_http_list, parse_keqv_list
ImportError: cannot import name parse_http_list
```

* **What is the expected behavior?**
The tutorial/demo to run with no errors.

* **What is the motivation / use case for changing the behavior?**
I need to include the CherryPy library in a software project and it needs to work by referencing the CherryPy library instead of requiring users to manually install. (See [PlexPy](https://github.com/JonnyWong16/plexpy) project as an example of using CherryPy without requiring user installation)

* **Please tell us about your environment:**
- Base system: Debian GNU/Linux 9 (stretch) 64-bit
- DE: Gnome 3.22.2
- Cheroot version: X.X.X UNKNOWN - NON-EXISTENT
- CherryPy version: 13.1.0
- Python version: 3.5.3 and 2.7.13
- Browser: Firefox ESR 52.5.2 (64-bit)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
???

**Comment by webknjaz** [comment]
You have to install requirements. In your case it's six, but there's others.  67d60277785644d848e0d1193d8663148739f940

**Comment by webknjaz** [comment]
You could run smth like `pip install -t lib cherrypy` during build in CI to vendor all deps.

**Comment by metaMMA** [comment]
Thanks for the reply. I guess I was confused, because I looked at the documentation first here:
[http://docs.cherrypy.org/en/latest/install.html#requirements](http://docs.cherrypy.org/en/latest/install.html#requirements)
and the first line states 
```
CherryPy does not have any mandatory requirements. 
```
I would like to create my software project so that the end user does not need to run additional installations (i.e. include the necessary libraries with my software). So, I would need to include the `six` library. Because the dependencies are not listed in the link I posted above, is there a list of the other requirements that you mentioned I would need that can be somewhere else online?

**Comment by webknjaz** [comment]
@metaMMA 

Oh.. It's a bit outdated doc section.
See, we've started using `six` to simplify supporting Python 2 and Python 3. A bit later we've factored out WSGI server into separate project Cheroot, so that ones to only require WSGI could not depend on the whole CherryPy distribution. And also we've decided to rely on third-party dependencies, because vendoring them makes it harder to get updates/fixes from them etc.

Just so you know, [`setup.py`](https://github.com/cherrypy/cherrypy/blob/e1380d5/setup.py#L56-L95) (and `setup.cfg`) is a standard place for dependencies in distribution packages in Python world.

Although you could look at that module and include dependencies, those may have other recursive dependencies etc.
I *strongly recommend* going with pip method in CI during build. So that you could download and vendor everything on build stage when packing your app.

Example downloading wheels or tarballs with sources:
```
$ pip download -d . cherrypy
Collecting cherrypy
  Using cached CherryPy-13.1.0-py2.py3-none-any.whl
  Saved ./CherryPy-13.1.0-py2.py3-none-any.whl
Collecting portend>=2.1.1 (from cherrypy)
  Using cached portend-2.2-py2.py3-none-any.whl
  Saved ./portend-2.2-py2.py3-none-any.whl
Collecting cheroot>=5.9.1 (from cherrypy)
  Using cached cheroot-6.0.0-py2.py3-none-any.whl
  Saved ./cheroot-6.0.0-py2.py3-none-any.whl
Collecting six>=1.11.0 (from cherrypy)
  Using cached six-1.11.0-py2.py3-none-any.whl
  Saved ./six-1.11.0-py2.py3-none-any.whl
Collecting tempora>=1.8 (from portend>=2.1.1->cherrypy)
  Using cached tempora-1.10-py2.py3-none-any.whl
  Saved ./tempora-1.10-py2.py3-none-any.whl
Collecting more-itertools>=2.6 (from cheroot>=5.9.1->cherrypy)
  Using cached more_itertools-4.0.1-py3-none-any.whl
  Saved ./more_itertools-4.0.1-py3-none-any.whl
Collecting pytz (from tempora>=1.8->portend>=2.1.1->cherrypy)
  Using cached pytz-2017.3-py2.py3-none-any.whl
  Saved ./pytz-2017.3-py2.py3-none-any.whl
Successfully downloaded cherrypy portend cheroot six tempora more-itertools pytz
$ l
total 1.1M
-rw-r--r-- 1 wk wk  61K Jan 12 23:43 cheroot-6.0.0-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk 421K Jan 12 23:43 CherryPy-13.1.0-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk  44K Jan 12 23:43 more_itertools-4.0.1-py3-none-any.whl
-rw-r--r-- 1 wk wk 6.0K Jan 12 23:43 portend-2.2-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk 500K Jan 12 23:43 pytz-2017.3-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk  11K Jan 12 23:43 six-1.11.0-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk  14K Jan 12 23:43 tempora-1.10-py2.py3-none-any.whl
$ pip download -d . --no-binary :all: cherrypy
Collecting cherrypy
  Downloading CherryPy-13.1.0.tar.gz (687kB)
    100% |████████████████████████████████| 696kB 520kB/s
  Saved ./CherryPy-13.1.0.tar.gz
Collecting six>=1.11.0 (from cherrypy)
  Downloading six-1.11.0.tar.gz
  Saved ./six-1.11.0.tar.gz
Collecting cheroot>=5.9.1 (from cherrypy)
  Downloading cheroot-6.0.0.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 828kB/s
  Saved ./cheroot-6.0.0.tar.gz
Collecting portend>=2.1.1 (from cherrypy)
  Downloading portend-2.2.tar.gz
  Saved ./portend-2.2.tar.gz
Collecting more_itertools>=2.6 (from cheroot>=5.9.1->cherrypy)
  Downloading more-itertools-4.0.1.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 491kB/s
  Saved ./more-itertools-4.0.1.tar.gz
Collecting tempora>=1.8 (from portend>=2.1.1->cherrypy)
  Downloading tempora-1.10.tar.gz
  Saved ./tempora-1.10.tar.gz
Collecting pytz (from tempora>=1.8->portend>=2.1.1->cherrypy)
  Downloading pytz-2017.3.zip (527kB)
    100% |████████████████████████████████| 532kB 280kB/s
  Saved ./pytz-2017.3.zip
Successfully downloaded cherrypy six cheroot portend more-itertools tempora pytz
$ l
total 2.4M
-rw-r--r-- 1 wk wk  61K Jan 12 23:43 cheroot-6.0.0-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk  62K Jan 12 23:44 cheroot-6.0.0.tar.gz
-rw-r--r-- 1 wk wk 421K Jan 12 23:43 CherryPy-13.1.0-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk 672K Jan 12 23:44 CherryPy-13.1.0.tar.gz
-rw-r--r-- 1 wk wk  44K Jan 12 23:43 more_itertools-4.0.1-py3-none-any.whl
-rw-r--r-- 1 wk wk  47K Jan 12 23:44 more-itertools-4.0.1.tar.gz
-rw-r--r-- 1 wk wk 6.0K Jan 12 23:43 portend-2.2-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk 7.8K Jan 12 23:44 portend-2.2.tar.gz
-rw-r--r-- 1 wk wk 500K Jan 12 23:43 pytz-2017.3-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk 516K Jan 12 23:44 pytz-2017.3.zip
-rw-r--r-- 1 wk wk  11K Jan 12 23:43 six-1.11.0-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk  30K Jan 12 23:44 six-1.11.0.tar.gz
-rw-r--r-- 1 wk wk  14K Jan 12 23:43 tempora-1.10-py2.py3-none-any.whl
-rw-r--r-- 1 wk wk  14K Jan 12 23:44 tempora-1.10.tar.gz
```

Example installing them into certain dir (like vendor dir):
```
$ pip install -t . cherrypy
Collecting cherrypy
  Using cached CherryPy-13.1.0-py2.py3-none-any.whl
Collecting cheroot>=5.9.1 (from cherrypy)
  Using cached cheroot-6.0.0-py2.py3-none-any.whl
Collecting portend>=2.1.1 (from cherrypy)
  Using cached portend-2.2-py2.py3-none-any.whl
Collecting six>=1.11.0 (from cherrypy)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting more-itertools>=2.6 (from cheroot>=5.9.1->cherrypy)
  Using cached more_itertools-4.0.1-py3-none-any.whl
Collecting tempora>=1.8 (from portend>=2.1.1->cherrypy)
  Using cached tempora-1.10-py2.py3-none-any.whl
Collecting pytz (from tempora>=1.8->portend>=2.1.1->cherrypy)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Installing collected packages: six, more-itertools, cheroot, pytz, tempora, portend, cherrypy
Successfully installed cheroot-6.0.0 cherrypy-13.1.0 more-itertools-4.0.1 portend-2.2 pytz-2017.3 six-1.11.0 tempora-1.10

$ l
total 92K
drwxr-xr-x 6 wk wk 4.0K Jan 12 23:48 cheroot/
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 cheroot-6.0.0.dist-info/
drwxr-xr-x 8 wk wk 4.0K Jan 12 23:48 cherrypy/
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 CherryPy-13.1.0.dist-info/
drwxr-xr-x 4 wk wk 4.0K Jan 12 23:48 more_itertools/
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 more_itertools-4.0.1.dist-info/
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 portend-2.2.dist-info/
-rw-r--r-- 1 wk wk 5.0K Jan 12 23:48 portend.py
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 __pycache__/
drwxr-xr-x 4 wk wk 4.0K Jan 12 23:48 pytz/
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 pytz-2017.3.dist-info/
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 six-1.11.0.dist-info/
-rw-r--r-- 1 wk wk  31K Jan 12 23:48 six.py
drwxr-xr-x 4 wk wk 4.0K Jan 12 23:48 tempora/
drwxr-xr-x 2 wk wk 4.0K Jan 12 23:48 tempora-1.10.dist-info/
```

Also, you'll be able to easily upgrade to newer versions this way.

**Comment by metaMMA** [comment]
@webknjaz I am so thankful for you taking the time to explain all of that. I am completely new to programming and just learned python to create my program. 

Are you saying that I can create a OS-agnostic `setup.py` file that will automatically download all the dependencies that my software needs? If so, do you have any advice on where to start learning? Sorry to spam your `issues` page, and I really appreciate the help!

**Comment by webknjaz** [comment]
@metaMMA Sure, you can learn about distributions at: https://packaging.python.org
Also, note that all modern python installations are being shipped with pip and setuptools, so you don't have to vendor dependencies, but rather declare them in setup.py and pip will fetch them from pypi.org and install them into your current environment (you know about virtualenv, right?).
That said, if you craft your own distribution package, you can freely upload/publish it to PYPI and others will be able to install them along with dependencies with a single command via pip.

But bear in mind that depending on your needs you might want to use some other packaging method. I think, you'll figure that out once you learn more:)
