### ISSUE TITLE
[TODO: remove in v15] Duplicate HTTP Auth Basic and HTTP Auth Digest tools have to be merged

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cherrypy#1688]
While working on #1680 I realized that there's functional duplication in tools we provide by default.
There's [`auth_basic`, `auth_digest`](https://github.com/cherrypy/cherrypy/blame/880f946/cherrypy/_cptools.py#L538-L539) and also [`basic_auth`, `digest_auth`](https://github.com/cherrypy/cherrypy/blame/880f946/cherrypy/_cptools.py#L529-L530).
They also have duplicate tests spread across 3-5 test modules, which has to be handled as well.

#913 (0704e6ca8c3e5a6014ecc88e3265854faf9fe764) and as mentioned in #914:
> Note that with this new auth_digest and the auth_basic in ticket #913, the files lib/auth.py and lib/httpauth.py can be completely deprecated.

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository
- [X] [WAT](http://i0.kym-cdn.com/photos/images/newsfeed/000/173/580/Wat.jpg?1315930588)

* **Do you want to request a *feature* or report a *bug*?**
Deprecated tool removal.

* **What is the current behavior?**
There's ambiguity making end-users confused about which tool to use.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
See src

* **What is the expected behavior?**
Just one well-documented and well-tested implementation for each of Basic/Digest HTTP Auth methods.

* **What is the motivation / use case for changing the behavior?**
[There should be one-- and preferably only one --obvious way to do it. (Zen of Python)](https://zen-of-python.info/there-should-be-one-and-preferably-only-one-obvious-way-to-do-it.html#13)

* **Please tell us about your environment:**

- Cheroot version: —
- CherryPy version: 3.2.0‒13.1.0+
- Python version: —
- OS: —
- Browser: —

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
—

**Comment by webknjaz** [comment]
@jaraco we've forgotten to remove this thing. Maybe we need some label for deprecations to check before doing major releases?

**Comment by webknjaz** [comment]
The only thing I worry about is that new tool runs on `before_handler`, while the old one was used to be running on `on_start_resource`.

**Comment by jaraco** [comment]
At YouGov, we have some applications that still use the deprecated handlers. I'm not sure we've given enough time for deprecation warnings to be noticed and addressed.

Also, it's not that we had forgotten to remove it; we just hadn't yet removed it. I don't think there's any prescribed schedule for removing deprecated functionality.

**Comment by webknjaz** [comment]
Well, I removed those in master.
