### ISSUE TITLE
TypeError: os_exit_noop() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by sebastian-philipp** [cherrypy/cherrypy#1691]
* **I'm submitting a ...**
- [X] bug report

* **What is the current behavior?**
I got this when running tox in a Python 3.5 environment:

```
Traceback (most recent call last):
  File "/home/user/ceph/src/pybind/mgr/dashboard_v2/.tox/py3/lib/python3.5/site-packages/cherrypy/process/wspbus.py", line 259, in _clean_exit
    self.exit()
  File "/home/user/ceph/src/pybind/mgr/dashboard_v2/.tox/py3/lib/python3.5/site-packages/cherrypy/process/wspbus.py", line 303, in exit
    os._exit(EX_SOFTWARE)
TypeError: os_exit_noop() takes 0 positional arguments but 1 was given
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.

```
git clone https://github.com/openattic/ceph
cd ceph/src/pybind/mgr/dashboard_v2
tox
```

* **Please tell us about your environment:**

- Cheroot version: ??
- CherryPy version: 13.1.0
- Python version: 3.5.2
- OS: Ubuntu 16.04

**Comment by webknjaz** [comment]
Hi, I believe you are running app in the environment with improperly monkey patched `os._exit`. Probably the app you use does this. It has nothing to do with CherryPy.

**Comment by sebastian-philipp** [comment]
Thanks! Exactly right.
