### ISSUE TITLE
test_4_AutoReload failing on Python 3.7.

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1693]
As seen in [this job](https://travis-ci.org/cherrypy/cherrypy/jobs/343489659) and others, there is one test consistently failing on Python 3.7. It's hard to find because the log is 43k lines long!

But here it is:

```


â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€• ServerStateTests.test_4_Autoreload â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•â€•



self = <cherrypy.test.test_states.ServerStateTests testMethod=test_4_Autoreload>



[1m    def test_4_Autoreload(self):[0m

[1m        # If test_3 has not been executed, the server won't be stopped,[0m

[1m        # so we'll have to do it.[0m

[1m        if engine.state != engine.states.EXITING:[0m

[1m            engine.exit()[0m

[1m    [0m

[1m        # Start the demo script in a new process[0m

[1m        p = helper.CPProcess(ssl=(self.scheme.lower() == 'https'))[0m

[1m        p.write_conf(extra='test_case_name: "test_4_Autoreload"')[0m

[1m        p.start(imports='cherrypy.test._test_states_demo')[0m

[1m        try:[0m

[1m            self.getPage('/start')[0m

[1m            start = float(self.body)[0m

[1m    [0m

[1m            # Give the autoreloader time to cache the file time.[0m

[1m            time.sleep(2)[0m

[1m    [0m

[1m            # Touch the file[0m

[1m            os.utime(os.path.join(thisdir, '_test_states_demo.py'), None)[0m

[1m    [0m

[1m            # Give the autoreloader time to re-exec the process[0m

[1m            time.sleep(2)[0m

[1m            host = cherrypy.server.socket_host[0m

[1m            port = cherrypy.server.socket_port[0m

[1m            portend.occupied(host, port, timeout=5)[0m

[1m    [0m

[1m            self.getPage('/start')[0m

[1m            if not (float(self.body) > start):[0m

[1m                raise AssertionError('start time %s not greater than %s' %[0m

[1m>                                    (float(self.body), start))[0m

[1m[31mE                                    AssertionError: start time 1519065695.762757 not greater than 1519065695.762757[0m



[1m[31mcherrypy/test/test_states.py[0m:254: AssertionError





 [36mcherrypy/test/test_states.py[0m::ServerStateTests.test_4_Autoreload[0m [31mâ¨¯[0m[31m77% [0m[40m[31mâ–ˆ[0m[40m[32mâ–ˆ[0m[40m[32mâ–ˆ[0m[40m[32mâ–ˆ[0m[40m[32mâ–ˆ[0m[40m[32mâ–ˆ[0m[40m[32mâ–ˆ[0m[40m[31mâ–Š[0m[40m[31m  [0m


```

Apologies for the mess, but that's what I was able to get out of the raw log.

**Comment by webknjaz** [comment]
> AssertionError: start time 1519065695.762757 not greater than 1519065695.762757

So that's it

**Comment by webknjaz** [comment]
I think, this test was flaky before

**Comment by jaraco** [comment]
> this test was flaky before

Yes, perhaps, but it seems to be failing more consistently on Python 3.7. I only checked a few jobs, but I did see this failure a couple of times.

Moreover, I reviewed the code for this test and it's putting in a `sleep(2)` for the test, yet the file modification time is identical (to the microsecond), so that leads me to believe this failing test is revealing an actual defect in the Autoreload functionality on Python 3.7.

As the beta is now out, I'll be getting Python 3.7 on my system soon and I can replicate the issue locally and I hope isolate the cause.

**Comment by jaraco** [comment]
> this test was flaky before

When you say it was flaky before, would it fail with this error message, @webknjaz ?

**Comment by jaraco** [comment]
The test [passes for me on my mac](https://gist.github.com/21641e53b7af3950291742084e9c5fce) with 3.7.0b1. Therefore, the issue is probably ~isolated to Linux~ (erm, ~macOS~) or to Travis or to another build of Python 3.7 or ~maybe it's intermittent~.

**Comment by jaraco** [comment]
It passed several times in a row, so I don't think it's intermittent.

**Comment by jaraco** [comment]
Oh, wow, I'm just now noticing the failure is on the macOS test for 3.7-dev. The test on Linux and Python nightly was passing.

**Comment by webknjaz** [comment]
I don't remember details, just that it seems familiar.

**Comment by jaraco** [comment]
In 726c23b9, I've limited the xfail to a very specific set of circumstances that bring about this failure. Since I can't replicate it locally, I'm going to assume it's a temporary condition that will correct itself. If it doesn't, we can revisit in the future.
