### ISSUE TITLE
pywin32 for python 3.4 is no longer supported (pywin32>=223)

### ISSUE THREAD

**Issue by jrivera294** [cherrypy/cherrypy#1700]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Cherrypy can't be installed on a Windows Python 3.4 environment. Pywin32 dependency is set to > 223, and 223 version doesn't exists for Python 3.4, they no longer support it.

Error installing cherrypy:
`Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32; sys_platform == "win32"->cherrypy) (from versions: 221)
No matching distribution found for pywin32>=223 (from pypiwin32; sys_platform == "win32"->cherrypy)
`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.
pip install cherrypy

* **What is the expected behavior?**
Successful install

* **What is the motivation / use case for changing the behavior?**
Support Cherrypy on python 3.4 (Windows)

* **Please tell us about your environment:**

- Cheroot version: 5.9.1
- CherryPy version: 14.0.0
- Python version: 3.4.4
- OS: Windows 7 32 bits
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jrivera294** [comment]
I managed to build my own pywin32 223 wheel, details here: https://github.com/mhammond/pywin32/issues/1172

**Comment by webknjaz** [comment]
The problem is that there's no old version of pywin32, which supports Python 3.4. Let's see if maintainers can publish it.

**Comment by webknjaz** [comment]
I think, this might become a solution: https://github.com/cherrypy/cherrypy/compare/bugfix/limit-pypywin32-ver-for-py34
I'll wait for tests at Appveyor and then merge

**Comment by jrivera294** [comment]
Perfect, it should work and avoid the issue on further relases of pywin32. Thanks!

**Comment by jrivera294** [comment]
If someone else is a bit stuck with this dependency problem:

I'm trying with a workaround until the next Cherrypy release. Basically I'm installing the cherrypy dependencies, pywin32 221 and finally installing Cherrypy with the --no-dependencies flag of pip.

```
wine pip install -r requirements/cherrypy.txt
wine pip install cherrypy==14.0.0 --no-dependencies
```

cherrypy.txt (From the install requires of cherrypy setup.py)
```
six>=1.11.0
cheroot>=5.9.1
portend>=2.1.1
pywin32==221
```

I have a working 221 wheel that I made from a exe that I found on sourceforge) but I suppose that it works with the 219 too.

**Comment by webknjaz** [comment]
You can also have `constraints.txt`:
```txt
pypiwin32==219
```

And do:
```shell
pip install -c constraints.txt cherrypy
```

**Comment by webknjaz** [comment]
have fun https://travis-ci.org/cherrypy/cherrypy/jobs/356933624 :)
https://pypi.org/project/CherryPy/14.0.1/

**Comment by jrivera294** [comment]
Perfect, everything seems to be working again :) Thanks!

**Comment by mobinalhassan** [comment]
> You can also have `constraints.txt`:
> 
> ```
> pypiwin32==219
> ```
> 
> And do:
> 
> ```shell
> pip install -c constraints.txt cherrypy
> ```

Thank you this method works perfects
