### ISSUE TITLE
Figure out where cherrypy.org domain is managed

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cherrypy#1702]
Ref: https://gitter.im/cherrypy/cherrypy?at=5ace03b47685a046389d8308

**Comment by jaraco** [comment]
CherryPy is managed at WebFaction and the [domain registrar is ovh](https://reports.internic.net/cgi/whois?whois_nic=cherrypy.org&type=domain) (https://www.ovh.com/world/). Remi Delon is the owner.
