### ISSUE TITLE
Host cherrypy.org through CloudFlare

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1703]
@webknjaz has proposed Cherrypy.org be hosted through a free CloudFlare account to give a better experience and host the site under SSL. To accomplish this, there are a few steps.

- [x] Create a CloudFlare account with some shared management.
- [x] Import the domain records as currently hosted with WebFaction to CloudFlare.
- [x] Reconfigure the cherrypy.org domain at the registrar to CloudFlare.

It's important that the CloudFlare account be under shared management such that more than one maintainer has the ability to manage the domain.

**Comment by jaraco** [comment]
Probably the first step should be to reach out to Remi and confirm he's okay with moving the DNS from WebFaction to CloudFlare.

**Comment by webknjaz** [comment]
@jaraco 
I'm getting `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` in my browser now. Could you please also this verify with yours?
According to https://support.cloudflare.com/hc/en-us/articles/200170616-Why-am-I-getting-a-SSL-mismatch-error- it might take 24 hours for this to get fixed.

**Comment by webknjaz** [comment]
I've also enabled uptime robot:
https://stats.uptimerobot.com/rkM5rfWQR
https://uptime.cherrypy.org/

**Comment by webknjaz** [comment]
Okay, so I've disabled a few toggles, waited for a while and now it works.
I'm going to start enabling them back one by one to figure out whether it was time-based or feature-toggle-dependent.

**Comment by webknjaz** [comment]
### Step 1:
Changed `Flexible` to `Full (strict)` here: https://www.cloudflare.com/a/crypto/cherrypy.org

**Comment by webknjaz** [comment]
Now, this resulted in:
```
Error 526
Invalid SSL certificate
```

**Comment by webknjaz** [comment]
### Step 2:
Changed `Full (strict)` to `Full` here: https://www.cloudflare.com/a/crypto/cherrypy.org

This means that CF will use SSL while connecting to gh-pages (and other hosts) when in proxy mode, but will not verify their certificates.

**Comment by webknjaz** [comment]
This fixed it. Now it's accessible again.

**Comment by webknjaz** [comment]
### Step 3:
Toggled `Require Modern TLS` from `Off` to `On` here: https://www.cloudflare.com/a/crypto/cherrypy.org

This should cut off clients with way outdated TLS.

**Comment by webknjaz** [comment]
Still works

**Comment by webknjaz** [comment]
### Step 4:
Toggled `TLS 1.3 BETA` from `Disabled` to `Enabled+0RTT` here: https://www.cloudflare.com/a/crypto/cherrypy.org

**Comment by jaraco** [comment]
Looks like some resources (font) aren't loading under https.

![image](https://user-images.githubusercontent.com/308610/38738522-565e866e-3f00-11e8-94b5-d91c7116c6b2.png)

![image](https://user-images.githubusercontent.com/308610/38738539-6152af0a-3f00-11e8-9475-3a90d9eef438.png)

**Comment by webknjaz** [comment]
### Step 5:
Toggled `Authenticated Origin Pulls` from `Off` to `On` here: https://www.cloudflare.com/a/crypto/cherrypy.org

**Comment by webknjaz** [comment]
@jaraco yeah, I've fixed that a couple of minutes ago.

**Comment by webknjaz** [comment]
### Step 6:
Enabled and set `HTTP Strict Transport Security (HSTS)` to:
```
Status: On
Max-Age: 0 (Disable)
Include subdomains: On
Preload: On
No-sniff: Off
```

**Comment by webknjaz** [comment]
### Step 7:
Toggled `Always use HTTPS` from `Off` to `On`.

**Comment by webknjaz** [comment]
Everything looks working now.

**Comment by webknjaz** [comment]
@jaraco 
I've `CNAME`d https://cheroot.cherrypy.org/ to cheroot.rtfd.io
Could you please wire it? Any other suggestions for cheroot docs fqdn?

**Comment by webknjaz** [comment]
### Step 8:
Toggled `Automatic HTTPS Rewrites` from `Off` to `On`.

**Comment by jaraco** [comment]
It is done. No suggestions on the fqdn, though I do see rtfd.io seems to redirect to readthedocs.org, so probably the latter is preferred.

**Comment by webknjaz** [comment]
Shortcuts for rtfd work as well, i like it more.

Next steps should be ensuring to update links in:
1. [x] dists
2. [x] repo pages
3. [x] docs

**Comment by webknjaz** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=cherrypy.org

**Comment by webknjaz** [comment]
I think this issue has been fulfilled now.

P.S. It's worth noticing that GitHub started supporting SSL for custom domains several days ago.
