### ISSUE TITLE
400 Bad Request : The request entity could not be decoded. The following charsets were attempted: ['utf-8']

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1706]
I know this issue has been posted before but still again i'm posting because i faced strange behavior.

I'm using Postman to test POST request. I set header like this:

**Content-Type: application/x-www-form-urlencoded**

I'm uploading image file, everything was working fine.
I used python 2.7 and 3.6.

But suddenly next morning i started getting this error:
```python-traceback
_Traceback (most recent call last):
  File "/opt/app-root/src/cherrypy/_cprequest.py", line 663, in respond
    self.body.process()
  File "/opt/app-root/src/cherrypy/_cpreqbody.py", line 1001, in process
    super(RequestBody, self).process()
  File "/opt/app-root/src/cherrypy/_cpreqbody.py", line 558, in process
    proc(self)
  File "/opt/app-root/src/cherrypy/_cpreqbody.py", line 173, in process_urlencoded
    "charsets were attempted: %s" % repr(entity.attempt_charsets))_
**HTTPError: (400, "The request entity could not be decoded. The following charsets were attempted: ['utf-8']")**
```
I'm sure that i didn't change anything in python code or Postman request. Then why this??
Many times i closed Postman tried again but no good result.

**Comment by webknjaz** [comment]
Well, obviously something changed. The best way to give us a clue is to fill in an issue template, which guides you through the questions we need answers for.
Without knowing env details, versions of everything, payload you sent we cannot help you except pointing out what traceback already says:
**The request entity could not be decoded using utf-8 encoding.**

**Comment by webknjaz** [comment]
Okay, after a closer look it became obvious to me that you just use wrong content type. Basically, your client is lying to server about payload of the POST HTTP request it sends.
You tell server that you send form data, while in fact you send binary payload.

Ref: https://stackoverflow.com/a/4073451/595220
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

**Solution:** use `multipart/form-data`.
