### ISSUE TITLE
Have a debian package for python 3 prefixed with python3-

### ISSUE THREAD

**Issue by mohierf** [cherrypy/cherrypy#1711]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] question about the decisions made in the repository

As recommended by the Debian policy, it may exist a *python3-cherrypy* deb installer for CherryPy, but, obviously, it does not. I expected to find a *python3-cherrypy* installable package as almost all the python libraries do (even if the libray is fully compatible python2/3).

I am using *fpm* to build the packages of my application. This excellent tool extracts the dependencies from the setup.py of the application and uses the python prefix to manage the dependencies (*python-* and *python3-*). CherryPy is the only package I am using that is not complying to this policy ...

The problem I am facing is that I must make a separate specific package for the CherryPy library, or rebuild a python3 prefixed deb from the current version of cherrypy ...

Anyway
* **What is the motivation / use case for changing the behavior?**
Complying with the debian standard packaging policy.

*Note* that I also posted a question on SO for this...

**Comment by webknjaz** [comment]
Hello @mohierf,

We only build python source and binary distribution, which we publish on PYPI.
If you want a separate deb package, you probably need to contact the maintainer of debian repository itself or package it yourself.

But honestly I don't understand why someone would want to install Python based projects via `apt` instead of `pip` with a proper virtual environment set up.

I'm closing this issue, but feel free to follow-up with additional questions if any :)

**Comment by mohierf** [comment]
Thanks for your answer. This is what I supposed but I preferred having a confirmation.

**Comment by webknjaz** [comment]
@mohierf Yeah, we never shipped other distributions in other packaging formats. This would require extra effort/resourced.

I think, if someone was willing to contribute and maintain/support this @jaraco and I might consider accepting such improvements :)
But maintaining a huge matrix of environments is rather exhausting: besides implementing the packaging and its automation itself someone would need to be able to test that in all supported environments and more importantly — troubleshoot hardly reproducible things.

Have a nice day!

**Comment by webknjaz** [comment]
// FTR:  https://stackoverflow.com/questions/50441805/debian-package-installation-for-python3

**Comment by jaraco** [comment]
I agree - it's not sustainable for projects to maintain such a matrix of support. Instead, this project, like many other Python projects, supplies releases using a community-consensus-driven process, such that downstream providers such as system package managers like Debian can reliably produce packages for their environment(s). CherryPy's responsibility should stop at presenting a repeatable installation procedure with accurate metadata, something it does present.

If there's something the project can do to facilitate the production of packages in a system package manager, such as presenting a license file, please file a ticket about that.
