### ISSUE TITLE
ModuleNotFoundError: No module named 'cherrypy'

### ISSUE THREAD

**Issue by satyadasari44** [cherrypy/cherrypy#1723]
I have installed cherrypy on python3.6.6 and python3.7.

when i run tutorial file, i'm getting error as below.

```python-traceback
Traceback (most recent call last):
  File "C:\Python36\source_code\env\Lib\site-packages\cherrypy\tutorial\tut01_helloworld.py", line 10, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'
```

**Comment by webknjaz** [comment]
How do you run that? (Are you sure you run it via Python executable, which points to the same env cherrypy is installed?)

**Comment by satyadasari44** [comment]
Tnqq for ur reply, after adding env path to path, it's working fine.

Can u please guide me how to run django on cherrypy wsgi server on Windows7.

**Comment by webknjaz** [comment]
You'll probably need to plug Cheroot into `wsgi.py` of your django app, exposing `application` callable.
https://docs.cherrypy.org/en/latest/deploy.html#wsgi-servers

**Comment by satyadasari44** [comment]
Thanks a lot for your suggestion, can you please suggest me with any sample
code available to run django on cherrypy on Windows . I tried so many but
not working.



Thanks &, Regards
SATYENDRA KUMAR DASARI

**Comment by webknjaz** [comment]
You should probably use `cheroot.wsgi.Server`, but I don't have any snippet in mind right now.

**Comment by webknjaz** [comment]
`run.py`:
```python
#! /usr/bin/env python

from cheroot.wsgi import Server as WSGIServer

from yourdjangoapp.wsgi import application

bind_addr = '0.0.0.0', 8080
WSGIServer(bind_addr, application).safe_start()
```

```bash
$ ./run.py
```
