### ISSUE TITLE
CherryPy always throws a warning when no config is set when mounting a new app

### ISSUE THREAD

**Issue by speidy** [cherrypy/cherrypy#1724]
* **I'm submitting a ...** bug report

* **Do you want to request a *feature* or report a *bug*?**
report a bug.

* **What is the current behavior?**
When running an app with empty config the following warning is thrown:
https://github.com/cherrypy/cherrypy/blob/46aa2267136763ecae8d4997b0f9bfc0e04b5176/cherrypy/_cpchecker.py#L100

As the `config` is optional, i personally don't see a reason to throw such warning.

Moreover, this warning can lead pytest tests to fail since its thrown globally.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

run your sample app from cherrypy.org:
```python
import cherrypy
	  
class HelloWorld(object):
    def index(self):
        return "Hello World!"
    index.exposed = True

cherrypy.quickstart(HelloWorld())
```

Examine its stdout output:
```bash
[27/Jul/2018:08:10:11] ENGINE Listening for SIGHUP.
[27/Jul/2018:08:10:11] ENGINE Listening for SIGTERM.
[27/Jul/2018:08:10:11] ENGINE Listening for SIGUSR1.
[27/Jul/2018:08:10:11] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.  <---------
...
```

* **What is the expected behavior?**
Shut up this warning, or at least provide an option to turn it off through config.

* **What is the motivation / use case for changing the behavior?**
1. Be consistent with CherryPy API requirements which doesn't require `config` param to be set.
2. Make my pytest tests be happy and stop crying because of this silly warning.

* **Please tell us about your environment:**

- Cheroot version: 6.3.3
- CherryPy version: 17.0.0
- Python version: 2.7.12 / 3.5.2
- OS: Ubuntu 16.04 LTS
- Browser: Firefox (not so relevant)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by speidy** [comment]
Just found out you can set it via:

```python
cherrypy.config.update({'checker.check_skipped_app_config': False})`
```

I hope you'll update your docs some day so it will mention those hidden options.

**Comment by webknjaz** [comment]
Feel free to contribute a PR :)
