### ISSUE TITLE
Update Travis runner to Xenial and Python 3.7

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1728]
In [this comment](https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442) I learned that using Xenial enables Python 3.7 support. It seems we should update our platform (a good idea in general) and test against Python 3.7 as the mainstream Python. I've done the same in my other projects by way of [jaraco/skeleton](https://github.com/jaraco/skeleton/commit/beb0e0eb774dd15e79574ace338b885101d86d4b) with good success.

Interestingly, the Travis ticket indicates they used `sudo: True`. I found I did not need to use `sudo: True` for things to work in my projects, so I recommend against it.

I'd make these changes myself, but the `.travis.yml` has grown beyond my comprehension and takes a very long time to run, so I'm going to ask @webknjaz to make the update.

**Comment by jaraco** [comment]
~~We may want to postpone this effort for now, as only a couple of days ago there was a [report that Python 3.7 support stopped working](https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-412344908).~~

Nevermind, it seems that issue was network related and was corrected.

**Comment by webknjaz** [comment]
Yes, it's about network issues. I also saw this when uploading cache to GCP, so my humble guess is that they might be in progress of moving to other cloud :)

**Comment by webknjaz** [comment]
I actually use 3.7 in Travis CI for months and it's in [Cheroot already](https://github.com/cherrypy/cheroot/blob/master/.travis.yml#L66-L70). I just didn't have time to update it everywhere :)

P.S. I'm working on a concept of a better CI configs generator in the scope of my aio-libs maintainership as well. Stay tuned :)

**Comment by webknjaz** [comment]
https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-412875612

**Comment by webknjaz** [comment]
I'd modify this issue to "Add 3.7 to all CIs". Next priority-1 should be AppVeyor and then others (experimental).

**Comment by webknjaz** [comment]
Done.
