### ISSUE TITLE
Can't get code coverage to work....

### ISSUE THREAD

**Issue by alan412** [cherrypy/cherrypy#1731]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I don't know if it is a bug or just my not knowing what I am doing.

* **What is the current behavior?**
When I try to execute covercp.py, I get the following:

```python-traceback
(venv3) Honeycrisp2018:CheckMeIn alan$ python venv3/lib/python3.6/site-packages/cherrypy/lib/covercp.py 
Traceback (most recent call last):
  File "venv3/lib/python3.6/site-packages/cherrypy/lib/covercp.py", line 391, in <module>
    serve(*tuple(sys.argv[1:]))
  File "venv3/lib/python3.6/site-packages/cherrypy/lib/covercp.py", line 377, in serve
    if coverage is None:
UnboundLocalError: local variable 'coverage' referenced before assignment
```

If I comment out lines 377 and 378 then it will start up, but I get the following on the left hand side:
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

```
Traceback (most recent call last):
  File "/Users/alan/Projects/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/Users/alan/Projects/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/Users/alan/Projects/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 264, in __call__
    ct.params['charset'] = self.find_acceptable_charset()
  File "/Users/alan/Projects/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 173, in find_acceptable_charset
    if encoder(self.default_encoding):
  File "/Users/alan/Projects/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 114, in encode_string
    for chunk in self.body:
  File "venv3/lib/python3.6/site-packages/cherrypy/lib/covercp.py", line 325, in menu
    tree = get_tree(base, exclude, self.coverage)
  File "venv3/lib/python3.6/site-packages/cherrypy/lib/covercp.py", line 280, in get_tree
    runs = coverage.data.executed_files()
AttributeError: 'CoverageData' object has no attribute 'executed_files'
```

* **What is the expected behavior?**
I would *really* like (and think would be great to have in the documentation) an example using code coverage of one of the tutorial projects.   I suspect I am just doing something not very smart.

* **What is the motivation / use case for changing the behavior?**
I would like to use code coverage to make sure my tests are covering enough of the project for a release.

* **Please tell us about your environment:**

- CherryPy version: 17.3.0
-Python 3.6.1
- Python version: 3.6.X

**Comment by webknjaz** [comment]
Hi, this module is very old and it looks like nobody tested it for a decade. Does `pytest-cov` work for you?

**Comment by alan412** [comment]
Please excuse my ignorance but how would I use that with cherrypy?

**Comment by webknjaz** [comment]
Do you use `pytest` for testing? It should be able to pick up `cov` plugin if you `pip install pytest-cov`

**Comment by alan412** [comment]
I don't now, but I am willing to try it.   anything special I have to do to
get it to work with CherryPy?

**Comment by webknjaz** [comment]
I don't yet know, but it's used in CI while testing CherryPy itself. Tell us about your experience once you try :)

**Comment by webknjaz** [comment]
This might result in a good enhancement of documentation.

**Comment by webknjaz** [comment]
cc @jaraco

**Comment by jaraco** [comment]
I don't know anything about covercp. That module clearly has bugs and it's not clear how to use it. I welcome PRs to improve that module and the documentation around how to use it. Whoever works on that will have to spend some time troubleshooting and establishing an understanding of that module and it's purpose(s).

**Comment by alan412** [comment]
Got coverage to work with pytest and --cov flag

Would you like me to write up some simple documentation showing how to do
It with one of the tutorial projects?  Then my suggestion would be to
remove covercp from the project.

**Comment by webknjaz** [comment]
@alan412 that would be lovely! The docs source is here: https://github.com/cherrypy/cherrypy/tree/master/docs

I believe that this module facilitated coverage in times of `unittest` and `nose` libs and now it's probably redundant:
https://github.com/cherrypy/cherrypy/blob/2fc78dc9af3e556829ce69d3e1311e5629200882/cherrypy/lib/covercp.py#L11
