### ISSUE TITLE
Tests fail to run on Windows

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1742]
While investigating a fix to pytest-dev/pytest-services#23, I went to run the CherryPy tests on my Windows VM, but they immediately failed thus:

```
PS C:\Users\jaraco\code\win\cherrypy> tox
python create: C:\Users\jaraco\code\win\cherrypy\.tox\python
python develop-inst: C:\Users\jaraco\code\win\cherrypy
python installed: You are using pip version 9.0.1, however version 18.0 is available.,You should consider upgrading via the 'python -m pip install --upgrade pip' command.,atomicwrites==1.2.1,attrs==18.2.0,backports.functools-lru-cache==1.5,backports.unittest-mock==1.4,certifi==2018.8.24,chardet==3.0.4,cheroot==6.5.2,-e git+C:\Users\jaraco\p\cherrypy\@8bc3e5289c8e7b4236f93a3e387184170ede33cc#egg=CherryPy,codecov==2.0.15,colorama==0.3.9,coverage==4.5.1,graphviz==0.9,idna==2.7,jaraco.functools==1.20,more-itertools==4.3.0,objgraph==3.4.0,path.py==11.1.0,pluggy==0.7.1,portend==2.3,psutil==5.4.7,py==1.6.0,pytest==3.8.0,pytest-cov==2.6.0,pytest-services==1.3.0,pytest-sugar==0.9.1,python-memcached==1.59,pytz==2018.5,pywin32==223,repoze.lru==0.7,requests==2.19.1,requests-toolbelt==0.8.0,Routes==2.4.1,six==1.11.0,tempora==1.13,termcolor==1.1.0,urllib3==1.23,zc.lockfile==1.3.0
python runtests: PYTHONHASHSEED='320'
python runtests: commands[0] | mkdir -p 'C:\Users\jaraco\code\win\cherrypy/.test-results/pytest'
ERROR: InvocationError for command could not find executable 'mkdir'
______________________________________________________________________ summary _______________________________________________________________________
ERROR:   python: commands failed

```

**Comment by jaraco** [comment]
My guess is that the reason these tests run on AppVeyor is because they provide some 'mkdir.exe' from cygwin or similar. We should remove this hidden dependency.

**Comment by webknjaz** [comment]
No, it's because I declared it as a conditional extra and now it's not installed in Appveyor. Unless you reverted that.

**Comment by webknjaz** [comment]
@jaraco this could be turned into python for compat, but that dir is needed (`python -c ...`)

**Comment by jaraco** [comment]
Right, you said in the commit:

> this directory is needed for Circle CI (it only scans for test results in directories as it maps their names to different test suites).

I'm not sure I understand. Can you provide more detail? Why doesn't the test run produce this directory? If it's only for circle-ci, perhaps the directory creation should happen in the Circle-CI script... or it has to happen in the tox commands, have tox invoke a script that detects circle CI and only creates it there. Otherwise, it just looks like cruft. At a bare minimum, this command needs a comment describing its purpose and needs to be cross-platform.

Can you investigate if this creation could happen in the Circle-CI manifest?

**Comment by webknjaz** [comment]
Circle CI uses folder names as labels for test results report. Previously, we put that xml in the root folder. I prefer having a standard place across all test runtimes.
We could probably store that folder on the Git level.
