### ISSUE TITLE
Again: Autoreloader throws "dictionary changed size during iteration" (since cp 16.0.0)

### ISSUE THREAD

**Issue by ralhei** [cherrypy/cherrypy#1744]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **What is the current behavior?**
At startup of my cherrypy server I get the following exception:
     `RuntimeError: dictionary changed size during iteration`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

see comment at end of this report

* **What is the expected behavior?**
No exception ;-)

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Cheroot version: 6.5.2
- CherryPy version: 16.0.0 - 18.0.1
- Python version: 3.6.4
- OS: Centos7

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
```
Error in background task thread function <bound method Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x7f3997bab128>>.
Traceback (most recent call last):
  File "/fs/local/rh300070/.virtualenvs/lims-dev/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 518, in run
    self.function(*self.args, **self.kwargs)
  File "/fs/local/rh300070/.virtualenvs/lims-dev/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 667, in run
    for filename in self.sysfiles() | self.files:
  File "/fs/local/rh300070/.virtualenvs/lims-dev/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 632, in sysfiles
    return set(filter(None, map(self._file_for_module, mods)))
RuntimeError: dictionary changed size during iteration
```

The problem lies in the 'filter()'-iterator created via 
     `search_mod_names = filter(re.compile(self.match).match, sys.modules)`
in plugins.py, around line 630

If this line is replaced by
     `search_mod_names = list(filter(re.compile(self.match).match, sys.modules))`
the problem disappears.

I guess the problem is due to my code doing dynamic imports during runtime. 
Our code base is rather large, so it is completely non-trivial for me to provide reproducable code, I'm afraid.

**Comment by webknjaz** [comment]
Thanks for the report! Your explanation makes sense. I'd probably copy that list early instead (`sys.modules[:]`).
Mind sending a PR for discussion?
