### ISSUE TITLE
17.4.0 tag

### ISSUE THREAD

**Issue by anderstheet** [cherrypy/cherrypy#1745]
Is it possible to get a tag for 17.4.0, so it can be used?

http://docs.cherrypy.org/en/latest/history.html#v17-4-0

**Comment by webknjaz** [comment]
It's there but hidden under the banner. Scroll up a bit :)

**Comment by anderstheet** [comment]
I see it in the history. I just can't use the version cause there is no tag for 17.4.0 in git.

It doesn't exist:
https://github.com/cherrypy/cherrypy/tree/v17.4.0

**Comment by webknjaz** [comment]
We never released that. It's a mistake in changelog. https://pypi.org/project/CherryPy/#history

This means that those changes likely got into v18.0.0

cc @jaraco

**Comment by jaraco** [comment]
@anderstheet Do you need the changes from that release? Or is it sufficient to correct the change log?

**Comment by jaraco** [comment]
I decided that since the maint/17.x branch already has those commits, and any subsequent 17.x release would include those changes, I went ahead and added the tag, which should create the release.

**Comment by webknjaz** [comment]
@anderstheet https://pypi.org/project/CherryPy/17.4.0/

**Comment by anderstheet** [comment]
Many thanks!
