### ISSUE TITLE
Testing example in documentation not working: header check fails even when set explicitly

### ISSUE THREAD

**Issue by crazcalm** [cherrypy/cherrypy#1749]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Original example code: https://docs.cherrypy.org/en/latest/advanced.html#testing-your-application
Link to code: https://github.com/crazcalm/learn-cherrpy/blob/master/testing_example.py
Using Firefox 62.0.3 (64-bit) on linux

In the first test, I expect the header check to pass. Instead, it fails, even though it is explicitly set.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

When you step through on the set trace, you will see that the "Content-Type" key exists, but it is never equal to your "Content-Type" string because the "-" has been re-encoded post being set. As such, the `k.lower() == lowkey` is always false.

To be clear, I believe there is an underlying bug that allows for your set header key to not be equal to the header key that is returned. However, I am reporting my inability to run the first test successfully.

* **What is the expected behavior?**

Given that this is an example in the documentation, I expected the first test to pass. The source code that I have linked has been modified slightly in an attempt to get the test to work. 

* **What is the motivation / use case for changing the behavior?**

Motivation: Trying to understand how testing works before I use this framework.

* **Please tell us about your environment:**

- Cheroot version: 6.5.2
- CherryPy version: 18.0.1
- Python version: 3.6.6
- OS: Linux: ubuntu (mate) 18.04
- Browser: Firefox 62.0.3

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

link to source code: https://github.com/crazcalm/learn-cherrpy/blob/master/testing_example.py

**Comment by ian-otto** [comment]
I just had a look at your source repo, and it looks like somehow your `-` character got mangled in the process of copying over the source from the test page. I tried it out in my console and got this (left being from your repo, right from cherrypy's tests page):

```
>>> '‐' == '-'
False
```

Also, I tested this test on my machine and was unable to replicate your behavior, so I think this may have just been a copying error.

**Comment by webknjaz** [comment]
yes, those have different char codes:
```python
>>> ord('‐'), ord('-')
(8208, 45)
```

**Comment by webknjaz** [comment]
@crazcalm try `sed -i 's/‐/-/g' testing_example.py`. Dashes in your test module got corrupted somehow. Maybe it's macOS replacing things during copy-paste or smth like that.
