### ISSUE TITLE
Free up port after multiprocess fork?

### ISSUE THREAD

**Issue by eoghanmurray** [cherrypy/cherrypy#1751]
This is more of a question than anything so delete and I'll repost to SO instead?

I'm wondering how to shut down cherrypy in a multiprocessing/forked context:

I'm using `multiprocessing` to fork off from my main web app to do some background tasks.

The main app is a legacy TurboGears 1.5 app that starts and stops CherryPy.

The problem starts when I restart the main app and the background tasks get orphaned as separate processes on the server; the app cannot be restarted as I get a `socket.error: No socket could be created -- (('0.0.0.0', 8110): [Errno 98] Address already in use)`

(I don't understand how a forked process can coexist happily on the same socket with the main process)

I've tried the following in the forked subprocess to stop CherryPy, as it's not actually needed in that context:

```
    def longrunning(is_in_fork=False):
        if is_in_fork:
            try:
                from cherrypy import engine
                engine.stop()  # ensure we don't continue to listen on the socket in this fork in case parent needs to be restarted
            except Exception, e:
                log.exception("Couldn't shut down cherrypy in forked process:")
        # do background stuff
    
    from multiprocessing import Process
    p = Process(target=long_running, args=(True))
```

Unfortunately this throws an exception as stop() in https://github.com/cherrypy/cherrypy/blob/master/cherrypy/process/servers.py#L274
 waits for the port to be free before shutting down (`portend.free()`).

Am I doing it terribly wrong by using multiprocessing? Or is there a simple solution I've missed?

**Comment by webknjaz** [comment]
> I don't understand how a forked process can coexist happily on the same socket with the main process

The thing is that fork inherits all file descriptors parent has. Sockets are accessible through such file descriptors in a nutshell. So while you kill your parent process and reparenting happens (fork gets ppid=1) your forks must get `SIGCHLD` from that exiting parent. Make sure that forks handle this signal correctly and actually exit instead of living as zombies.

P.S. As for shared socket, here's some generic info JFYI:
* https://lwn.net/Articles/542629/
* https://stackoverflow.com/a/670897/595220

**Comment by webknjaz** [comment]
You probably need smth like https://stackoverflow.com/a/34353290/595220

**Comment by eoghanmurray** [comment]
Thanks @webknjaz that's super informative!

**Comment by eoghanmurray** [comment]
`_set_cloexec()` seems to be doing something with file descriptors (sockets?) during a restart:
https://github.com/cherrypy/cherrypy/blob/master/cherrypy/process/wspbus.py#L536
but calling this from my app instead of `stop()` doesn't do what I need.

Here's a C version for closing child sockets: https://stackoverflow.com/questions/19319387/close-opened-sockets-in-child-process  but I've no idea how to translate that to Python.

Closing as I can live with the `p.daemon = True` solution.
