### ISSUE TITLE
Incorrect loglevel set in  cherrypy/cherrypy/process/win32.py  file 

### ISSUE THREAD

**Issue by jvisu** [cherrypy/cherrypy#1762]
Its looks like a trival issue. But want to inform you.

The loglevel set for class ConsoleCtrlHandler(plugins.SimplePlugin) is error for success case which I assume should be info or debug.

That is in class ConsoleCtrlHandler(plugins.SimplePlugin), start and stop method we have the below logs which are set to error.
start: 
 self.bus.log('Set handler for console events.', level=40) 
stop:
 self.bus.log('Removed handler for console events.', level=40)

I assume that the log level should be 10 or 20 if I'm not wrong.

**I'm submitting a ...**
- [ ] bug report

**Do you want to request a *feature* or report a *bug*?**
Reporting as bug

**What is the current behavior?**
Currently it logs as ERROR as below
 [cherrypy.error] [ERROR] [18/Dec/2018:19:40:27] ENGINE Set handler for console events.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
File name:  cherrypy/cherrypy/process/win32.py
Class: ConsoleCtrlHandler(plugins.SimplePlugin)
Method:
start
  self.bus.log('Set handler for console events.', level=40)
stop
  self.bus.log('Removed handler for console events.', level=40)

**What is the expected behavior?**
It should report as INFO
 [cherrypy.error] [INFO] [18/Dec/2018:19:40:27] ENGINE Set handler for console events.

**What is the motivation / use case for changing the behavior?**
Looks like a bug as the log shows error though everything is good.

**Please tell us about your environment:**
It occurs in all versions. Tested in CherryPy 7.1.0.
OS: Windows

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
@jvisu can you confirm that it's still the case for a modern version of CherryPy? Is this reproducible under v18?

**Comment by jvisu** [comment]
Thanks webknjaz for the quick response.
Based on the code in github I can confirm the issue is in v18 also.
The code https://github.com/cherrypy/cherrypy/blob/v18.1.0/cherrypy/process/win32.py still sets the loglevel to 40 for successful case.

**Comment by webknjaz** [comment]
It's probably fine to follow the example of wspbus module and use `20`. Would you like to send a PR for that?

**Comment by jvisu** [comment]
Thanks webknjaz.
Will be using loglevel as 20 if needed. 
Regarding providing pull request, I'm new to this group, I can create a request with code changes and no through test as I don't know the process how to test all use cases.
So did not create a request.
Created this trivial issue only to inform about the needed code changes.

**Comment by webknjaz** [comment]
It's fine if you create a PR without tests now :)

**Comment by jvisu** [comment]
Thanks webknjaz.
Create a pull request 
https://github.com/cherrypy/cherrypy/pull/1763

**Comment by webknjaz** [comment]
Thanks @jvisu!

**Comment by jvisu** [comment]
Thanks webknjaz for the quick update.
I'm not sure about merging the request. 
I assume merge will be done by the system/administrators once the test are done. 
Do I have any action do be done now regarding pull request or issue closure. If yes, please let me know. I will do that.
Thanks again for  good support provided.

**Comment by webknjaz** [comment]
Don't worry, I'll merge it. Test failures are not related to your change :)
