### ISSUE TITLE
multi background task shared the global sqlalchemy session

### ISSUE THREAD

**Issue by xiazhibin** [cherrypy/cherrypy#1773]
Since cherrypy is an Multi-Threaded Application Server , I have multi background tasks to sync data from outside. And all of them shared the global SQLAlchemy session. That is not thread safe.But I have no idea to deal with this situation.

In request,I can hook the SQLAlchemy session into `cherrypy.request.db`.  [Here](https://bitbucket.org/Lawouach/cherrypy-recipes/src/tip/web/database/sql_alchemy/) is the recipe

So, my question is how can I deal with the SQLAlchemy session between the background tasks?

**Comment by webknjaz** [comment]
@xiazhibin I believe you should be able to do it like in this line https://bitbucket.org/Lawouach/cherrypy-recipes/src/1a27059966e962be52b2abd91e9709c3ee63cf2d/web/database/sql_alchemy/satool.py?at=default&fileviewer=file-view-default#satool.py-35

**Comment by webknjaz** [comment]
cc @Lawouach

**Comment by Lawouach** [comment]
A blast from the past.

Honestly, I haven't looked there for a very a long time so this is off the top of my head.
scoped_session in SA are per thread so I'm not sure what the difficulty is here? @xiazhibin, could you please clarify your question/use case?
