### ISSUE TITLE
CherryPy splits queries on semicolon rather than ampersand

### ISSUE THREAD

**Issue by mcow** [cherrypy/cherrypy#1778]
As best as I can tell, a query string with parameters is supposed to [separate those parameters using `&` (ampersand)](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data) (W3C 2014 TR; see **decode** algorithm step ~~4.3~~1), but CherryPy splits on semicolon. (EDIT: fixed pointer to relevant TR statement.)

I ran into this because the original version of my server was written on CherryPy and the in-page JavaScript generates semicolon-separate queries; these fail in the port of my server to one written on Express in NodeJS. Changing the query generation to work under Express causes it to fail under CherryPy.

The [best discussion I could find](https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator) on this, at StackOverflow, accepted the answer referencing that spec, but opinions varied vociferously.

Version info; I originally wrote my server under Python 2.7 using whatever CherryPy was current in 2014, and recently got it running under Python 3 (cheroot 6.5.4, cherrypy 18.1.0) with no changes required on the query generation.

**Comment by webknjaz** [comment]
Hey, could you please provide a more complete reproducible example? We're missing some context here.

**Comment by mcow** [comment]
I can try; not sure what is sufficient here. My web application is a single-page, AJAXy controller. The web page JS sends some queries with parameters to the server's `dyno` page. When I first wrote the server, using CherryPy, what I found worked was a query issued via jQuery such as:

`$.getJSON("dyno/list?delete=42;hash=loremipsum", (resp)=>{...});`

Note the semicolon separating the `delete` parameter from the `hash` parameter.

Then in the server I have
```python
class Dyno(object):
    @cherrypy.expose
    @cherrypy.tools.response_headers(headers=jsonhdrs)
    def list(self, **kwargs):
        if 'delete' in kwargs and 'hash' in kwargs:
            # process the delete request
```

This worked great. But then I ported my server to Node.js and the Express server and found that with the semicolon, I did not get the fields parsed out; but changing to an ampersand made it work. That same change causes CherryPy to no longer parse out the fields. And as I referred to originally, it seems that `&` is the standard and `;` is not.

**Comment by ankush981** [comment]
@webknjaz Hello, random dev interested in CheryPy here. Don't tell me CherryPy can't handle query strings with the `&` character!! :astonished: Surely this is some other issue here, right?

**Comment by webknjaz** [comment]
@ankush981 Everything works.
This topic is about submitting forms which use `application/x-www-form-urlencoded`, not normal URL params in queries.

@mcow I think that the most robust way of using forms in `multipart/form-data` anyway. But if you want to improve the support of `urlencoded`, PRs are welcome.

**Comment by webknjaz** [comment]
Also, jQuery thing doesn't look right. Ampersand in normal raw query-params works. So maybe you're confusing what you're actually sending there. Anyway. We need a complete reproducer. And better remove all JS and show queries with `curl`.

**Comment by webknjaz** [comment]
It may also be useful to show an asciinema recording of what you do actually and what happens.

**Comment by webknjaz** [comment]
Parser for the request line uses `urllib.parse`: https://github.com/cherrypy/cheroot/blob/7558014/cheroot/server.py#L819.

**Comment by mcow** [comment]
@webknjaz no, not gonna do that. Not interested in even googling to find out what "asciinema" is. If you don't care, I don't care: I have a solution that works, and it's not CherryPy.

**Comment by webknjaz** [comment]
I do care, but since you didn't provide a way to reproduce this and ways I know work there nothing actionable here.

**Comment by webknjaz** [comment]
FTR a more complete analysis of supporting delimiters per HTTP specs is outlined @ https://github.com/cherrypy/cherrypy/issues/1860.
