### ISSUE TITLE
Question: Possible to use an interactive shell?

### ISSUE THREAD

**Issue by ankush981** [cherrypy/cherrypy#1782]
Hello, I was wondering what it'd take to set up and run an interactive shell for CherryPy, just like we have the `manage.py` shell in Django. I'm a little surprised there aren't any issues/tutorials/StackOverflow discussions for it. 

Can something like this be done easily? Is it even possible?

**Comment by webknjaz** [comment]
It's is not needed for this framework. You can write your own if you want.
Django is a huge monster with one enforced way to do things.
CherryPy is a microframework, which means it doesn't try to limit how you use it or which other tools you integrate into your project, this also means that you have great flexibility.

**Comment by ankush981** [comment]
I'm sorry but I don't see how a shell limits flexibility or forces a particular way of thinking. Please note that I'm not talking about developing a script similar to `manage.py` but a sort of console (similar to what we see after launching Django's interactive shell). I think it'd be nice to be able to access the framework instance and play around through an interactive Python interpreter. This perhaps can even be done through the standard Python interpreter; it's just that I don't know how to instantiate the framework instance and access, say, models, etc., once the interpreter is running.

**Comment by webknjaz** [comment]
there's no such thing as models or anything else enforced. you choose and configure everything as you want. there's nothing called an instance of a framework.
and there's nothing to manage like that.

I think you're missing the point of microframeworks. You have to go through the tutorial to understand better.

You can use normal Python REPL or IPython or anything similar and import things to play with. Yet, I don't see a point for you to try it out before learning more. Currently, you only point to things you have to implement yourself.

**Comment by ankush981** [comment]
Okay, never mind. :slightly_smiling_face:
