### ISSUE TITLE
Trouble with URL containing "+" sign.

### ISSUE THREAD

**Issue by Adilet92** [cherrypy/cherrypy#1790]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

Hello!
I want to decode the input parameter to image, but created image is incorrect. I found, when encoding input parameter, "+" sign encoded as " " (blank space). My input parameter - encode base64 of image as string. My actions:
1. Encode the string to bytes.
2. Decode them to base64.
3. Create image file and write decoded value.

My code:
```python
import cherrypy
import base64

class StringDecoder(object):
         @cherrypy.expose
         def decoder(self, img):
                   image = img.encode()
                   dec_img = base64.decodestring(image)
                   f = open("1.jpg", "wb")
                   f.write(dec_img)
                   f.close()

                   return image
if __name__ == '__main__':
          cherrypy.quickstart(StringDecoder())
```
my request: http://127.0.0.1/decoder?img=/9fUnJ1+K...
responce: /9fUnJ1 K...

- Cheroot version: 6.5.5
- CherryPy version: 18.1.2
- Python version: 3.5.3
- OS: Windows 10

Thanks!

**Comment by webknjaz** [comment]
Hi, from the HTTP point of view you must percent-encode values in query params. For example, `+` is `%2B`.

https://en.wikipedia.org/wiki/Percent-encoding

**Comment by webknjaz** [comment]
P.S. You really should just send multipart/form-data payload using POST, the length of query-params is usually quite limited.
