### ISSUE TITLE
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 7077 not free on 0.0.0.0.',)

### ISSUE THREAD

**Issue by alnikolaj** [cherrypy/cherrypy#1792]
**I'm submitting a ...**
- [ ] bug report

**Do you want to request a *feature* or report a *bug*?**
The following Bug: 
```python-traceback
Traceback (most recent call last):
  File "/home/sammy/.local/lib/python3.6/site-packages/portend.py", line 115, in free
    Checker(timeout=0.1).assert_free(host, port)
  File "/home/sammy/.local/lib/python3.6/site-packages/portend.py", line 69, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/home/sammy/.local/lib/python3.6/site-packages/portend.py", line 85, in _connect
    raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 0.0.0.0 is in use on 7077.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sammy/.local/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/home/sammy/.local/lib/python3.6/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/home/sammy/.local/lib/python3.6/site-packages/cherrypy/process/servers.py", line 177, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "/home/sammy/.local/lib/python3.6/site-packages/portend.py", line 119, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 7077 not free on 0.0.0.0.

[18/Jul/2019:09:54:44] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/home/sammy/.local/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/home/sammy/.local/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 7077 not free on 0.0.0.0.',)

[18/Jul/2019:09:54:44] ENGINE Bus STOPPING
[18/Jul/2019:09:54:44] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 7077)) already shut down
[18/Jul/2019:09:54:44] ENGINE Stopped thread 'Autoreloader'.
[18/Jul/2019:09:54:44] ENGINE Bus STOPPED
[18/Jul/2019:09:54:44] ENGINE Bus EXITING
```
**What is the current behavior?**
I have created a website with CherryPy and Mako running with NGINX. But, whenever I start my CherryPy script it says `cherrypy.process.wspbus.ChannelFailures: Timeout('Port 8080 not free on 127.0.0.1.',)`. Although I have to say that the script runs nonetheless and the website goes live. But the error message is still bugging me. I checked the configurations and NGINX listens to port `80` (default, I believe) and the `upstream app_servers` is server `127.0.0.1:8080`.

 I killed the python process locating it with the PID. I restarted it and funny enough, the error did not came back after shutting down the script but when I re-started the script for a second time (while running again), the error came back. So, something must be funky.

I added `cherrypy.config.update({'server.socket_port': 7077})` which basically changes the port of my CherryPy script to the port `7077`. Changed the nginx config to: `upstream app_servers { server 127.0.0.1:7077; }` and opened the ports in the firewall settings, but still the same issue with `('Port 7077 not free on 127.0.0.1.',)` when I re-start my running CherryPy script. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- CherryPy version: CherryPy 18.1.0
- Python version: Python 3.6.8
- OS: ubuntu 18.04

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
Any reproducer? I have no idea what you're running.

**Comment by alnikolaj** [comment]
Hey webknjaz, 

thanks for the reply! I am rather a novice with CherryPy and in general with WebFrameworks. Therefore, I will say sorry in advance for my inexperience and be straight forward saying I do not know how to provide you with a reproducer? 

To explain a bit more what I did: I have this issue "cherrypy.process.wspbus.ChannelFailures: Timeout('Port 7077 not free on 0.0.0.0.',)" with my existing website and to see whether this Problem occurred again I created a whole new test server on Digital Ocean. 

1) I setup the server (https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-18-04)
2) I installed Pip and CherryPy. 
3) I Installed NGINX and I used the NGINX configuration shown here (skip to section Configuring Nginx -> Example configuration for web applications // WSGI was not installed nor configured): https://www.digitalocean.com/community/tutorials/how-to-deploy-python-wsgi-applications-using-a-cherrypy-web-server-behind-nginx#miscellaneous-tips-and-suggestions 
4) I created a simple python file (test.py) running cherrypy (hello world!). I worked with no problems. 

Here is where the problems started. If I run the cherrypy script again ($ python3 test.py&) I get the error message shown above. I located the process with netstat -plunt and saw that python3 and nginx: master are listening to:

22833/python3: 127.0.0.1:8080
22793/nginx: master: 0.0.0.0:80

Since the error message said that port is not free, I changed the cherrypy port to 7077, configured the NGINX Config to upstream app_servers { server 127.0.0.1:7077; }. 

I restarted NGINX and run the script again. If the process is shutdown and I start it, it does not show the error message. If it is running and I re-start it, the error message arises. So, maybe it is normal? I tried to google the issue but could not find any information so this is my last resort? Sorry if this question is very stupid..

**Comment by webknjaz** [comment]
Yes, multiple applications normally cannot listen to the same port. The kernel only allocates that port to one process and unless you shut it down another process cannot start listening to it.
Also, I'd like to point out that `python3 test.py &` is not a good way of keeping the server running. You should probably wrap it into a systemd unit and use like any other system service (via systemctl).

As for reproducer — it's a very minimal snippet of code that anybody would be able to run, follow your instructions and see the problem. Best if you can exclude unrelated stuff like extra software (e.g. nginx) from such reproducer. Usually, it's very useful to provide logs/terminal/console output.
I also find interesting the https://asciinema.org project which allows you to record your terminal session and others would be able to replay it and see with their own eyes.

**Comment by alnikolaj** [comment]
Thanks for the reply! 

Ok, I did not know that python3 test.py & is not a good way. Ok, I will check and figure out to do your suggestion with the systemd. Do you might an indication where I could find out how do it with CherryPy? (if not, no problem - I will use the power of Google!) 

Till then (first I have to see how to it with the systemd), please find below the recording: 

https://asciinema.org/a/7FPNZJCwxlUWL39gjoULyiw6p

**Comment by webknjaz** [comment]
https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units

**Comment by webknjaz** [comment]
Watching your recording: `kill -9` is a bad practice. Usually, SIGTERM is enough. SIGKILL doesn't give the process any chance to gracefully complete whatever it was doing before exiting which may lead do half-complete operations and things that script should do correctly before closing.

**Comment by webknjaz** [comment]
`&` puts the process in "background" but it's still bound to your current terminal. I'll get terminated as soon as you close the terminal. Systemd units or similar will take care of this by spawning proper daemons which aren't connected to your terminal session. You'll also get logs in `journalctl` this way.

**Comment by webknjaz** [comment]
So after watching the whole recording, I can confirm that you are trying to listen to the same port with multiple processes which won't work.

**Comment by alnikolaj** [comment]
Dear webknjaz, 

I am absolutely grateful for your help! 

As it seems, this is rather my stupidity and inexperience rather than a CherryPy bug. Just to understand it correctly, since I re-start my Python script, test.py, basically interferes with itself causing the error message to pop-up, correct? Because netstat does not show any other process listening to that specific port? 

Thank you so much again and I wish you a wonderful day!

**Comment by webknjaz** [comment]
Yes, that's right. You can also type `jobs` command to see scripts you spawned with `&` and also you can use `fg` to attach the last one back to the foreground in which mode `Ctrl+C` will also work (emitting SIGINT) as a hotkey to initialize the app termination.

**Comment by webknjaz** [comment]
Closing the issue now because it's now a bug :)
