### ISSUE TITLE
CherryPy and pytest fixtures in tests' class

### ISSUE THREAD

**Issue by stemoser** [cherrypy/cherrypy#1798]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
I think is a sort of "bug", but I'm not sure to understand what's the intended behaviour.

**What is the current behavior?**
When I run a test method with pytest inside a test class to group different tests together, the test fails if a fixture is required by the test method (intended as a pytest fixture).
It seems that this is due to the helper.CPWebCase class, that for some reason tries to use unittest (even if the documentation tells to install pytest).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

A minimal example to reproduce the problem:

```
import pytest
from cherrypy.test import helper

@pytest.fixture
def foo():
    return "Ok!"

class TestSample(helper.CPWebCase):

    def test_sample(self, foo):
        return foo is not None
```

If you run the test with pytest you will get:
`TypeError: test_sample() missing 1 required positional argument: 'foo'`

**What is the expected behavior?**
I would expect that if pytest is the suggested testing framework it will work as expected also with the helpers of CherryPy, so fixtures should be correctly injected in the test methods.
Or, at least, the documentation should state somewhere that pytest is used for other purposes, but not all the features are supported in these cases. 

**Please tell us about your environment:**

- Cheroot version: 6.5.5
- CherryPy version: 18.1.2
- Python version: 3.7.3
- OS: Windows
- Browser: not relevant.
- pytest: 5.0.1

**Comment by webknjaz** [comment]
I believe that the problem is that `CPWebCase` inherits `unittest.TestCase` which doesn't play well with pytest (https://docs.pytest.org/en/latest/unittest.html#mixing-fixtures). I suggest you try https://pyriform.readthedocs.io/en/latest/ with pytest-native test functions.

**Comment by stemoser** [comment]
@webknjaz, thanks for the links. In fact pytest clearly states that normal fixtures do not work correctly in unittest.TestCase derived classes.
I think that this expected behaviour should be added somewhere in the documentation, don't you agree?

**Comment by webknjaz** [comment]
Yes, that would be nice to add a note. I think that earlier versions of pytest partially supported fixtures but then it got dropped. Feel free to send a docs PR to mention this.

**Comment by stemoser** [comment]
Ok, give me some days, just to have the time to do it. 👍
