### ISSUE TITLE
RamSession clean_up() occasionally causes cleanup thread death

### ISSUE THREAD

**Issue by eshellman** [cherrypy/cherrypy#1803]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Under heavy load (25K req/hr) and a large session cache (10K sessions), the `RamSession.clean_up()` method will occasionally (~1/week) raise a `RuntimeError` with the message "dictionary changed size during iteration". This causes the cleanup thread to die, and the cache then grows to use all available memory.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

```python-traceback
[15/Aug/2019:02:06:11] ENGINE Error in background task thread function <bound method 
RamSession.clean_up of <cherrypy.lib.sessions.RamSession object at 0x7f138d920438>>.
Traceback (most recent call last):
  File "/var/lib/autocat/.local/share/virtualenvs/autocat3-mGIyuTut/lib/python3.6/site-packages/cherrypy/process/plugins.py", line 517, in run
    self.function(*self.args, **self.kwargs)
  File "/var/lib/autocat/.local/share/virtualenvs/autocat3-mGIyuTut/lib/python3.6/site-packages/cherrypy/lib/sessions.py", line 407, in clean_up
    for _id, (data, expiration_time) in list(self.cache.items()):
RuntimeError: dictionary changed size during iteration

```
The autocat3 service serves the dynamic content on the Project Gutenberg website.

**What is the expected behavior?**

the cleanup thread should not die.

**What is the motivation / use case for changing the behavior?**

not having the server die in the night every week or so.

**Please tell us about your environment:**

- Cheroot version: 6.5.5
- CherryPy version: 18.1.1
- Python version: 3.6.8
- OS: CentOS Linux release 7.6.1810 (Core)
- Browser: all
- Number of server threads: 10

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

I am preparing a PR which catches `RuntimeError`s from `list(self.cache.items())` in `RamSession`; a patched class is now in production. and I'd like to see it run for a week.

The other, more general way to fix this would be to change line 301 in `lib.sessions` from ```if self.clean_freq and not cls.clean_thread``` to ```if self.clean_freq and (not cls.clean_thread or not cls.clean_thread.is_alive())``` but I do not know the code well enough to judge whether this is overkill.

**Comment by webknjaz** [comment]
Thanks for the report @eshellman!

**Comment by eshellman** [comment]
let me know if there is other relevant info I can provide.

**Comment by webknjaz** [comment]
This looks quite comprehensive but I disagree with the conclusions. I'll comment on the PR :)
