### ISSUE TITLE
module 'cherrypy' has no attribute 'expose'

### ISSUE THREAD

**Issue by micksulley** [cherrypy/cherrypy#1809]
I'm new to CherryPy so may have missed something.  All on Python3.  
I installed on my desktop (Linux Mint) and ran the 'Hello World' example, opened browser on http://localhost:8080 and it works.  
I installed on a Raspberry Pi (Buster) but when I run this code 
```python
import cherrypy
class HelloWorld(object):
    @cherrypy.expose
    def index(self):
        return "Hello world!"
if __name__ == '__main__':
    cherrypy.quickstart(HelloWorld(),'/')
````
this is what I see
```python-traceback
pi@pi-solar-old:~ $ python3 cherrypy.py
Traceback (most recent call last):
  File "cherrypy.py", line 1, in <module>
    import cherrypy
  File "/home/pi/cherrypy.py", line 4, in <module>
    class HelloWorld(object):
  File "/home/pi/cherrypy.py", line 5, in HelloWorld
    @cherrypy.expose
AttributeError: module 'cherrypy' has no attribute 'expose'
pi@pi-solar-old:~ $ 
```
What am I doing wrong?

**Comment by webknjaz** [comment]
> What am I doing wrong?

Two things:
1) you didn't fill in the template which would be helpful
2) you called your module `cherrypy.py` so it imports itself. Rename it and clean up all `__pycache__/*.pyc` files.

For more info, read about how imports work somewhere @ https://docs.python.org/3/.
