### ISSUE TITLE
Dictionary entries by class HeaderReader are strange

### ISSUE THREAD

**Issue by bmxp** [cherrypy/cherrypy#1827]
❓ **I'm submitting a ...**
- [X] 🐞 bug report
- [ ] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

🐞 **Describe the bug. What is the current behavior?**

From cheroot server the class HeaderReader gives strange dict entries like ``{"B'Status'": b'302 Found' }`` when using a predefined dictionary like the one in ``cherrypy.serving.response.headers``.

❓ **What is the motivation / use case for changing the behavior?**
The result should not contain these strange dictionary entries.

💡 **To Reproduce**

Consider the following code:
```python
import tempfile
import cherrypy
from cheroot import server

response = tempfile.SpooledTemporaryFile(max_size = 1000, mode = "w+b")

response.write(b'Status: 302 Found\r\nLocation: index.php?\r\nContent-type: text/html; charset=UTF-8\r\n\r\n')

emptydict ={} 
response.seek(0)
hr = server.HeaderReader()
headers = hr(response,cherrypy.serving.response.headers)
print(headers)

print(80*'-')

response.seek(0)
headers = hr(response,emptydict)
print(headers)


print(80*'-')

otherdict ={ 'Content-Type':'text/html'} 
response.seek(0)
headers = hr(response,otherdict)
print(headers)
```
This will result in output like
```console
{'Content-Type': 'text/html', 'Server': 'CherryPy/18.4.0', 'Date': 'Sat, 23 Nov 2019 20:10:51 GMT', "B'Status'": b'302 Found', "B'Location'": b'index.php?', "B'Content-Type'": b'text/html; charset=UTF-8'}
--------------------------------------------------------------------------------
{b'Status': b'302 Found', b'Location': b'index.php?', b'Content-Type': b'text/html; charset=UTF-8'}
--------------------------------------------------------------------------------
{'Content-Type': 'text/html', b'Status': b'302 Found', b'Location': b'index.php?', b'Content-Type': b'text/html; charset=UTF-8'}
```

💡 **Expected behavior**

The first printed dict is not ok IMHO. The second and third printed dicts show the expected entries in dict.
A lookup like ``if 'Status' in dict ...`` will thus fail and a workaround ist needed.

📋 **Environment**

- Cheroot version: 8.2.1
- CherryPy version: 18.4.0
- Python version: 3.7.3
- OS: Debian 10 (buster)
- Browser: not relevant

📋 **Additional context**

**Comment by webknjaz** [comment]
@jaraco I think we still need to add bytes-validation to `cheroot.server.HeaderReader.__call__()` too.

**Comment by jaraco** [comment]
> I think we still need to add bytes-validation to `cheroot.server.HeaderReader.__call__()` too.

Yes, I think so too. Having mixed bytes/text in the HeaderMap is bad form. Would you be willing to write up a ticket about that issue?

**Comment by webknjaz** [comment]
I guess so.

**Comment by webknjaz** [comment]
After looking into it closer, I don't think that such validation belongs there because `__call__()` just adds headers into the given dict, it doesn't do anything with what already exists there. Such validation would need to be done in the calling code.
