### ISSUE TITLE
CherryPy 17.x fails against cheroot 8.x

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1831]
In Travis-CI (our main CI), the tests for the maint/17.x branch (Python 2 compatible version) are failing. They [last passed two months ago](https://travis-ci.org/cherrypy/cherrypy/builds/592826066?utm_medium=notification&utm_source=email) and [started failing shortly thereafter](https://travis-ci.org/cherrypy/cherrypy/builds/593605221?utm_medium=notification&utm_source=email).

**Comment by jaraco** [comment]
Not too long after that, the [test started failing earlier](https://travis-ci.org/cherrypy/cherrypy/builds/596661176?utm_medium=notification&utm_source=email).

**Comment by webknjaz** [comment]
I have a hunch that this is related to that connections management change in Cheroot...

**Comment by jaraco** [comment]
>> Not too long after that, the test started failing earlier.

> I have a hunch that this is related to that connections management change in Cheroot...

Confirmed - the introduction of cheroot 8.1.0 introduced a regression that causes one test to consistently fail (prior tests ran against cheroot 7.0.0).

**Comment by jaraco** [comment]
This is the same as #1817.
