### ISSUE TITLE
pip can no longer install cherrypy (without tweaking) on python 3.5.3 due to 4 dependencies requiring 3.6

### ISSUE THREAD

**Issue by JonasHeidelberg** [cherrypy/cherrypy#1837]
**I'm submitting a ...**
- [x] bug report

**What is the current behavior?**
When trying to
`pip3 install cherrypy`
on raspbian (stretch) with python 3.5.3, I get the following error message:

> jaraco.collections requires Python '>=3.6' but the running Python is 3.5.3

According to [jaraco.collections ChangeLog](https://github.com/jaraco/jaraco.collections/blob/master/CHANGES.rst), the Version 3.0.0 now requires python 3.6 --> workaround is to install jaraco.collections<3.0.0. The same issue then pops up 3 more times:

> jaraco.functools requires Python '>=3.6' but the running Python is 3.5.3
> jaraco.classes requires Python '>=3.6' but the running Python is 3.5.3
> tempora requires Python '>=3.6' but the running Python is 3.5.3

**My final workaround therefore is**
`pip3 install "jaraco.collections<3.0.0"  "jaraco.classes<3.0.0" "jaraco.functools<3.0.0" "tempora<2.0.0" "cherrypy" `

**What is the expected behavior?**
Cherrypy should automatically request the correct versions of these tools in python3.5, to avoid the error messages

**What is the motivation / use case for changing the behavior?**
Less hassle installing cherrypy.

**Please tell us about your environment:**

- Cheroot version: cheroot-8.2.1
- CherryPy version: cherrypy-18.5.0
- Python version: 3.5.3
- OS: Linux raspberrypi 4.14.34-v7+
- Browser: n/a

**Comment by webknjaz** [comment]
CherryPy's metadata is correct. Upgrade your Pip and you'll be fine.

**Comment by JonasHeidelberg** [comment]
@webknjaz I tried again in a venv, where I updated pip to 19.3.1. 

`pip3 install cherrypy` still fails with the same error. Maybe you can argue that jaraco.* and tempora need to fix their metadata, but it is not fine, as far as I can tell.

**Comment by webknjaz** [comment]
Log or didn't happen ☺

**Comment by ian-otto** [comment]
I can second this behavior on the Raspberry Pi install of Python 3.5.3:

```
pi@raspberrypi:~ $ python3 --version
Python 3.5.3
pi@raspberrypi:~ $ python3 -m pip --version
pip 20.0.2 from /home/pi/.local/lib/python3.5/site-packages/pip (python 3.5)
pi@raspberrypi:~ $ python3 -m pip install cherrypy
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cherrypy
  Using cached CherryPy-18.5.0-py2.py3-none-any.whl (418 kB)
Collecting zc.lockfile
  Using cached zc.lockfile-2.0-py2.py3-none-any.whl (9.7 kB)
Collecting portend>=2.1.1
  Using cached portend-2.6-py2.py3-none-any.whl (5.1 kB)
Collecting more-itertools
  Using cached more_itertools-8.1.0-py3-none-any.whl (41 kB)
Collecting jaraco.collections
  Using cached https://www.piwheels.org/simple/jaraco-collections/jaraco.collections-3.0.0-py2.py3-none-any.whl (9.4 kB)
ERROR: Package 'jaraco.collections' requires a different Python: 3.5.3 not in '>=3.6'
```

**Comment by webknjaz** [comment]
@duper51 ~I can only suggest that debians ship "broken" Python/Pip (because they strip off some things, this may be a possible explanation).~

Oh, wait! I see now! You use a custom index (https://www.piwheels.org) which delivers dists that are different from PyPI. If they build them incorrectly (which they 100% are), this'd happen. I bet they use an outdated setuptools version which results in wheels not having `python_version` embedded into the metadata.

You should raise this issue with them then.


@jaraco ^

**Comment by webknjaz** [comment]
Hm... Interesting. The wheels are identical. `METADATA` inside has `Requires-Python: >=3.6` so it's good. The only thing I can think of is `piwheels` not implementing PEP503.

**Comment by webknjaz** [comment]
Ah... I was right, it doesn't: https://github.com/pypa/setuptools/issues/1976#issuecomment-576036922

Compare the source code (HTML view) of https://pypi.org/simple/jaraco-collections/ vs. https://www.piwheels.org/simple/jaraco.collections/.

PyPI injects `data-requires-python` into the link attributes and piwheels doesn't.
This means when Pip fetches the list of dists from this index, it doesn't know which versions have Python restriction and just gets the latest one.

Anyway, you should complain to piwheels about this. As a workaround, you could stop using piwheels. CherryPy is pure-python anyway and the official dists should work just fine on Rpi.

**Comment by brainwane** [comment]
Looks like https://github.com/piwheels/piwheels/issues/208 is about this issue so Piwheels is in the process of fixing it.
