### ISSUE TITLE
add .idea folder to .gitignore file

### ISSUE THREAD

**Issue by zarinpy** [cherrypy/cherrypy#1843]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

when you open the project with jetbrain ides it will track .idea folder

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

**What is the expected behavior?**

.idea folder should be in .gitignore file

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- Cheroot version: 8.2.1
- CherryPy version: 18.5.0
- Python version: 3.6.X
- OS: Ubuntu
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
> .idea folder should be in .gitignore file

Yes, in the user-global, given that the user uses Idea.
