### ISSUE TITLE
ToolTests::testCombinedTools fails in NixOS

### ISSUE THREAD

**Issue by unode** [cherrypy/cherrypy#1849]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**What is the current behavior?**

Test `ToolTests::testCombinedTools` fails with the output mentioned in [this Nixpkgs issue](https://github.com/NixOS/nixpkgs/issues/84897#issuecomment-612383018).
The version listed is `18.3.0` but the failure is also reproducible in `18.5.0`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

1. Install [NixOS](https://nixos.org) or [nix](https://nixos.org/nix/) or use https://hub.docker.com/r/nixos/nix/
2. `git clone --depth 1 https://github.com/NixOS/nixpkgs`
3. `cd nixpkgs`
4. `git checkout 4e4e57bdd3bbfaaf27eab08c6502530c0f52d448`
5. `export NIXPKGS=$(pwd)`
6. `nix-build $NIXPKGS -A python37Packages.cherrypy`

**What is the expected behavior?**

Test `ToolTests::testCombinedTools` fails. All others pass (except 3 XPASS + 3 SKIPPED).

**Please tell us about your environment:**
```
platform linux -- Python 3.7.7, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /nix/store/vs4vj1yzqj1bkcqkf3b6sxm6jfy1gb4j-python3-3.7.7/bin/python3.7
cachedir: .pytest_cache
rootdir: /build/CherryPy-18.5.0, inifile: pytest.ini, testpaths: cherrypy/test/
plugins: cov-2.8.1, services-2.0.1
collected 298 items / 1 deselected / 297 selected
```
```
Requirement already satisfied: portend>=2.1.1 in /nix/store/8ynzwhpbl3f8hxx0w8x11b15izck1q1x-python3.7-portend-2.6/lib/python3.7/site-packages (from CherryPy==18.5.0) (2.6)
Requirement already satisfied: more-itertools in /nix/store/nlxnby9qcnykhbpaxk4wa3jdivj7mzb3-python3.7-more-itertools-8.0.2/lib/python3.7/site-packages (from CherryPy==18.5.0) (8.0.2)
Requirement already satisfied: cheroot>=8.2.1 in /nix/store/73vm9wzl2779zggh5yp4yp3pi2bby7fn-python3.7-cheroot-8.2.1/lib/python3.7/site-packages (from CherryPy==18.5.0) (8.2.1)
Requirement already satisfied: jaraco.collections in /nix/store/2h7h6g0lj5yp21ql9w97y801iawyp6h7-python3.7-jaraco.collections-2.1/lib/python3.7/site-packages (from CherryPy==18.5.0) (2.1)
Requirement already satisfied: zc.lockfile in /nix/store/irkckny3vvipls1hqc1vmrv6p05abifn-python3.7-zc.lockfile-2.0/lib/python3.7/site-packages (from CherryPy==18.5.0) (2.0)
Requirement already satisfied: tempora>=1.8 in /nix/store/i5n6dpbdk07inlzws2ifjnig8nzkkyzs-python3.7-tempora-1.14.1/lib/python3.7/site-packages (from portend>=2.1.1->CherryPy==18.5.0) (1.14.1)
Requirement already satisfied: jaraco.functools in /nix/store/sdbcp9k4jhf7rcvwlj4hmq372gnmws5b-python3.7-jaraco.functools-2.0/lib/python3.7/site-packages (from cheroot>=8.2.1->CherryPy==18.5.0) (2.0)
Requirement already satisfied: six>=1.11.0 in /nix/store/whv9wb1anihmjvc27y52m6a1xpa52sb7-python3.7-six-1.14.0/lib/python3.7/site-packages (from cheroot>=8.2.1->CherryPy==18.5.0) (1.14.0)
Requirement already satisfied: jaraco.classes in /nix/store/ws17q3fv5iwvpyhkiy49hz4s6fwl2nbj-python3.7-jaraco.classes-3.1.0/lib/python3.7/site-packages (from jaraco.collections->CherryPy==18.5.0) (3.1.0)
Requirement already satisfied: jaraco.text in /nix/store/hs0sd4m4nly7n3gjwzsryc347qir9k8v-python3.7-jaraco.text-3.2.0/lib/python3.7/site-packages (from jaraco.collections->CherryPy==18.5.0) (3.2.0)
Requirement already satisfied: setuptools in /nix/store/kxri2ybkwkzpqms4qf5p8n7wipbb64h9-python3.7-setuptools-45.2.0/lib/python3.7/site-packages (from zc.lockfile->CherryPy==18.5.0) (45.2.0.post20200329)
Requirement already satisfied: pytz in /nix/store/aszlsvifr4ym1lg7k213hxnjqyims6xr-python3.7-pytz-2019.3/lib/python3.7/site-packages (from tempora>=1.8->portend>=2.1.1->CherryPy==18.5.0) (2019.3)
```

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

https://github.com/NixOS/nixpkgs/issues/84897

**Comment by bachp** [comment]
The issue only occures since the update from Python 3.7.6 to 3.7.7.

The exact failure is that the body seems to be different:
```diff
-3.7.6: b'"\x8e\x0b\x03-\xbc\x94a\x03\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03'
-                                 ^^^
+3.7.7: b'"\x8e\x0b\x03-\xbc\x94a\x05\x02\xf6K\xd0\xcc\xcc\xda,\xd22\xcdL<\xd7sk4\x03\xe62\x9e\x8e\x12\x03\x03\x03'
+                                 ^^^
```

**Comment by webknjaz** [comment]
Looks like it's reproducible w/ the nightly Python build: https://travis-ci.org/github/cherrypy/cherrypy/jobs/674223158#L569.

**Comment by thesamesam** [comment]
We've hit the same downstream in [Gentoo](https://bugs.gentoo.org/727240).

**Comment by webknjaz** [comment]
I wonder if this may be related to fixing the compression level value in gzip headers:
* https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-7-final
* https://bugs.python.org/issue39389
* https://github.com/python/cpython/pull/18101

**Comment by webknjaz** [comment]
Confirmed: that's the root cause.

**Comment by webknjaz** [comment]
Reopening since the fix didn't work.

**Comment by webknjaz** [comment]
Oops, wrong issue.
