### ISSUE TITLE
SSL:  CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jeichert60** [cherrypy/cherrypy#1857]
I am doing a POST request having created a root CA and a client cert with the following Python code:

                    `post_data = {'resource': 'GetService', 'type': 'client', 'id': '42',
                                 'secret': '1357924680'} 
                    tok_resp = requests.post('https://supervisor.mdira.net:6789/token/', post_data,
                                             verify='CA/myCA.pem',
                                             cert=('client.crt', 'client.key'))

`
Using the debugger, it looks like I am making the connection but it raises the exception when I do the handshake @ ssl.pyI (SSLSocket._create(...)

I am using Python 3.7 on Windows.

**Comment by webknjaz** [comment]
Looks like you've posted this to a wrong repo. The requests lib issue tracker is elsewhere.
