### ISSUE TITLE
Hide Information Disclosure. Nmap is able to find out the server is hosted by CherryPy.

### ISSUE THREAD

**Issue by Rohitbels** [cherrypy/cherrypy#1859]
I ran a nmap command on a server hosted by Cherrypy version 4.

sudo nmap -sC -sS -sV -n -Pn --open xxx.xxx.xxx.xxx
This return a result:

Starting Nmap 7.80 ( https://nmap.org ) at 2020-06-01 14:33 India Standard Time
Nmap scan report for xxx.xxx.xxx.xxx
Host is up (0.34s latency).
Not shown: 999 filtered ports
Some closed ports may be reported as filtered due to --defeat-rst-ratelimit
PORT    STATE SERVICE  VERSION
443/tcp open  ssl/http **CherryPy wsgiserver**
|_http-title: Site doesn't have a title (text/plain).
| ssl-cert: Subject: commonName=*.xxx.com/organizationName=xxx, Inc./stateOrProvinceName=California/countryName=US
| Subject Alternative Name: DNS:*.xxx.com, DNS:xxx.com
| Not valid before: 2020-04-22T00:00:00
|_Not valid after:  2021-09-15T12:00:00
|_ssl-date: TLS randomness does not represent time

**I'm submitting a ...*
- [ ] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**What is the motivation / use case for changing the behavior?**
How can I hide this?

**Please tell us about your environment:**

- CherryPy version: 4
- Python version: 2.7
- OS: Ubuntu 18

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
Something like `cherrypy.config.update({'response.headers.server': 'Custom Server Name'})` should do.

**Comment by Rohitbels** [comment]
I am talking about is something else.
I have already configured server response header.

This is being displayed at some other level.

PORT     STATE  SERVICE   VERSION
443/tcp open   ssl/http    **CherryPy wsgiserver**

**Comment by webknjaz** [comment]
@Rohitbels well, I don't know what your app does so it's hard to guess what you expose. Maybe you have it in dev mode as opposed to production and it shows tracebacks on non-existing pages. Also, the default page 404 probably mentions it as well. Besides version 4 is ancient so maybe there's something else an such a retro env. Try upgrading as we don't support that one for many years already.

**Comment by FooBar007** [comment]
@webknjaz I don't think it's a version issue. I'm also finding the same issue using `nmap` - which came as a security vulnerability in a pentest report. FWIW, we are using the latest version of CherryPy which is not running in dev mode.

After reading your comment, we also tried using `cherrypy.config.update({'response.headers.server': 'Custom Server Name'})`, but unfortunately, the `nmap` output still reveals CherryPy wsgiserver.

**Comment by webknjaz** [comment]
I have no idea how that happens. For us to have anything actionable you need to figure out how exactly that works.
