### ISSUE TITLE
SSL.WantReadError occurs when connected client is interrupted and crashes the cherrypy server 

### ISSUE THREAD

**Issue by kmohite14** [cherrypy/cherrypy#1871]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
Report bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/72913986/96102494-35a8dc00-0ef4-11eb-9955-b107be01bae3.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
![image](https://user-images.githubusercontent.com/72913986/96102438-26c22980-0ef4-11eb-97a8-6813ec780c91.png)

**What is the expected behavior?**
To see the application running without crashing. The server is crashing when the connected client is interrupted.

**What is the motivation / use case for changing the behavior?**
The application should work seamlessly 

**Please tell us about your environment:**

- Cheroot version: 8.3.0
- CherryPy version: 18.5.0
- Python version: 3.6.8
- OS: Linux 3.10.0-1062.4.1.el7.x86.64
- Browser: Chrome

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
Please send text, not pictures with small fonts. We need searchable and copy-pastable content to work with.
