### ISSUE TITLE
Cherrypy Sessions Refreshing After Http Redirect

### ISSUE THREAD

**Issue by bryanbrown740** [cherrypy/cherrypy#1876]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
I'm using Cherrypy with python-saml / onelogin. My setup is similar to the one in the article [here.](https://medium.com/@gohberg/okta-authentication-using-saml-simplified-python-version-74ea9d5b4be7)

I have handlers for urls `/` and `/saml`. At `/`, I check if `session[KEY]` exists. If it does, I render normally. Otherwise, I redirect to my SSO idp. The response is then posted to `/saml`. At `/saml`, I set `session[KEY]` with user specific data. Then I redirect to `/`.

The session id cookie obtained at `/saml` is always replaced by a new session id upon redirection to `/`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
```python
import cherrypy
import urllib
from onelogin.saml2.auth import OneLogin_Saml2_Auth
from onelogin.saml2.utils import OneLogin_Saml2_Utils

SAML_PATH = 'path_to_saml_config'
# structure is 
# saml  - certs/
#       - settings.json

CONF = {
    'global': {
        'server.socket_host': '0.0.0.0',
        'server.socket_port': 8000,
        'server.ssl_certificate' : 'path_to_cert',
        'server.ssl_private_key' : 'path_to_key',
        'server.ssl_module' : 'builtin'
    },
    '/': {
        'tools.sessions.on': True
    }
}

class SSO:

    def __init__(self):
        pass

    def init_saml_auth(self, saml_req):
        auth = OneLogin_Saml2_Auth(saml_req, custom_base_path=SAML_PATH)
        return auth

    def get_saml_req(self, request):
        parsed_url = urllib.parse.urlparse(request.base)
        host = parsed_url.hostname
        port = parsed_url.port
        return {
        'https': 'on',
        'http_host': host,
        'script_name' : request.path_info,
        'server_port': port,
        'get_data': request.params.copy(),
        'post_data': request.params.copy()
        }

    @cherrypy.expose
    def index(self, **kwargs):
        # Logged in if session data, so render normally
        if 'samlUserData' in cherrypy.session:
            return "Authentication worked, great job!"
        else:
            saml_req = self.get_saml_req(cherrypy.request)
            auth = self.init_saml_auth(saml_req)
            raise cherrypy.HTTPRedirect(auth.login())

    @cherrypy.expose
    def saml(self, **kwargs):
        # Assertion Consumer Service
        saml_req = self.get_saml_req(cherrypy.request)
        auth = self.init_saml_auth(saml_req)
        auth.process_response()
        errors = auth.get_errors()
        if not errors
            if auth.is_authenticated():
                # Set session atributes
                cherrypy.session['samlUserData'] = auth.get_attributes()
                raise cherrypy.HTTPRedirect("/")
                # Redirecting, the session id changes, and session data is unavailable 
            else:
                pass
        else:
            pass

if __name__ == "__main__":
    cherrypy.quickstart(SSO(), '/', config=CONF)
```

**What is the expected behavior?**
The session / session data set at /saml would persist to the redirect to /.

**What is the motivation / use case for changing the behavior?**
This seems unintuitive and the session data should be persisted

**Please tell us about your environment:**

- CherryPy version: 18.6.0
- Python version: 3.6.12
- OS: Ubuntu
- Browser: Edge, Chrome, Firefox

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
@bryanbrown740 Are you implying that when the redirect `/saml -> /` happens, the `/saml` handler does not set the cookie? Have you verified that the HTTP response (the one with a redirect) contains a cookie header with the session data?

**Comment by webknjaz** [comment]
Also, it'd be useful to have some reproducer. It must be minimalistic, without any third-parties or things that are unnecessary to trigger the demonstrated behaviour.

**Comment by bryanbrown740** [comment]
Closing this issue, as I think this is actually an issue with an SSL certificate or a browser implementation issue.  In some cases in firefox, the redirect (code 303) from /saml to / seems to be keeping the POST method instead of forcing a GET. This seems to start a new session, causing the above.
