### ISSUE TITLE
Reenable four tests under continuous integration

### ISSUE THREAD

**Issue by cclauss** [cherrypy/cherrypy#1878]
Related to #1877 

**I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
https://github.com/cherrypy/cherrypy/pull/1877/files did `pytest.skipif()` on four tests when run under continuous integration.
* [ ] cherrypy/test/test_bus.py -- test_wait_publishes_periodically() on macOS
* [ ] cherrypy/test/test_states.py --test_1_Restart()
* [ ] cherrypy/test/test_states.py -- test_2_KeyboardInterrupt()
* [ ] cherrypy/test/test_tools.py -- testCombinedTools()

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

**What is the expected behavior?**
pytest passes these four tests.

**What is the motivation / use case for changing the behavior?**
Test coverage is  good thing.

**Please tell us about your environment:**

CircleCI

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
`skipif` should only be used if something cannot be tested. If the env is okay, tests should be marked with `xfail` instead so they are executed but their failures don't influence the overall outcome.

**Comment by webknjaz** [comment]
On a side note, I'm not sure when I'll get time but I'll probably be dumping some of the CIs.

**Comment by cclauss** [comment]
These tests hang the system so xfail is not better than the current unmodified code.

**Comment by webknjaz** [comment]
I commented on the PR but I'll also duplicate here. TL;DR: you can use `xfail` with `run=False` or (even better) with `pytest-forked` applied via a marker on the test.
