### ISSUE TITLE
installation - `collision between `python3.8-jaraco.functools-3.0.1/lib/python3.8/site-packages/jaraco/__pycache__/__init__.cpython-38.pyc' 

### ISSUE THREAD

**Issue by InLaw** [cherrypy/cherrypy#1903]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [X] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
a sub-optimal packaging which gets compensated by pip 

**What is the current behavior?**
At installation you get 
collision between e.g. `python3.8-jaraco.functools-3.0.1/lib/python3.8/site-packages/jaraco/__pycache__/__init__.cpython-38.pyc' and python3.8-jaraco.collections-3.0.0/lib/python3.8/site-packages/jaraco/__pycache__/__init__.cpython-38.pyc'`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
nix-shell -p nixFlakes --run "nix run github:davhau/mach-nix#with.cherrypy --show-trace "
https://github.com/DavHau/mach-nix/issues/248

**What is the expected behavior?**
There shouldn't be two different python packages have a module with the same name / files

**What is the motivation / use case for changing the behavior?**
Cleaner implementation e.g. for more reproducibility 

**Please tell us about your environment:**

- CherryPy version: 18.6.0
- Python version: 3.8.8
- OS: Linux 5.9.15 / NixOS
(- Browser: [all ])

**Comment by webknjaz** [comment]
Thanks for documenting this!

FWIW the only supported installer on our side is pip. We don't package anything for NixOS so this is really something that the packagers for that ecosystem should take care of.

Also, you're pointing at the dependencies, not CherryPy itself so it's not even related to anything in this repository.

As a side note, this is a standard way of doing namespaces in the Python packaging world. See https://packaging.python.org/guides/packaging-namespace-packages/.

Back in the times of Python 2, this was the only way of producing the namespace packages. Nowadays, Python 3 supports implicit namespaces so it is theoretically possible to avoid putting `__init__.py` there. This is a good solution for the new namespaces. But these two types of packaging are incompatible with each other. The whole `jaraco.*` namespace has to use the same way of doing things or things will break, one cannot just migrate one package or part of them to the new way. Also, even if everything's migrated, people doing updates from the older versions of the packages in this namespace will experience terrible problems so it's not really possible to do anything in this namespace without breaking a lot of people out there.

**Comment by InLaw** [comment]
you don't need to change it right away
- why not do it in the next major release?

----

"only supported installer on our side is pip"
"We don't package anything for NixOS"
- it's not about packaging cherrypy for anything different than pip 

Even so NixOS seems to be "used"
- it is only the foundation (for mach-nix) but pip is the package manager which takes care of the installation of pypi packages at the end 


"pointing at the dependencies, not CherryPy itself so it's not even related to anything in this repository."
- have a look at the current dependency tree 

```
cherrypy - 18.6.0 - wheel
├── more-itertools - 8.6.0 - wheel
├── cheroot - 8.5.2 - wheel
│   ├── six - 1.15.0 - wheel
│   ├── jaraco.functools - 3.1.0 - wheel
│   │   └── more-itertools - 8.6.0 - wheel
│   └── more-itertools - 8.6.0 - wheel
├── portend - 2.7.0 - wheel
│   └── tempora - 4.0.1 - wheel
│       ├── jaraco.functools - 3.1.0 - wheel -> ...
│       └── pytz - 2020.5 - wheel
├── zc.lockfile - 2.0 - wheel
│   └── setuptools - 47.3.1 
└── jaraco.collections - 3.1.0 - wheel
    ├── jaraco.classes - 3.1.0 - wheel
    │   └── more-itertools - 8.6.0 - wheel
    └── jaraco.text - 3.4.0 - wheel
        └── jaraco.functools - 3.1.0 - wheel -> ...
```

**Comment by webknjaz** [comment]
I'm not sure what you wanted to say by this. We don't maintain the `jaraco.*` namespace. But FWIW packaging that using Nix is a responsibility of the Nix packager, we have nothing to do with that.

> you don't need to change it right away

> why not do it in the next major release?

Even if @jaraco upgrades the packaging method in all of 164 packages in the namespace (https://pypi.org/search/?q=jaraco), it will still cause serious problems. It is impossible to safely do this in the current Pip ecosystem. But whoever packages these projects for Nix, can patch out the `__init__.py` file if necessary.

**Comment by webknjaz** [comment]
If you can reproduce this by using pip solely, then it's a bug. If you can't — it's not.
If it's really a packaging bug, please report it to the corresponding projects where it appears (not CherryPy which is unrelated to how those projects are packaged).

**Comment by jaraco** [comment]
For what it’s worth, the jaraco.* packages are migrating to native namespace packages, which should address this issue.

This issue has been [reported previously](https://github.com/jaraco/jaraco.functools/issues/16). But the outcome there is the same as webknjaz has described, especially because there’s nothing CherryPy can do short of eliminating this dependency.
