### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [cherrypy/cherrypy#1907]
I see some changes already commited related to some test suite issues ond other things with which I've been dealing recently.
Is it possible to make new release of the cherrypy soon?

**Comment by webknjaz** [comment]
I'll release it when I'll have time to fix the whole CI/CD disaster. No ETA so far. But TL;DR [Travis CI is dead](https://webknjaz.me/prose/et-tu-brute-use-travis-ci-for-foss-no-more/) but the automatic release was only configured there.
At some point, I'll make the automation similar to Cheroot.
