### ISSUE TITLE
performance tuning on raspberry pi 1st generation

### ISSUE THREAD

**Issue by Blindfreddy** [cherrypy/cherrypy#1908]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

performance bug

**What is the current behavior?**

CherryPy consumes about 15-20% CPU on a single-core raspberry pi 1st generation when idle, ie. no requests being processed at all. To reduce this, I tried various configuration adjustments, but to no avail.  How can I reduce this ?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
```python
>>> import cherrypy
>>> cherrypy.quickstart()
[29/Apr/2021:14:14:22] ENGINE Listening for SIGTERM.
[29/Apr/2021:14:14:22] ENGINE Listening for SIGHUP.
[29/Apr/2021:14:14:22] ENGINE Listening for SIGUSR1.
[29/Apr/2021:14:14:22] ENGINE Bus STARTING
[29/Apr/2021:14:14:22] ENGINE Started monitor thread 'Autoreloader'.
[29/Apr/2021:14:14:23] ENGINE Serving on http://127.0.0.1
[29/Apr/2021:14:14:23] ENGINE Bus STARTED
```

top output:
```console
Tasks:  85 total,   1 running,  84 sleeping,   0 stopped,   0 zombie
%Cpu(s): 23.9 us,  8.9 sy,  0.0 ni, 66.6 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
MiB Mem :    430.1 total,    152.9 free,     76.2 used,    201.0 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.    297.3 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                             
10674 root      20   0  131484  21240   8188 S  18.5   4.8   0:45.63 python3                                                                                             
```

**What is the expected behavior?**

when idle, no noticeable CPU consumption even on a single-core raspberry pi (or generally 'low-performance devices')

**What is the motivation / use case for changing the behavior?**

useability on low-performance devices

**Please tell us about your environment:**

- Cheroot version: ?
- CherryPy version: 18.6.0
- Python version: 3.9.2
- OS: Raspbian GNU/Linux 10 (buster)
- Browser: [all ]

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

have tried to reduce server.thread_pool to 1, unfortunately no CPU reduction

**Comment by cyraxjoe** [comment]
I remember that some changes were introduced in cheroot (cherrypy's web server) that caused a lot of CPU usage when idle. 

Are you using a virtualenv? Try forcing the installation of an older cheroot with `pip install cheroot==8.2.1` and see if you have any improvements.

**Comment by Blindfreddy** [comment]
Yes, using venv. Downgraded as suggested, unfortunately same situation:

```
#pip list | grep cher
cheroot                8.2.1

#top
Tasks:  87 total,   1 running,  86 sleeping,   0 stopped,   0 zombie
%Cpu(s): 29.1 us,  7.4 sy,  0.0 ni, 63.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :    430.1 total,     84.3 free,    110.4 used,    235.4 buff/cache
MiB Swap:    100.0 total,     98.2 free,      1.8 used.    261.6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                             
18032 root      20   0  197576  27504   8928 S  20.1   6.2   1:53.48 python
```

**Comment by webknjaz** [comment]
@Blindfreddy you could try using https://github.com/benfred/py-spy to generate a flame graph and see what consumes the most resources. They have platform wheels for `armv7l` — if that's what you have, upgrade your pip and it'll pick up a manylinux2014 wheel seamlessly. If not, you may have to set up a build toolchain so that it'll get compiled from sdist (requires Rust).

**Comment by webknjaz** [comment]
You could also try installing older CherryPy versions to see if that's a regression or it's always been like this in that env.

**Comment by Blindfreddy** [comment]
@webknjaz  thanks for the suggestion, old Pi is an armv6l.  I'll try downgrading further. But even if it's always been that way, it should never have been that way in the first place:  before introducing CherryPy I used the stdlib httpserver in my app and it consumed no noticeable resources when idle - granted it is not production grade but still shows that it's possible to consume no resources when idle.

**Comment by webknjaz** [comment]
Sure, but if it's a regression, it'd be easier to bisect what caused it. Without more data it could be anything.

**Comment by Blindfreddy** [comment]
I tried to downgrade to 6.1 but cherrpypy won't even start with a recent python version. Next I'll the the py-spy to narrow down the problem area.

**Comment by Blindfreddy** [comment]
Haven't had time to use py-spy but thought I'd reduce the threadpool from default 10 to 1:   sadly no change, but at least now it's clear that the worker threads aren't the root cause. Next I'll turn off the Autoreloader thread. Keep you posted.

**Comment by MichaIng** [comment]
You might want to try CherryPy<9.0.0, as this is where the engine was switched from wsgiserver to cheroot: https://github.com/cherrypy/cherrypy/blob/main/CHANGES.rst#v900
At least in our project that version works fine on Python 3.9.

**Comment by webknjaz** [comment]
> You might want to try CherryPy<9.0.0, as this is where the engine was switched from wsgiserver to cheroot: [https://github.com/cherrypy/cherrypy/blob/main/CHANGES.rst#v900](https://github.com/cherrypy/cherrypy/blob/main/CHANGES.rst?rgh-link-date=2021-07-19T19%3A00%3A34Z#v900)

It shouldn't matter. The "switch" was just moving code from one place to another w/o changes. It was an organizational change, not a functional one. Of course, over time it got refactored but I don't believe it'd influence stuff this much.
OTOH, it may be a good idea to check if the use of cheroot alone produces a similar amount of load or not. The invocation examples are here: https://cheroot.readthedocs.io/en/latest/pkg/cheroot.cli.html.

**Comment by webknjaz** [comment]
@Blindfreddy could you check this out https://github.com/cherrypy/cheroot/issues/378?

**Comment by MichaIng** [comment]
Yes, I checked back what the reason for us was to stick with CherryPy<9 and it was idle CPU usage as well. So I narrowed it down to two PRs which changed the connection management and even found a workaround by changing a single timeout value in the code. But I have not enough insights to know whether this has other negative impact. But at least [the initial reason to lower this timeout](https://github.com/cherrypy/cheroot/pull/308) (which was the change for the major increased idle load) has been [addressed later in a better way](https://github.com/cherrypy/cheroot/pull/311), so it may be indeed correct to raise it back to what it was. To test, on latest CherryPy + cheroot, when installed via pip:
```sh
sed -i 's/timeout=0\.01/timeout=0\.1/' /usr/local/lib/python3.9/dist-packages/cheroot/connections.py
```
Adjust path, when done on other Python version, of course.

**Comment by Blindfreddy** [comment]
https://github.com/cherrypy/cheroot/issues/378 seems to describe the same problem so happy to merge the two.

Assuming the timeout is the root cause I'd also suggest to make it configurable because nowadays low-performance SBCs are pretty rare and in many cases faster response times are preferable - e.g. I never noticed the problem on my high-performance development laptop....

**Comment by MichaIng** [comment]
With https://github.com/cherrypy/cheroot/pull/352 it would then be the `expiration_interval` that can be set for the `HTTPServer` class already and defaults to 0.5 seconds. While it is probably not yet a perfect solution, as I noted in the other issue, it would solve the idle CPU load (when indeed the reason in your cases is the same) with the default value already 🙂.

**Comment by MichaIng** [comment]
This has now been merged here: https://github.com/cherrypy/cheroot/pull/401
Testing/verifying the idle CPU usage benefits would be welcome.

On Windows systems, sadly a capped timeout needs to stay, as the connection handler `select()` function somehow on Windows does not return as fast as a connection is detected. The timeout however has been increased from `0.01` to `0.05` seconds, which seems to be a good balance between idle CPU usage and max delay for processing an incoming connection. For Raspberry Pi with Linux however this doesn't play a role since `select()` returns immediately once incoming connections appear. That `expiration_interval` (defaulting to `0.5` seconds) needs to be kept as well on Linux is to assure that expired connections are disconnected and removed in time, since new connections and expiry are done within the same loop.

**Comment by webknjaz** [comment]
@Blindfreddy up for doing more testing?

**Comment by Blindfreddy** [comment]
@webknjaz Sure thing, just let me know the specifics of what to test, please.

**Comment by MichaIng** [comment]
Upgrade your CherryPy and cheroot to the latest version and check whether idle CPU usage on RPi 1 is now fine.

**Comment by Blindfreddy** [comment]
Apologies for the delay, I'll try to test it in the next fortnight and report.

**Comment by Blindfreddy** [comment]
Finally got around to testing it, here are the results:

CPU utilization is now down from ~19% to ~10%, which is a major improvement but still not great considering there is no load / are no connections. Is this now tuneable with the `expiration_timeout` setting ? If so, I can run additional tests.

Supporting information:
```
Tasks:  88 total,   1 running,  87 sleeping,   0 stopped,   0 zombie
%Cpu(s): 10.7 us,  2.7 sy,  0.0 ni, 86.3 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 s
MiB Mem :    429.5 total,     99.9 free,     58.2 used,    271.4 buff/cache
MiB Swap:    100.0 total,     99.7 free,      0.2 used.    315.5 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
 4838 andrev    20   0  131196  22120   8764 S   9.8   5.0   1:34.01 python   
  247 avahi     20   0    7032   3292   2704 S   2.0   0.7   2:31.65 avahi-da+
 4826 andrev    20   0   11224   3212   2528 R   1.3   0.7   0:15.22 top      
   10 root      20   0       0      0      0 S   0.3   0.0   0:10.82 ksoftirq+
 4145 root      20   0       0      0      0 I   0.3   0.0   0:21.71 kworker/+
```

Steps to reproduce:
1. Install raspberrypi os lite (bullseye 32bit) on a pi 1st generation - single core
2. create a virtual environment and activate it
3. pip install cherrypy
4. cherrypy.quickstart() in a python interactive interpreter

```
>>> import cherrypy
>>> cherrypy.quickstart()
[19/Dec/2022:08:25:10] ENGINE Listening for SIGTERM.
[19/Dec/2022:08:25:10] ENGINE Listening for SIGHUP.
[19/Dec/2022:08:25:10] ENGINE Listening for SIGUSR1.
[19/Dec/2022:08:25:10] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[19/Dec/2022:08:25:10] ENGINE Started monitor thread 'Autoreloader'.
[19/Dec/2022:08:25:10] ENGINE Serving on http://127.0.0.1:8080
[19/Dec/2022:08:25:10] ENGINE Bus STARTED
```

```
~/pyvenv $ pip list | grep -i che
cheroot            9.0.0
CherryPy           18.8.0
```

```
~/pyvenv $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 000e
Serial		: 00000000763dd984
Model		: Raspberry Pi Model B Rev 2
```

**Comment by MichaIng** [comment]
Yes `expiration_timeout` is now also the connection handler loop interval, which causes idle load in the first place. Since that was raised from 0.01 to 0.5 (x50), I would have expected much better than halved idle CPU utilisation, but at least. Would be great if you could play with this, e.g. whether increasing the interval up to e.g. 5 (seconds) further reduces idle load.

I still had ideas to further reduce what the connection handler does in one loop, merging lookup/pickup for new connections with closing/dropping of expired ones. But not sure when I find time to pick this up again.

**Comment by Blindfreddy** [comment]
Ok happy to play around it with, but I don't actually know how to set this variable.  Couldn't find it in cherrypy, config, tools.   Would you kindly advise how I can set it ?

Many thanks.

**Comment by webknjaz** [comment]
@Blindfreddy if you use Cheroot directly, you can set it on the `HTTPServer` instance (https://github.com/cherrypy/cheroot/blob/86fb3adef765d7d08524efb341fcf693e9b1f0bf/cheroot/server.py#L1527).
When using CherryPy, it could be exposed as `server.connection_expiration_timeout` but currently it's not. Somebody would have to send a PR bypassing the corresponding setting @ https://github.com/cherrypy/cherrypy/blob/93b3beb/cherrypy/_cpwsgi_server.py#L67-L79 and https://github.com/cherrypy/cherrypy/blob/93b3beb/cherrypy/_cpserver.py#L23-L155 (here's an example patch doing this for the peercred settings — https://github.com/cherrypy/cherrypy/commit/86ebb75e48ee5c4c7de224a99c0e8624d874c663).

I suppose you could monkey-patch this by importing `cheroot` before `cherrypy` and doing something like:
```python
import cheroot.server
cheroot.server.HTTPServer.expiration_timeout = 0.000001

import cherrypy
...
```

**Comment by Blindfreddy** [comment]
Have tested it, bottom line is that the `expiration_timeout` makes no difference at all to the idle utilization. I tested it with values ranging from 1e-10 to 10,000 (ie. 1e4) and the cpu utilization is always ~10%.

Here is the script I wrote, perhaps someone else still has a raspberry pi 1st generation to confirm:

```python
(pyvenv) andrev@raspberrypi:~/pyvenv $ cat expiration_timeout_test.py 
timeo = float(input("enter expiration timeout: "))
import cheroot.server
cheroot.server.HTTPServer.expiration_timeout = timeo
import cherrypy
cherrypy.quickstart()
```

So either the parameter is not really changed by the above monkey patch method, or it truly makes no difference to the idle cpu utilization.

**Comment by MichaIng** [comment]
> So either the parameter is not really changed

That one, I'm sure. Isn't it needed to change the value for the particular cheroot instance CherryPy loads? Try this instead:
```python
timeo = float(input("enter expiration timeout: "))
import cheroot.server
myserver = cheroot.server.HTTPServer()
myserver.expiration_timeout = timeo
import cherrypy
cherrypy.server.httpserver = CPHTTPServer(myserver)
cherrypy.quickstart()
```

**Comment by Blindfreddy** [comment]
```
Traceback (most recent call last):
  File "/home/andrev/pyvenv/expiration_timeout_test.py", line 6, in <module>
    cherrypy.server.httpserver = CPHTTPServer(myserver)
NameError: name 'CPHTTPServer' is not defined
```

**Comment by MichaIng** [comment]
Ah sorry, this one:
```python
timeo = float(input("enter expiration timeout: "))
import cheroot.server
myserver = cheroot.server.HTTPServer()
myserver.expiration_timeout = timeo
import cherrypy
cherrypy.server.httpserver = cherrypy._cpnative_server.CPHTTPServer(myserver)
cherrypy.quickstart()
```

**Comment by webknjaz** [comment]
> Isn't it needed to change the value for the particular cheroot instance CherryPy loads?

I don't think that CherryPy sets this value on the instance at all, so if you update the class attribute, the instance attribute will inherit it, unless I'm missing something.

**Comment by MichaIng** [comment]
Sounds logic, but I don't know whether editing a classes attribute that way works, if the same class is imported again from another script. No professional programmer here 😅.

I (and others) tested it with cheroot alone up and down, as well as with a project which uses CherryPy (changing `expiration_timeout` in cheroot code directly) and the impact of `expiration_timeout` was highly significant. And the rationale behind it is trivial. So it is basically impossible that a successfully applied `expiration_timeout` has no effect on idle CPU usage 🤔. Of course the values need to be in a range where it shows a difference, like comparing `0.01`s with `1`s.

**Comment by Blindfreddy** [comment]
```
Traceback (most recent call last):
  File "/home/andrev/pyvenv/expiration_timeout_test.py", line 6, in <module>
    cherrypy.server.httpserver = cherrypy._cpnative_server.CPHTTPServer(myserver)
AttributeError: module 'cherrypy' has no attribute '_cpnative_server'
```

**Comment by MichaIng** [comment]
Hmm, comparing with instructions here: https://github.com/cherrypy/cherrypy/blob/main/docs/advanced.rst#no-need-for-the-wsgi-interface
Looks like the `CPHTTPServer` needs to be imported separately.
```python
timeo = float(input("enter expiration timeout: "))
import cheroot.server
myserver = cheroot.server.HTTPServer()
myserver.expiration_timeout = timeo
import cherrypy
from cherrypy._cpnative_server import CPHTTPServer
cherrypy.server.httpserver = CPHTTPServer(myserver)
cherrypy.quickstart()
```

**Comment by Blindfreddy** [comment]
Now a different error:

```
Traceback (most recent call last):
  File "/home/andrev/pyvenv/expiration_timeout_test.py", line 7, in <module>
    cherrypy.server.httpserver = CPHTTPServer(myserver)
  File "/home/andrev/pyvenv/lib/python3.9/site-packages/cherrypy/_cpnative_server.py", line 133, in __init__
    server_name = (self.server_adapter.socket_host or
AttributeError: 'HTTPServer' object has no attribute 'socket_host'
```

**Comment by MichaIng** [comment]
I managed it this way:
```python
#!/usr/bin/python3
timeo = float(input("enter expiration timeout: "))
import cheroot.server
myserver = cheroot.server.HTTPServer(('127.0.0.1',8080), '192.168.1.1')
myserver.expiration_timeout = timeo
import cherrypy
cherrypy.server.instance = myserver
cherrypy.quickstart()
```
But since I couldn't see any effect, I checked back everything and we simply used a wrong attribute: It is `expiration_interval`. Somewhere in comments above `expiration_timeout` was accidentally introduced, likely mixed because `select_timeout` is the name of the variable for the internal connection handler timeout, which equals the passed `expiration_timeout` now to reduce idle load. And I didn't notice 😅. With this, also the simple approach to edit the class directly works:
```python
timeo = float(input("enter expiration timeout: "))
import cheroot.server
cheroot.server.HTTPServer.expiration_interval = timeo
import cherrypy
cherrypy.quickstart()
```

**Comment by Blindfreddy** [comment]
Makes sense and I changed the script as per above and tried out different values, refer table below. Bottom line is that CPU util bottoms out at 10% with a setting of 0.1 or larger.

| timeout | cpu util
| ---- | ---- 
| 0.00001 | 50%
| 0.001 | 48%
| 0.01 | 16%
| 0.1 | 10%
| 1 | 10%
| 10 | 9%
| 1000 | 9%

Something I noticed with values above 0.1 is that the CPU util momentarily drops to ~6% every 10-15 seconds and then climbs back to 10%. So it seems there is something causing the base load of around 10% that is independent of the timeout.
Food for thought.....

**Comment by MichaIng** [comment]
At least an enhancement, but not as great as we were hoping. If you are using CherryPy < 9 (which does not use `cheroot`), is the idle load around 9% as well?

Would be interesting to know what causes those ~9% when the connection handler stands still. Probably there is another loop which can be enhanced in a similar way. Does someone have an idea how to identify such in Python? Some verbose mode or so?

**Comment by Blindfreddy** [comment]
Happy to try with CherryPy < 9, could someone advise which raspbian / debian version corresponds so I can easily install it ?  Or alternatively advise how to install CP < 9 on a current debian version ?

**Comment by webknjaz** [comment]
`pip install 'cherrypy < 9'` in a fresh virtualenv?

**Comment by Blindfreddy** [comment]
That worked and CPU utilization out of the box is ~8%

```
(cp8test) andrev@raspberrypi:~/pyvenv/cp8test $ pip list | grep -i cherry
CherryPy      8.9.1
(cp8test) andrev@raspberrypi:~/pyvenv/cp8test $ python
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cherrypy
>>> cherrypy.quickstart()
[02/Feb/2023:13:49:31] ENGINE Listening for SIGTERM.
[02/Feb/2023:13:49:31] ENGINE Listening for SIGHUP.
[02/Feb/2023:13:49:31] ENGINE Listening for SIGUSR1.
[02/Feb/2023:13:49:31] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[02/Feb/2023:13:49:31] ENGINE Started monitor thread 'Autoreloader'.
[02/Feb/2023:13:49:31] ENGINE Started monitor thread '_TimeoutMonitor'.
[02/Feb/2023:13:49:32] ENGINE Serving on http://127.0.0.1:8080
[02/Feb/2023:13:49:32] ENGINE Bus STARTED
```

```
top - 13:50:38 up  1:27,  3 users,  load average: 0.22, 0.20, 0.17
Tasks:  90 total,   1 running,  89 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.0 us,  2.3 sy,  0.0 ni, 89.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :    429.5 total,    253.1 free,     70.0 used,    106.4 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.    309.0 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                            
 1526 andrev    20   0  136508  19600   8264 S   8.2   4.5   0:11.85 python           
```

**Comment by MichaIng** [comment]
Okay, so only slightly better. With some optimisations to the connection handler I have in mind, we can get there or better again. But not sure when I find time.

But since the issue (compared to pre-cheroot era) is solved, I think this issue can be closed.

**Comment by Blindfreddy** [comment]
I agree, 8% CPU utilization seems to be the minimum reference, even if that seems high considering it is idle.
Still useful to optimize further considering there are more and more low-performance boards out there.
