### ISSUE TITLE
Threading related deprecation warnings in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [cherrypy/cherrypy#1914]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

Python 3.10 deprecates camelCase aliases in threading module.

Ref : python/cpython#25174

Similar to https://github.com/cherrypy/cheroot/issues/369

**What is the current behavior?**

```
cherrypy/cherrypy/process/plugins.py:            if self.thread is not threading.currentThread():
cherrypy/cherrypy/process/plugins.py:        if threading.activeCount() != 1:
cherrypy/cherrypy/process/wspbus.py:                    t != threading.currentThread() and
```

**What is the expected behavior?**

activeCount -> active_count
currentThread -> current_thread

**What is the motivation / use case for changing the behavior?**

Fixes deprecation warnings in Python 3.10

**Please tell us about your environment:**

- Cheroot version: X.X.X
- CherryPy version: master branch
- Python version: 3.10
- OS: XXX
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hroncok** [comment]
There is also:

```
DeprecationWarning: getName() is deprecated, get the name attribute instead
DeprecationWarning: setName() is deprecated, set the name attribute instead
```

Funnily enough, the entire pytest exits with code 70 with no useful information when those happen.

This pytest filterwarning seems to work as a temporary workaround:

```
ignore:[gs]etName|currentThread:DeprecationWarning
```
