### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [cherrypy/cherrypy#1941]
Hey there!

I belong to an open source security research community, and a member (@scara31) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by webknjaz** [comment]
Thanks for raising this! I didn't realize that the CherryPy repos don't have this file (I tend to create it in the new projects right away).

I've just created a forwarding rule for `security` AT [this framework] dot `dev` for the reports and I'll keep this issue open until I get to creating the `SECURITY.rst` document.

As for the issue, I have created a draft advisory in this repository and invited @Scara31 as a collaborator so they should be able to fill out the details on that page. It also allows collaborating on the patch.

Thanks again for following the responsible disclosure principles!

**Comment by jaraco** [comment]
Someone sent an email to `team@` requesting guidance. Let's get this issue fixed.

**Comment by jaraco** [comment]
In my other projects, I rely on Tidelift for security disclosure. Probably CherryPy should too. I'm going to assume that for now, but webknjaz - if you have something else in mind for a security workflow, please document it in SECURITY.md.

**Comment by webknjaz** [comment]
@jaraco I'd like to prefer GitHub, now that it's enabled, as it won't be a problem for most people as virtually everyone has a GH account. It's also a good centralized location for access management, having secret branches and PRs. And it's usually a good idea to fill out the GitHub Advisory anyway — so why not let the reporters fill it out themselves with good collaboration interface right there. It also let's us credit GH accounts.
I'd go for `security@` as a fallback, to cover people not having GH accounts or not trusting it with sensitive data.
P.S. I also considered Tidelift but that causes more unnecessary burden in my experience. So I'd prefer the information flow to originate from GH and not the other way around..

**Comment by jaraco** [comment]
Feel free to change the process to your preference.

**Comment by webknjaz** [comment]
> Feel free to change the process to your preference.

Done: https://github.com/cherrypy/cherrypy/security/policy

**Comment by webknjaz** [comment]
@Scara31 @JamieSlome did you end up reporting it?
