### ISSUE TITLE
Application cannot restart when packaging cherrypy with pyinstaller

### ISSUE THREAD

**Issue by xfangfang** [cherrypy/cherrypy#1949]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

It's hard to say whether this is a bug or a feature request

**What is the current behavior?**

When using pyinstaller to package CherryPy, calling ` cherrypy.engine.restart() ` will cause a crash:

```python-traceback
[26/Feb/2022:21:04:15] ENGINE Stopped thread 'Autoreloader'.
[26/Feb/2022:21:04:15] ENGINE Removed handler for console events.
[26/Feb/2022:21:04:15] ENGINE Stopped thread 'IP_MONITOR_THREAD'.
[26/Feb/2022:21:04:15] ENGINE Bus STOPPED
[26/Feb/2022:21:04:15] ENGINE Bus EXITING
[26/Feb/2022:21:04:15] ENGINE Waiting for child threads to terminate...
[26/Feb/2022:21:04:15] ENGINE Bus EXITED
[26/Feb/2022:21:04:15] ENGINE Re-spawning
Exception in thread SERVICE_THREAD:
Traceback (most recent call last):
File "threading.py", line 973, in _bootstrap_inner
File "threading.py", line 910, in run
File "macast\server.py", line 198, in run
File "cherrypy\process\wspbus.py", line 369, in block
File "cherrypy\process\wspbus.py", line 405, in _do_execv
ValueError: execv() arg 2 must not be empty  
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

create demo.py:

```python
import cherrypy
class Root:
    @cherrypy.expose
    def index(self):
        cherrypy.engine.restart()
        return "restarting"
cherrypy.quickstart(Root(), '/')
```

```shell
pyinstaller demo.py
```

Open a CMD and run the dist/demo/demo.exe that you just built. You can get the error message by accessing port 8080 from browser.

**What is the expected behavior?**

CherryPy restart normally

**What is the motivation / use case for changing the behavior?**

When using the `cherrypy.engine.restart` function of CherryPy, if I run from the source code then it can be executed normally, but it cannot run normally after packaging with pyinstaller.

**Please tell us about your environment:**

- Cheroot version: 8.5.2
- CherryPy version: 18.6.1
- pyinstaller version: 4.9
- Python version: 3.9.6
- OS: Windows
- Browser: [all ]

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

Different results may be obtained in different Python environments:

python 3.7.9:
`self._get_true_argv()` in  `cherrypy/process/wspbus.py` works fine with pyinstaller.

python 3.9.6:
`self._get_true_argv()` return a empty list when packaging with pyinstaller.

This can solve my problem:

https://github.com/cherrypy/cherrypy/blob/541ab4942bd111b779680f1a168855051fcee55b/cherrypy/process/wspbus.py#L379-L389

I'm not clear how pyinstaller affects the process of obtaining argvs, but the repair will not affect the existing code:

```python
    def _do_execv(self):
        """Re-execute the current process.

        This must be called from the main thread, because certain platforms
        (OS X) don't allow execv to be called in a child thread very well.
        """
        try:
            args = self._get_true_argv()
        except NotImplementedError:
            """It's probably win32 or GAE"""
            args = []

        if len(args) == 0:
            args = [sys.executable] + self._get_interpreter_argv() + sys.argv
```

**Comment by webknjaz** [comment]
I don't think it ever worked under Pyinstaller. My understanding is that this is a packaging approach so it concerns the production mode. And the autorestart feature is something meant to be used in development. I'm not sure if it's a good idea to enable it in production even.

**Comment by webknjaz** [comment]
Hm.. it might be a bug after all. Although, with no tests in CI, it's not something that would be fixable.
