### ISSUE TITLE
RFE: Replace use of `pkg_resources` with `importlib.metadata`

### ISSUE THREAD

**Issue by kloczek** [cherrypy/cherrypy#1973]
See discussions:
[astropy/astropy#11091](https://github.com/astropy/astropy/pull/11091)
[pypa/pip#7413](https://github.com/pypa/pip/issues/7413)

```console
[tkloczko@devel-g2v cherrypy-18.7.0]$ grep pkg_resources -r
cherrypy/__init__.py:    import pkg_resources
cherrypy/__init__.py:    __version__ = pkg_resources.require('cherrypy')[0].version
cherrypy/test/helper.py:         import pkg_resources, re, sys; \
cherrypy/test/helper.py:            pkg_resources.load_entry_point(\
docs/conf.py:import pkg_resources
docs/conf.py:prj_dist = pkg_resources.get_distribution('cherrypy')
build/lib/cherrypy/__init__.py:    import pkg_resources
build/lib/cherrypy/__init__.py:    __version__ = pkg_resources.require('cherrypy')[0].version
build/lib/cherrypy/test/helper.py:         import pkg_resources, re, sys; \
build/lib/cherrypy/test/helper.py:            pkg_resources.load_entry_point(\
```

**Comment by Safihre** [comment]
@webknjaz Did you notice that these lines:
```python
try:
    __version__ = pkg_resources.require('cherrypy')[0].version
except Exception:
    __version__ = 'unknown'
``` 
actually take ages? 
It goes off and does all kind of logic to figure out the depency structure of `cherrypy` and seems to parse all installed modules..
Hopefully this can be simplified by using `importlib.metadat`.

**Comment by webknjaz** [comment]
@Safihre you're right. This should've been done long ago.

**Comment by Safihre** [comment]
Great @webknjaz 👍👍 now let's not wait another year to release it 🤣

**Comment by webknjaz** [comment]
@Safihre I identified a few incompatible changes post-merge: https://github.com/cherrypy/cherrypy/pull/1993#pullrequestreview-1793935270. Once they're addressed — why not.

**Comment by webknjaz** [comment]
And another one: https://github.com/cherrypy/cherrypy/pull/2006/files#r1435574215.
