### ISSUE TITLE
RTD deprecates use_system_packages

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1999]
From an email from RTD:

----

Hello,
--
You are receving this email because your Read the Docs project is impacted by an upcoming deprecation.Read the Docs used to pre-install common scientific Python packages like scipy, numpy, pandas, matplotlib  and others at system level to speed up the build process. However, with  all the work done in the Python ecosystem and the introduction of  "wheels", these packages are a lot easier to install via pip install and these pre-installed packages are not required anymore. If you have Apt package dependencies, they can be installed with build.apt_packages.With  the introduction of our new "Ubuntu 20.04" and "Ubuntu 22.04" Docker  images, we stopped pre-installing these extra Python packages and we  encouraged users to install and pin all their dependencies using a requirements.txt file. We have already stopped supporting "use system packages" on these newer images.We are removing the "use system packages" feature on August 29th. Make sure you are installing all the required dependecies to build your project's documentation using a requirements.txt file and specifying it in your .readthedocs.yaml.Here you have an example of the section required on the .readthedocs.yaml configuration file:python:   install:     - requirements: docs/requirements.txt The content of docs/requirements.txt would be similar to:scipy==1.11.1 numpy==1.25.2 pandas==2.0.3 matplotlib==3.7.2 We are sending you this email  because you are a maintainer of the following projects that are affected  by this removal. Either using "Use system package" checkbox in the  Admin UI, or the config key python.sytem_packages or python.use_system_site_packages in your .readthedocs.yaml file:cherrypytwineRead more about this in our Reproducible builds guide for more details.
Keep documenting,Read the Docs

Hello,

You are receving this email because your Read the Docs project is impacted by an upcoming deprecation.

Read the Docs used to pre-install common scientific Python packages like scipy, numpy, pandas, matplotlib and others at system level to speed up the build process. However, with all the work done in the Python ecosystem and the introduction of "wheels", these packages are a lot easier to install via pip install and these pre-installed packages are not required anymore. If you have Apt package dependencies, they can be installed with [build.apt_packages](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages).

With the introduction of our new "Ubuntu 20.04" and "Ubuntu 22.04" Docker images, we stopped pre-installing these extra Python packages and we encouraged users to install and pin all their dependencies using a requirements.txt file. We have already stopped supporting "use system packages" on these newer images.

We are removing the "use system packages" feature on August 29th. Make sure you are installing all the required dependecies to build your project's documentation using a requirements.txt file and specifying it in your .readthedocs.yaml.

Here you have an example of the section required on the .readthedocs.yaml configuration file:

python:
  install:
    - requirements: docs/requirements.txt

The content of docs/requirements.txt would be similar to:

scipy==1.11.1
numpy==1.25.2
pandas==2.0.3
matplotlib==3.7.2

We are sending you this email because you are a maintainer of the following projects that are affected by this removal. Either using "Use system package" checkbox in the Admin UI, or the config key python.sytem_packages or python.use_system_site_packages in your .readthedocs.yaml file:

    [cherrypy](https://readthedocs.org/projects/cherrypy/)

    [twine](https://readthedocs.org/projects/twine/)

Read more about this in our [Reproducible builds](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html) guide for more details.
Keep documenting,
Read the Docs

**Comment by webknjaz** [comment]
Yeah, I got similar emails regarding other projects too. There's also a way to have even more control over the build process in RTD which I think is objectively better.. It's possible to use raw pip commands directly, with `-r` + `-c`.

**Comment by webknjaz** [comment]
Looks like our RTD config file never had this setting in the YAML config. So it must've been set in the UI, which is no longer relevant after https://github.com/cherrypy/cherrypy/pull/2008 and https://github.com/cherrypy/cherrypy/issues/2013.

So I'm closing this issue as there's no action items left to do here.
