### ISSUE TITLE
`path.py` has been renamed to `path`

### ISSUE THREAD

**Issue by mtelka** [cherrypy/cherrypy#2034]
The `path.py` [has been renamed](https://pypi.org/project/path.py/) to `path`, but it is still [listed in `setup.py`](https://github.com/cherrypy/cherrypy/blob/30d9a141c67ecb958ce305810203d89d60ef318b/setup.py#L95) as a test dependency.  Please update the `setup.py` file to do not use the deprecated `path.py`.  Thank you.

**Comment by webknjaz** [comment]
Sure, open a PR to update it.
