### ISSUE TITLE
Allow reuse of listener socket on UNIX

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#532]
Originally reported by: **Robert Brewer (Bitbucket: [fumanchu](http://bitbucket.org/fumanchu), GitHub: [fumanchu](http://github.com/fumanchu))**

---

Thought up by Joseph Tate and discussed [http://groups.google.com/group/cherrypy-devel/browse_thread/thread/a43a629ae31191ef/c34ea1b91a7db0df here] and [http://www.defuze.org/oss/cpirc/%23cherrypy.2006-05-05.log.html here]:

UNIX allows the re-use of sockets via socket.fromfd(fd). _cpwsgiserver could pass the fd from one process to another via os.environ. UNIX users could then employ signal handlers like these:

```
#!python

def sigusr1(signum, frame):
    """Re-exec the process."""
    cherrypy.server.stop()
    cherrypy.log("Re-executing %s %s" % (sys.executable, sys.argv))
    os.execv(sys.executable, [sys.executable] + sys.argv)

def sigusr2(signum, frame):
    """Restart the HTTP server."""
    cherrypy.server.restart()

signal.signal(signal.SIGUSR1, sigusr1)
signal.signal(signal.SIGUSR2, sigusr2)
```

See [1116] for an experimental implementation of the socket reuse. The signal handlers could either be stuck in /lib somewhere, or enabled by default on platforms where hasattr(signal, "SIGUSR1").

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/532

**Comment by webknjaz** [comment]
There's PR #1458 + #1494 implementing such behavior for systemd units mechanism called 'socket activation'.

**Comment by jaraco** [comment]
To the extent this has been implemented, it's complete. To the extent that it's lacking, I'm closing this as won't fix, though if someone is interested in expanding on the effort such as adding Windows support, I welcome the idea. Just create a new ticket and/or pull request and reference this one if appropriate.
