### ISSUE TITLE
Make CP static file performance comparable to Apache

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#571]
Originally reported by: **Robert Brewer (Bitbucket: [fumanchu](http://bitbucket.org/fumanchu), GitHub: [fumanchu](http://github.com/fumanchu))**

---

I can dream, can't I?

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/571

**Comment by jaraco** [comment]
> Nobody in their right mind will use CP for static file serving in a production setup anyways.

CP has adequate performance for many production setups, especially if it's an origin server behind a CDN (where performance of the origin server needs only to be adequate). For this purpose, CherryPy is more than suitable, in that it also provides all of the richness of CherryPy tools for managing headers and other aspects of the resources.

As for improving performance, this appears to be a wish more than an actionable proposal. I welcome optimizations, but for now I'm marking this as a won't fix.
