### ISSUE TITLE
Dispatcher nesting should be unfolded

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#687]
Originally reported by: **Robert Brewer (Bitbucket: [fumanchu](http://bitbucket.org/fumanchu), GitHub: [fumanchu](http://github.com/fumanchu))**

---

The ability to nest multiple dispatchers (i.e. have one dispatcher call another) is powerful and necessary; however, the current implementation suffers in that Python code cannot inspect the chain of dispatchers. For example:

```
#!python
from cherrypy.dispatch import *

hostmap = {'www.mydom2.com': '/mydom2',
           'www.mydom3.com': '/mydom3',
           'www.mydom4.com': '/dom4',
           }
vh = VirtualHost(next_dispatcher=XMLRPCDispatcher(), **hostmap)
cherrypy.tree.mount(root, config={'/': {'request.dispatch': vh}})
```

Although the !VirtualHost dispatcher wraps another dispatcher (and in this case, the XMLRPC dispatcher also wraps the default builtin CherryPy dispatcher), there is no interface exposed to Python code to inspect any dispatcher beyond the outermost one. Having just a simple means to iterate over the dispatchers involved in a chain would be a huge improvement.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/687

**Comment by jaraco** [comment]
I'm closing this as languishing, though I invite anyone to revive the effort as desired.
