### ISSUE TITLE
Session storage to Postgres fails for unicode string objects when using utf-8 based database

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#739]
Originally reported by: **guest (Bitbucket: [guest](http://bitbucket.org/guest), GitHub: [guest](http://github.com/guest))**

----------------------------------------

I'm using CherryPy 2.2.1 with Postgresql that has a database using UNICODE encoding. Storing sessions there breaks when the stored content start being non-ascii, as Python's pickle stores these strings as raw-unicode-escape, which stores nicely into an ISO-LATIN encoded database, but does not store into a UNICODE-encoded database.

A simple solution for me is to say `pickled_data = pickled_data.decode('raw-unicode-escape').encode('utf-8')` when saving and `pickled_data = pickled_data.decode('utf-8').encode('raw-unicode-escape')` when loading, but of course a proper fix should figure out the encoding used in the database and use that.

Or you should fix the documentation to say that the database where sessions are stored needs to use ISO-LATIN encoding (which then often will require a separate database for sessions which might be a problem).

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/739

**Comment by webknjaz** [comment]
PostgreSQL is cut off CherryPy. Closing.
