### ISSUE TITLE
PostgresqlSession is incomplete, broken, and too specific

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#748]
Originally reported by: **Robert Brewer (Bitbucket: [fumanchu](http://bitbucket.org/fumanchu), GitHub: [fumanchu](http://github.com/fumanchu))**

----------------------------------------

The current !PostgresqlSession class:

 1. Is incomplete without a get_db function. At the least, it should try to import pypgsql and psycopg.
 2. Is broken, since it doesn't even INSERT new rows.
 3. Is too specific. It should be transformed into a generic DBAPISession class (which would make it incomplete again, but why limit ourselves to a single provider for such a simple need?).

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/748

**Comment by jaraco** [comment]
I've stripped out the code, though it's always available in the parent of the aforementioned commit for posterity and in case anyone wants to revive the implementation.

For what it's worth, jaraco.mongodb provides a [sessions implementation in MongoDB](https://github.com/jaraco/jaraco.mongodb/blob/master/jaraco/mongodb/sessions.py), and third-party packages may be a good model for implementing functionality in other backends.
