### ISSUE TITLE
Replace sessions.py with something good

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#767]
Originally reported by: **Robert Brewer (Bitbucket: [fumanchu](http://bitbucket.org/fumanchu), GitHub: [fumanchu](http://github.com/fumanchu))**

---

The session library in CP isn't very good: it's hard to extend, partly because IMO it tries to do too much. For example, it shouldn't try to allow both eager and lazy locking. It also does too much at the class level instead of the instance level; that is, instead of instantiating a Session object per request, it should just stick all that state into cherrypy.request--it would then be free to instantiate a FileSession object per Application, rather than using class variables to manage config across requests.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/767

**Comment by jaraco** [comment]
This ticket is languishing. Feel free to revive the effort.
