### ISSUE TITLE
Add a subclass of WSPBus with Unix-native wait

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#769]
Originally reported by: **Robert Brewer (Bitbucket: [fumanchu](http://bitbucket.org/fumanchu), GitHub: [fumanchu](http://github.com/fumanchu))**

---

There's already one for Win32 which uses win32event.WaitForSingleObject. Surely there's a *nix equivalent.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/769

**Comment by jaraco** [comment]
This ticket is languishing. Feel free to revive the effort.

**Comment by webknjaz** [comment]
@jaraco I think, it's better to stay open. It's worth being investigated and implemented via [epoll](https://docs.python.org/3/library/select.html#select.epoll).
