### ISSUE TITLE
cherrypy doesn't handle case where URL path contains multiple slashes

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#815]
Originally reported by: **guest (Bitbucket: [guest](http://bitbucket.org/guest), GitHub: [guest](http://github.com/guest))**

---

If you feed something like

GET //status/Status/ HTTP/1.1

cherrypy will treat status as hostname and Status as path.

As a result links like http://localhost//status/Status/ will produce 404.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/815

**Comment by jaraco** [comment]
It looks like this work has been abandoned. I invite others to revive the effort as desired.

**Comment by webknjaz** [comment]
This should be covered by cherrypy/cheroot#39 and further improvements now.
