### ISSUE TITLE
Improve CherryPy logging

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#816]
Originally reported by: **Toni Ruža (Bitbucket: [raz](http://bitbucket.org/raz), GitHub: [raz](http://github.com/raz))**

---

Somewhere in cyberspace the following conversation was carried out:

```
01:08            raz  why is it that cp uses the python logging module in such a convoluted way?
01:08 @     fumanchu  backward compatibility
...
01:09 @     fumanchu  now that 3.1 is nearly done, maybe we can migrate to something better (with proper deprecation)
01:09            raz  that would be awesome
01:09 @     fumanchu  make a ticket :)
```

Here's my personal wishlist (in chronological order):
1. Get rid of the "cherrypy-layer", just use the logging module directly. The latter is brain damaged enough on it's own, no additional indirection needed.
2. Since CP logging is fairly performance critical (access.log!) it might make sense to reinvent the wheel one more time and write a custom logger. It could be a simple as a CP-specific stream-writer or it could become a full blown replacement for the brain damaged logging-module.
3. Did I mention that the python logging module is brain damaged?

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/816

**Comment by jaraco** [comment]
This ticket feels mostly like a rant about logging. A PR to improve the logging technique would be welcomed.
