### ISSUE TITLE
Additional installation folders

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#982]
Originally reported by: **guest (Bitbucket: [guest](http://bitbucket.org/guest), GitHub: [guest](http://github.com/guest))**

---

I recently installed CherryPy 3.20rc1 and it installs all the CherryPy files in c:\program files\python31\lib\site-packages\cherrypy (as expected).  However it also creates a folder in c:\program files\python31\cherrypy with subfolders tutorial, test and scaffold.  These folders are incomplete and look (to me) as though they may be part of a test environment, and are not necessary for the installation.

Regards,
Alan Harris-Reid

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/982

**Comment by jaraco** [comment]
I'm pretty sure this has been fixed in recent packaging fixes.
