### ISSUE TITLE
cherryd fails if a tree.app item is instance of _cpwsgi.VirtualHost

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#994]
Originally reported by: **Anonymous**

---

cherryd tries to call app.merge on line 22 to merge passed in config to any apps mounted.

_cpwsgi.VirtualHost doesn't support this. I think its a bit naive to assume that every app mounted needs to have the passed in config merged with its own current config. Whatever the solution, something needs to be fixed.

Reported by dasacc22@gmail.com

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/994

**Comment by jaraco** [comment]
This ticket is languishing. Feel free to revive the effort.
